feat(home-page): Build CMS Driven Homepage content using Modular Blocks
KiboSoftware/nextjs-storefront pull request #100
Opened 2022-08-03 15:37 UTC by kibo-geetanshuchhabra

2022-08-16 22:23 UTC, kibo-kevinwatts requested changes
Couple of notes but this is great!

2022-08-16 22:23 UTC, kibo-kevinwatts commented on lib/operations/get-page/index.ts
> +export const getHomePageCMSRes = async () => {
Lets modify these params a little so we can use re-use one getPage operation
and modify the response type so we can add more props later
```
export const getPage = async ({ contentTypeUid, referenceFieldPath}) => {
         const response = await Stack.getEntry({ ...

        return {
               components: response[0][0]?.page_components
        }
}
```

2022-08-16 22:23 UTC, kibo-kevinwatts commented on lib/operations/get-page/index.ts
> +export const getProductRes = async () => {
Can we modify or create something like "product_detail_page" in the CMS? That also has a "page_components" block?

2022-08-16 22:23 UTC, kibo-kevinwatts commented on pages/index.tsx
> +  const cmsResults = await getHomePageCMSRes()
this is a nitpick, can we rename this to `cmsPage`? so it would be `cmsPage?.components?.map`

2022-08-18 08:39 UTC, kibo-geetanshuchhabra commented on lib/operations/get-page/index.ts
> +export const getHomePageCMSRes = async () => {
Resolved

2022-08-18 08:39 UTC, kibo-geetanshuchhabra commented on lib/cms/content-stack/index.js
> +              Utils.jsonToHTML({
Resolved

2022-08-18 08:39 UTC, kibo-geetanshuchhabra commented on components/home/CmsComponent/CmsComponent.tsx
> +export default CmsComponent
Resolved

2022-08-18 17:41 UTC, kibo-kevinwatts approved these changes

2022-08-18 17:41 UTC, merged