feat(order-history): icky-662 Order history integration with my account page
KiboSoftware/nextjs-storefront pull request #101
Opened 2022-08-04 14:04 UTC by TriptiVermaXP

2022-08-05 14:49 UTC, kibo-kevinwatts commented on components/page-templates/OrderHistoryTemplate/OrderHistoryTemplate.tsx
> +    color: '#2b2b2b',
#2b2b2b is === grey.900, we can use that

2022-08-05 16:04 UTC, kibo-kevinwatts requested changes
good work :)

2022-08-08 11:31 UTC, kibo-sushant commented on hooks/queries/useUserOrderQueries/useUserOrderQueries.ts
> +  filters?: string | string[]
No mandatory prop? Can all the Props nullable?

2022-08-08 11:31 UTC, kibo-sushant commented on hooks/queries/useUserOrderQueries/useUserOrderQueries.ts
> +  })
In some of the places, we are building params in Component and passing the final one to hook but here we are building inside hook, for consistency purpose we should follow only one approach.
@kibo-kevinwatts , any specific recommendation?

2022-08-08 11:31 UTC, kibo-sushant commented on lib/constants/index.ts
> +  { label: 'Last 6 months', filterValue: 'M-6', isApplied: false, isDisplayed: true, count: 0 },
shouldn't these label come from translation?

2022-08-08 11:31 UTC, kibo-sushant commented on lib/helpers/buildOrdersFilterInput.ts
> +    pageSize: 20,
shouldn't pageSize be configurable?

2022-08-10 05:57 UTC, TriptiVermaXP commented on components/page-templates/OrderHistoryTemplate/OrderHistoryTemplate.tsx
> +  const orders = orderGetters.getNonAbandonedOrder(items as Order[])
Done

2022-08-10 05:57 UTC, TriptiVermaXP commented on lib/getters/orderGetters.ts
> +const getNonAbandonedOrder = (orders: Order[]) =>
Done

2022-08-10 05:58 UTC, TriptiVermaXP commented on lib/getters/orderGetters.ts
> +  order?.payments && order?.payments[0]?.billingInfo?.billingContact?.address
Resolved

2022-08-10 05:58 UTC, TriptiVermaXP commented on components/product-listing/FacetItemList/FacetItemList.tsx
> +    isUpdateRoute = true,
Done

2022-08-10 05:58 UTC, TriptiVermaXP commented on components/product-listing/FacetItem/FacetItem.tsx
> +    isUpdateRoute = true,
Done

2022-08-10 05:59 UTC, TriptiVermaXP commented on components/product-listing/FacetItem/FacetItem.tsx
> +    isElementVisible = true,
Done, this variable is used to show search and count, so renamed with showSearchAndCount.

2022-08-10 06:24 UTC, TriptiVermaXP commented on components/product-listing/FacetItem/FacetItem.tsx
> +    isUpdateRoute = true,
By default it is true, so will not affect existing functionality. Passing false if don't want to display into the DOM.

2022-08-10 06:24 UTC, TriptiVermaXP commented on components/common/FilterOrders/FilterOrders.tsx
> +        />
As discussed, not required.

2022-08-10 06:24 UTC, TriptiVermaXP commented on components/common/FilterOrders/FilterOrders.tsx
> +}
Done

2022-08-10 06:25 UTC, TriptiVermaXP commented on hooks/queries/useUserOrderQueries/useUserOrderQueries.ts
> +  filters?: string | string[]
All could be nullable because _view order details_ page only passing filter, and _view order status_ passing billingEmail & orderNumber both.

2022-08-10 06:25 UTC, TriptiVermaXP commented on hooks/queries/useUserOrderQueries/useUserOrderQueries.ts
> +  })
No changes required as discussed.

2022-08-10 06:25 UTC, TriptiVermaXP commented on lib/constants/index.ts
> +  { label: 'Last 6 months', filterValue: 'M-6', isApplied: false, isDisplayed: true, count: 0 },
Done

2022-08-10 06:25 UTC, TriptiVermaXP commented on lib/helpers/buildOrdersFilterInput.ts
> +    pageSize: 20,
Done

2022-08-11 23:41 UTC, kibo-kevinwatts approved these changes

2022-08-11 23:41 UTC, kibo-kevinwatts commented on lib/helpers/buildOrdersFilterInput.ts
> +  variables.filter = variables.filter.concat(' and status ne Abandoned')
Should this use the constant OrderStatus.ABANONDED?

2022-08-11 23:41 UTC, kibo-kevinwatts commented on hooks/queries/useUserOrderQueries/useUserOrderQueries.ts
> +  })
I think either is fine, as long as we stay consistent. 
I did a quick check, most places we are building params inside the hooks. we may need to change places where we are not

2022-08-12 10:31 UTC, kibo-sushant approved these changes

2022-08-12 10:32 UTC, merged