feat( wishlist ): icky-654
KiboSoftware/nextjs-storefront pull request #102
Opened 2022-08-04 15:32 UTC by amolpawar-kibo

2022-08-08 05:15 UTC, kibo-chandradeeptalaha commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +          <FavoriteRoundedIcon sx={{ color: '#BB2500', marginRight: '0.875rem' }} />{' '}
remove {' '}

2022-08-08 05:20 UTC, kibo-chandradeeptalaha commented on components/page-templates/WishlistTemplate/WishlistTemplate.spec.tsx
> +const ProductCardMock = () => <div data-testid="product-card-mock" />
Don't mock this. Try to match the mock data with the Product card if product name is correct or not

2022-08-08 09:09 UTC, kibo-sushant commented on hooks/mutations/useWishlist/useRemoveWishlistItemMutation/useRemoveWishlistItemMutation.ts
> +        }
I think instead of isRemovedFromWishlist params hook should accept delay time from the caller, and it should be also configurable. @kibo-kevinwatts advice please.

2022-08-10 10:09 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +          <FavoriteRoundedIcon sx={{ color: '#BB2500', marginRight: '0.875rem' }} />{' '}
Done

2022-08-10 10:13 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +              >
Overlay effect is used only in wishlist so keeping this outside from ProductCard component

2022-08-10 10:31 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +          <FavoriteRoundedIcon sx={{ color: '#BB2500', marginRight: '0.875rem' }} />{' '}
1. Instead of hardcoding colours can we use any Theme colour?
-This is unique  colour & only used for wishlist icon 
2. I think we don't have spacers defined in theme

2022-08-10 10:43 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +import { Maybe, WishlistItem } from '@/lib/gql/types'
Done

2022-08-10 10:43 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +const WishlistTemplate = (props: any) => {
Done.

2022-08-10 10:44 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +                  data-wishlist-item-id={item?.id}
Removed.

2022-08-10 10:44 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +  const [removedProduct, setRemovedProduct] = useState<WishlistProductInput>()
Done.

2022-08-10 10:44 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.stories.tsx
> +}
Done.

2022-08-10 10:49 UTC, amolpawar-kibo commented on components/product/ProductCard/ProductCard.tsx
> +import FavoriteRoundedIcon from '@mui/icons-material/FavoriteRounded'
No. Both the icons has not exported member of '"@mui/icons-material"'

2022-08-10 10:51 UTC, amolpawar-kibo commented on components/product/ProductCard/ProductCard.tsx
> +                  <FavoriteRoundedIcon sx={{ color: '#BB2500' }} />
This colour is used only for Wishlist icon. Do we need to add in theme?

2022-08-10 10:54 UTC, amolpawar-kibo commented on components/product/ProductCard/ProductCard.tsx
> +                  <FavoriteBorderRoundedIcon sx={{ color: '#cdcdcd', marginRight: '14px' }} />
From theme grey.600 is near to this '#cdcdcd'  colour but little bit darken. Should we use it or add new grey shade?

2022-08-10 11:00 UTC, amolpawar-kibo commented on components/product/ProductCard/ProductCard.tsx
> +    onAddOrRemoveWishlistItem && onAddOrRemoveWishlistItem()
When user clicks on wish list icon we are checking the that product is in wishlist or not then performing add/remove action. so I think we don't required this separate.

2022-08-10 11:22 UTC, amolpawar-kibo commented on hooks/mutations/useWishlist/useRemoveWishlistItemMutation/useRemoveWishlistItemMutation.ts
> +        }
We are display grey out product only in wishlist so I think no need of it to configurable

2022-08-11 23:28 UTC, kibo-kevinwatts requested changes

2022-08-11 23:28 UTC, kibo-kevinwatts commented on hooks/mutations/useWishlist/useRemoveWishlistItemMutation/useRemoveWishlistItemMutation.ts
> +        }
I agree, the delay time should be a parameter from the caller

2022-08-11 23:28 UTC, kibo-kevinwatts commented on components/product/ProductCard/ProductCard.tsx
> +                href={link}
should this be wrapped in a Next/Link instead of just href=link?

2022-08-11 23:28 UTC, kibo-kevinwatts commented on components/product/ProductCard/ProductCard.tsx
> +                  <FavoriteRoundedIcon sx={{ color: '#BB2500' }} />
I agree, this color is used in at least two different places, we should add to theme

2022-08-11 23:28 UTC, kibo-kevinwatts commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +          <FavoriteRoundedIcon sx={{ color: '#BB2500', marginRight: '0.875rem' }} />
lets go ahead and add color to theme

2022-08-12 09:19 UTC, amolpawar-kibo commented on components/product/ProductCard/ProductCard.tsx
> +                href={link}
Done.

2022-08-12 09:21 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +          <FavoriteRoundedIcon sx={{ color: '#BB2500', marginRight: '0.875rem' }} />
I have used existing theme error colour for the red icon & for grey used grey.600.  Is it fine or we need to add specific to wish list colour in theme?

2022-08-12 09:23 UTC, amolpawar-kibo commented on hooks/mutations/useWishlist/useRemoveWishlistItemMutation/useRemoveWishlistItemMutation.ts
> +        }
Done. added delay parameter

2022-08-12 11:29 UTC, amolpawar-kibo commented on components/product/ProductCard/ProductCard.spec.js
> +  })
Done.

2022-08-16 21:37 UTC, kibo-kevinwatts commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +          <FavoriteRoundedIcon sx={{ color: '#BB2500', marginRight: '0.875rem' }} />
The grey.600 re use is good
I wouldn't re-use the error color for wishlist though. Probably add a new "red" property to the palette and use that, like we do for grey.

2022-08-17 08:12 UTC, amolpawar-kibo commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +          <FavoriteRoundedIcon sx={{ color: '#BB2500', marginRight: '0.875rem' }} />
Done.

2022-08-17 21:09 UTC, kibo-kevinwatts approved these changes

2022-08-18 07:26 UTC, kibo-sushant approved these changes

2022-08-18 07:38 UTC, merged