feat: apply promo code and update order
KiboSoftware/nextjs-storefront pull request #105
Opened 2022-08-12 12:29 UTC by sss-bct

2022-08-17 04:37 UTC, amolpawar-kibo commented on components/page-templates/Checkout/Checkout.tsx
> +      }
I think we should add promoMessage into public/locales/en/common.json or We can create new file for errors so it will help in future for error handling. @kibo-kevinwatts, please suggest us.

2022-08-17 04:37 UTC, amolpawar-kibo commented on lib/gql/mutations/coupon/updateOrderCoupon.ts
> +const updateOrderCouponMutation = /* GraphQL */ `
can we add spacing in between import & mutation definition

2022-08-17 06:30 UTC, TriptiVermaXP requested changes
Please take a look.

2022-08-17 06:30 UTC, TriptiVermaXP commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
>    const handleRemoveCouponCode = (item: any) => {
_Item_ type should be defined.
All static promo messages should be localized.
Inside the style, _backgroundColor: '#DCDCDC'_ should come from theme, if exact color not present please use nearest color code present.

2022-08-17 06:30 UTC, TriptiVermaXP commented on components/page-templates/Checkout/Checkout.tsx
>      backLabel: 'Go Back',
Please localize texts are used in orderSummaryArgs.

2022-08-17 17:59 UTC, sss-bct commented on components/page-templates/Checkout/Checkout.tsx
> +      }
Actually this error message is available in API response, so updated accordingly. Thank you.

2022-08-17 17:59 UTC, sss-bct commented on lib/gql/mutations/coupon/updateOrderCoupon.ts
> +const updateOrderCouponMutation = /* GraphQL */ `
Done.

2022-08-17 18:00 UTC, sss-bct commented on components/common/OrderPrice/OrderPrice.tsx
> +          />
Yes as per mockup when there is promo applied. Handled in other pages as well.

2022-08-17 18:00 UTC, sss-bct commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
>    const handleRemoveCouponCode = (item: any) => {
Done.

2022-08-17 18:00 UTC, sss-bct commented on components/page-templates/Checkout/Checkout.tsx
>      backLabel: 'Go Back',
Done.

2022-08-22 15:09 UTC, sss-bct commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +    }
Done.

2022-08-22 15:09 UTC, sss-bct commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +              aria-label="remove-promo-code"
No. actually aria-label is used to access element in test.

2022-08-22 15:09 UTC, sss-bct commented on components/common/OrderPrice/OrderPrice.tsx
> +  discountedSubtotal?: string
Actually it's optional , it will be required if any discount applied.

2022-08-22 15:09 UTC, sss-bct commented on __mocks__/stories/cartCouponMock.ts
> +export const cartCouponResponse: Cart = {
Yes. Updated the cartMock and reused.

2022-08-22 15:09 UTC, sss-bct commented on __mocks__/stories/orderCouponMock.ts
> +export const orderCouponResponse: Order = {
Yes. Updated the orderMock and reused.

2022-08-22 15:11 UTC, sss-bct commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
>        ))}
Done all except setError as undefined.

2022-08-24 08:27 UTC, TriptiVermaXP approved these changes

2022-08-24 12:58 UTC, sss-bct commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
>        ))}
Done.

2022-08-24 13:56 UTC, sss-bct commented on hooks/mutations/useCouponMutation/useDeleteCartCouponMutation/useDeleteCartCouponMutation.ts
> +      queryClient.invalidateQueries(cartKeys.all)
Actually apart from making data stale 'invalidateQueries' has the ability to do background refetch where removeQuery will reload .

2022-08-24 13:56 UTC, sss-bct commented on hooks/mutations/useCouponMutation/useDeleteOrderCouponMutation/useDeleteOrderCouponMutation.ts
> +      queryClient.invalidateQueries(checkoutKeys.all)
Actually apart from making data stale 'invalidateQueries' has the ability to do background refetch where removeQuery will reload .

2022-08-24 13:56 UTC, sss-bct commented on hooks/mutations/useCouponMutation/useUpdateCartCouponMutation/useUpdateCartCouponMutation.ts
> +      queryClient.invalidateQueries(cartKeys.all)
Actually apart from making data stale 'invalidateQueries' has the ability to do background refetch where removeQuery will reload .

2022-08-24 21:47 UTC, kibo-kevinwatts approved these changes
This looks good to me, but i am unsure on the `reactqueryclient.invalidate` vs remove

2022-08-26 09:25 UTC, sss-bct commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +  })
Done.

2022-08-26 09:26 UTC, sss-bct commented on components/page-templates/Checkout/Checkout.tsx
> +
Done.

2022-08-26 09:26 UTC, sss-bct commented on components/page-templates/Checkout/Checkout.tsx
> +
Done.

2022-08-26 09:29 UTC, kibo-sushant approved these changes

2022-08-26 13:01 UTC, merged