feat(vieworderstatus): feature/icky-626 View order status implemented
KiboSoftware/nextjs-storefront pull request #106
Opened 2022-08-16 15:46 UTC by TriptiVermaXP

2022-08-17 21:43 UTC, kibo-kevinwatts requested changes

2022-08-17 21:43 UTC, kibo-kevinwatts commented on components/page-templates/OrderStatusTemplate/OrderStatusTemplate.tsx
> +            onShowOrderHistoryItem={handleShowOrderHistoryItem}
since we are reusing this ViewOrderDetails component, should we rename this prop `onShowOrderHistoryItem`
it took me a second to understand what it was for

2022-08-17 21:43 UTC, kibo-kevinwatts commented on components/order/ViewOrderStatus/ViewOrderStatus.tsx
> +export interface OrderStatusFormData {
good rename!

2022-08-17 21:43 UTC, kibo-kevinwatts commented on components/page-templates/OrderStatusTemplate/OrderStatusTemplate.tsx
> +        {!selectedOrder && <ViewOrderStatus onOrderStatusSubmit={handleOrderStatusSubmit} />}
I think we're missing a warning message here, if there are no orders found.
The ViewOrderStatus component should have a prop to pass a message to it

2022-08-18 08:34 UTC, kibo-sushant commented on components/page-templates/OrderStatusTemplate/OrderStatusTemplate.tsx
> +  }, [items])
Without state (setSelectedOrder) will it not work (just doubt)?

2022-08-18 08:34 UTC, kibo-sushant commented on components/page-templates/OrderStatusTemplate/OrderStatusTemplate.tsx
> +export default OrderStatusTemplate
Storybook story is not interactive

2022-08-18 08:34 UTC, kibo-sushant commented on components/page-templates/OrderStatusTemplate/OrderStatusTemplate.spec.tsx
> +})
Not testing whether KiboBreadcrumbs are displayed or not?

Missing testcases
1.  should display ViewOrderStatus component when the order is not selected
2. should display ViewOrderDetails component when then order is selected

2022-08-18 13:27 UTC, TriptiVermaXP commented on components/page-templates/OrderStatusTemplate/OrderStatusTemplate.tsx
> +  }, [items])
Done

2022-08-18 13:27 UTC, TriptiVermaXP commented on components/order/ViewOrderDetails/ViewOrderDetails.spec.tsx
> +    expect(screen.getByText(/order-history/i)).toBeVisible()
Done

2022-08-18 13:28 UTC, TriptiVermaXP commented on components/order/ViewOrderDetails/ViewOrderDetails.tsx
> +import { AddressCard, FullWidthDivider, OrderSummary, ProductItemList } from '@/components/common'
Removed

2022-08-18 13:28 UTC, TriptiVermaXP commented on components/page-templates/OrderStatusTemplate/OrderStatusTemplate.tsx
> +        {!selectedOrder && <ViewOrderStatus onOrderStatusSubmit={handleOrderStatusSubmit} />}
Done by adding <Box color="warning.main">{lookupWarningMessage}</Box>

2022-08-18 13:28 UTC, TriptiVermaXP commented on components/page-templates/OrderStatusTemplate/OrderStatusTemplate.tsx
> +            onShowOrderHistoryItem={handleShowOrderHistoryItem}
Renamed to onGoBackToOrderHistory as it is using for navigation only and made it optional in ViewOrderDetails  component as its not required for view order status.

2022-08-18 15:29 UTC, kibo-kevinwatts approved these changes

2022-08-18 15:30 UTC, kibo-sushant approved these changes

2022-08-18 15:31 UTC, merged