feat: my-account payments implementation
KiboSoftware/nextjs-storefront pull request #108
Opened 2022-08-18 11:35 UTC by kibo-chandradeeptalaha

2022-08-19 05:41 UTC, kibo-sushant commented on components/page-templates/MyAccountTemplate/MyAccountTemplate.tsx
> +import { CustomerAccount } from '@/lib/gql/types'
use import type {

2022-08-19 05:45 UTC, kibo-sushant commented on components/my-account/PaymentMethod.tsx
> +import { AddressType } from '@/lib/constants'
use import type {

2022-08-19 08:58 UTC, kibo-sushant commented on components/my-account/PaymentMethod.tsx
> +  const { showModal, closeModal } = useModalContext()
if we are not using closeModal, then we should delete it.

2022-08-19 11:55 UTC, TriptiVermaXP requested changes
Please take a look review comments.
@kibo-chandradeeptalaha I just noticed, Is storybook not created for PaymentMethod.tsx?

2022-08-19 11:55 UTC, TriptiVermaXP commented on components/common/AddressForm/AddressForm.tsx
> +              label={'Make this my default payment'}
Please use localized key.

2022-08-19 11:55 UTC, TriptiVermaXP commented on hooks/mutations/useCustomerCardsMutation/useCustomerCardsMutation.ts
> +    deleteSavedCardDetails: useMutation(deleteCustomerAccountCardDetails, {
Should we create separate hooks for CRUD to have single responsibility?
@kibo-sushant  please suggest.

2022-08-19 11:55 UTC, TriptiVermaXP commented on lib/constants/index.ts
> +}
Should we move to Constant file?

2022-08-19 11:55 UTC, TriptiVermaXP commented on hooks/mutations/useCustomerAddressMutation/useCustomerAddressMutation.ts
> +    deleteSavedAddressDetails: useMutation(deleteCustomerAccountContactDetails),
Should we create separate hooks for each CRUD to have single responsibility?
@kibo-sushant please suggest.

2022-08-19 11:55 UTC, TriptiVermaXP commented on components/page-templates/MyAccountTemplate/MyAccountTemplate.tsx
> +          <FullWidthDivider sx={{ backgroundColor: 'grey.500', ...style.divider }} />
Do we need to use FullWidthDivider as we are going to handle fullwidth differently?

2022-08-19 15:43 UTC, kibo-kevinwatts requested changes

2022-08-19 15:43 UTC, kibo-kevinwatts commented on hooks/mutations/useCustomerCardsMutation/useCustomerCardsMutation.ts
> +  await client.request({
I know you're invalidating the queries here, so its not required. 
but lets go ahead and return the response here

2022-08-19 15:43 UTC, kibo-kevinwatts commented on hooks/mutations/useCustomerCardsMutation/useCustomerCardsMutation.ts
> +    deleteSavedCardDetails: useMutation(deleteCustomerAccountCardDetails, {
lets separate them

2022-08-19 15:43 UTC, kibo-kevinwatts commented on hooks/mutations/useCustomerAddressMutation/useCustomerAddressMutation.ts
> +import { CustomerContactInput } from '@/lib/gql/types'
import type {

2022-08-19 15:43 UTC, kibo-kevinwatts commented on components/checkout/CardDetailsForm/CardDetailsForm.tsx
> +    const saveCardData = { ...cardData, isCardDetailsValidated: isValid, isDataUpdated: true }
Not sure if it would handle all of your use cases here.
But for "isDataUpdated" the react hook form does have a state variable that may help
"isDirty"
https://react-hook-form.com/api/useformstate

2022-08-19 20:35 UTC, kibo-kevinwatts commented on hooks/mutations/useCustomerAddressMutation/useCustomerAddressMutation.ts
> +  }
Shouldn't we be invalidating other queries on sucessful mutation?

2022-08-22 05:17 UTC, kibo-chandradeeptalaha commented on components/page-templates/MyAccountTemplate/MyAccountTemplate.tsx
> +import { CustomerAccount } from '@/lib/gql/types'
Done

2022-08-22 05:18 UTC, kibo-chandradeeptalaha commented on components/my-account/PaymentMethod.tsx
> +} from '@/lib/types'
Done

2022-08-22 05:18 UTC, kibo-chandradeeptalaha commented on components/my-account/PaymentMethod.tsx
> +import { CustomerAccount, CustomerContactInput } from '@/lib/gql/types'
Done

2022-08-22 05:19 UTC, kibo-chandradeeptalaha commented on components/my-account/PaymentMethod.tsx
> +        contentText: 'Are you sure ?',
Done

2022-08-22 05:22 UTC, kibo-chandradeeptalaha commented on components/checkout/CardDetailsForm/CardDetailsForm.tsx
> +      if (!isEdit) {
when cardnumber is tokenized, isEdit is true. else false

2022-08-22 06:02 UTC, kibo-chandradeeptalaha commented on components/my-account/PaymentMethod.tsx
> +  const { showModal, closeModal } = useModalContext()
Done

2022-08-22 06:02 UTC, kibo-chandradeeptalaha commented on components/common/AddressForm/AddressForm.tsx
> +              label={'Make this my default payment'}
Done

2022-08-22 06:54 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useCustomerCardsMutation/useCustomerCardsMutation.ts
> +  await client.request({
Done

2022-08-22 06:54 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useCustomerAddressMutation/useCustomerAddressMutation.ts
> +import { CustomerContactInput } from '@/lib/gql/types'
Done

2022-08-22 06:54 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useCustomerAddressMutation/useCustomerAddressMutation.ts
> +  }
Done

2022-08-22 06:57 UTC, kibo-chandradeeptalaha commented on components/page-templates/MyAccountTemplate/MyAccountTemplate.tsx
> +          <FullWidthDivider sx={{ backgroundColor: 'grey.500', ...style.divider }} />
Removed

2022-08-22 06:57 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useCustomerAddressMutation/useCustomerAddressMutation.ts
> +    deleteSavedAddressDetails: useMutation(deleteCustomerAccountContactDetails),
Done

2022-08-22 12:30 UTC, kibo-chandradeeptalaha commented on components/checkout/AddressDetailsView/AddressDetailsView.tsx
> +          onChange={(value) => handleRadioChange && handleRadioChange(value)}
Done

2022-08-22 12:30 UTC, kibo-chandradeeptalaha commented on components/checkout/CardDetailsForm/CardDetailsForm.tsx
> +
Handled

2022-08-22 12:30 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useCustomerCardsMutation/useCustomerCardsMutation.ts
> +    deleteSavedCardDetails: useMutation(deleteCustomerAccountCardDetails, {
Done

2022-08-22 22:54 UTC, kibo-kevinwatts approved these changes

2022-08-23 10:47 UTC, kibo-sushant approved these changes

2022-08-24 08:25 UTC, TriptiVermaXP approved these changes
Over all looks good, approving the PR but please take a look additional comments.

2022-08-24 08:25 UTC, TriptiVermaXP commented on hooks/mutations/useCustomerAddressMutation/useDeleteCustomerAddressMutation.ts
> +
Spec files are missing for useCustomerAddressMutation hooks. 
deleteCustomerAccountContact missing in msw.

2022-08-24 08:25 UTC, TriptiVermaXP commented on hooks/mutations/useCustomerCardsMutation/useDeleteCustomerCardsMutation.ts
> +import { makeGraphQLClient } from '@/lib/gql/client'
Spec files are missing for useCustomerCardsMutation hooks. 
deleteCustomerAccountCard missing in msw.

2022-08-25 09:12 UTC, kibo-chandradeeptalaha commented on __test__/e2e/integration/page-template/MyAccountTemplate/MyAccountTemplate.spec.tsx
> +import { Card } from '@/lib/gql/types'
Done

2022-08-25 10:47 UTC, merged