feat: categorytree-cache-implementation
KiboSoftware/nextjs-storefront pull request #110
Opened 2022-08-23 06:44 UTC by kibo-sushant

2022-08-23 22:35 UTC, kibo-kevinwatts requested changes
overall this looks good

2022-08-23 22:35 UTC, kibo-kevinwatts commented on lib/gql/client/index.ts
> +export function makeCategoryTreeGraphQLClient(endpoint?: string) {
do we need this? We're just doing a fetch to an api endpoint? we don't need a gql client

2022-08-24 07:31 UTC, TriptiVermaXP approved these changes

2022-08-26 08:32 UTC, kibo-sushant commented on lib/api/operations/get-category-tree.ts
> +const key = serverRuntimeConfig.cacheKey
Resolved

2022-08-26 08:32 UTC, kibo-sushant commented on lib/api/operations/get-category-tree.ts
> +      return response
Resolved

2022-08-26 08:34 UTC, kibo-sushant commented on lib/gql/client/index.ts
> +export function makeCategoryTreeGraphQLClient(endpoint?: string) {
Resolved using browser fetch, I don't think vercel-fetch still ready to use in browser
![image](https://user-images.githubusercontent.com/89385472/186859773-5945d3c7-6391-4d81-8628-6f6c89351cba.png)

2022-08-26 17:14 UTC, kibo-kevinwatts approved these changes

2022-08-26 17:14 UTC, merged