feat(my account): addressbook
KiboSoftware/nextjs-storefront pull request #111
Opened 2022-08-23 11:52 UTC by amolpawar-kibo

2022-08-24 06:36 UTC, kibo-chandradeeptalaha commented on components/dialogs/MyAccount/DeleteAddressConfirmationDialog/DeleteAddressConfirmationDialog.tsx
> +  isOpen: boolean
we don't need this prop

2022-08-24 22:18 UTC, kibo-kevinwatts requested changes

2022-08-24 22:18 UTC, kibo-kevinwatts commented on lib/helpers/buildAddressProps.ts
> +export const buildAddressProps = (address: CuAddress | CrAddress) => {
We haven't been using "helpers" like this. Use getters to get values from data or use a function isolated to the component

2022-08-24 22:18 UTC, kibo-kevinwatts commented on lib/helpers/buildAddressParams.ts
> +  return action === 'update' ? updateAddressParams : addressParams
accountId is listed twice in addressParams
Why use 'action' for this helper? if its new, contact id won't exist. can just use that?

2022-08-24 22:18 UTC, kibo-kevinwatts commented on components/my-account/AddressBook/AddressBook.tsx
> +      {isAuthenticated && !isAddNewAddress && !isEditAddress && (
isAuthenticated shouldnt be needed. the my-account page is a protected  route (only auth users can see it)

2022-08-24 22:18 UTC, kibo-kevinwatts commented on components/my-account/AddressBook/AddressBook.tsx
> +              <Link href="" passHref>
If we're not navigating anywhere, why next/link?

2022-08-26 10:41 UTC, amolpawar-kibo commented on components/dialogs/MyAccount/DeleteAddressConfirmationDialog/DeleteAddressConfirmationDialog.tsx
> +  isOpen: boolean
Done.

2022-08-26 10:45 UTC, amolpawar-kibo commented on components/common/AddressForm/AddressForm.tsx
> -  checkout: Order | undefined
Resolved in merged PR https://github.com/KiboSoftware/nextjs-storefront/pull/108

2022-08-26 10:46 UTC, amolpawar-kibo commented on components/dialogs/MyAccount/DeleteAddressConfirmationDialog/DeleteAddressConfirmationDialog.tsx
> +const DeleteAddressConfirmationDialog = (props: DeleteAddressConfirmationDialogProps) => {
Resolved in merged PR https://github.com/KiboSoftware/nextjs-storefront/pull/108

2022-08-26 10:46 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +      {isAuthenticated && !isAddNewAddress && !isEditAddress && (
Done.

2022-08-26 11:26 UTC, amolpawar-kibo commented on lib/helpers/buildAddressParams.ts
> +  return action === 'update' ? updateAddressParams : addressParams
Done.  accountId is required in both the places as per arguments needed in createCustomerAccountContact mutation

2022-08-26 15:59 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +              <Link href="" passHref>
Done

2022-08-26 16:00 UTC, amolpawar-kibo commented on lib/helpers/buildAddressProps.ts
> +export const buildAddressProps = (address: CuAddress | CrAddress) => {
Done. used from addressGetters

2022-08-30 06:46 UTC, kibo-chandradeeptalaha requested changes
Please take a look

2022-08-30 08:42 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +          <AddCircleOutlineIcon sx={{ paddingRight: '1rem' }} />
Done

2022-08-30 10:40 UTC, TriptiVermaXP requested changes
Please take a look review comments.
One thing I notices, ConfirmationDialog is placed inside /Dialogs/MyAccount, shouldn't be directly inside the /Dialogs as it could be used in other places?
@kibo-kevinwatts Please suggest.

2022-08-30 10:40 UTC, TriptiVermaXP commented on components/my-account/AddressBook/AddressBook.tsx
> +              {t('primary')}
Primary - Fontsize and weight are not matching with wireframe.
Edit - Fontsize is not matching with wireframe.
Space between Edit and Delete icon should be little less.

2022-08-30 10:40 UTC, TriptiVermaXP commented on components/my-account/AddressBook/AddressBook.tsx
> +  const [editAddress, setEditAddress] = useState<CustomerContact>()
Please group the states, hooks and methods.

2022-08-30 10:40 UTC, TriptiVermaXP commented on components/my-account/AddressBook/AddressBook.tsx
> +        })
buildAddressParams code is repetitive in both the blocks if-else.
 Also use  AddressType.SHIPPING constant.
 How we are handing this for billing address?

2022-08-30 10:40 UTC, TriptiVermaXP commented on components/my-account/AddressBook/AddressBook.tsx
> +        contentText: t('are-you-sure-you-want-to-delete-this-address'),
This key is too long, can we have some short one eg: delete-address-confirmation or something better.

2022-08-30 10:40 UTC, TriptiVermaXP commented on components/my-account/AddressBook/AddressBook.tsx
> +        <Box paddingY={1} key={item?.id + 'address'}>
Avoid using concatenation, try to use backquote

2022-08-30 10:40 UTC, TriptiVermaXP commented on components/my-account/AddressBook/AddressBook.tsx
> +                onClick={() => handleEditAddress(item as CustomerContact)}
Try to use verb/action at the end for all methods.
@kibo-sushant Please suggest if its applicable.

2022-08-30 10:40 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/MyAccountTemplate/MyAccountTemplate.spec.tsx
> +
Integration tests are missing for add, update and delete the address.
Also graphql mocks are missing in msw.

2022-08-30 10:40 UTC, TriptiVermaXP commented on components/my-account/AddressBook/AddressBook.tsx
> +  Maybe,
Remove unused Maybe

2022-08-30 17:21 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +  const addresses = userAddressGetters.getUserShippingAddress(contacts?.items)
Done.

2022-08-30 17:21 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +          <AddCircleOutlineIcon sx={{ paddingRight: '1rem' }} />
Done.

2022-08-30 17:21 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +            <Box sx={{ display: 'block' }}>
Done.

2022-08-30 17:22 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +            <Box sx={{ display: 'flex', flexDirection: 'column' }}>
Done.

2022-08-30 17:22 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +          addressType: 'shipping',
Done.

2022-08-30 17:22 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +      {addresses?.map((item: Maybe<CustomerContact>, index: number) => (
Done.

2022-09-01 07:00 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +              {t('primary')}
Resolved in merged PR https://github.com/KiboSoftware/nextjs-storefront/pull/108

2022-09-01 07:06 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +  const [editAddress, setEditAddress] = useState<CustomerContact>()
Done.

2022-09-01 07:07 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +        })
Done.

2022-09-01 07:07 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +        <Box paddingY={1} key={item?.id + 'address'}>
Done.

2022-09-01 07:07 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +  Maybe,
Done

2022-09-02 15:01 UTC, TriptiVermaXP approved these changes

2022-09-02 15:13 UTC, amolpawar-kibo commented on components/my-account/AddressBook/AddressBook.tsx
> +        contentText: t('are-you-sure-you-want-to-delete-this-address'),
Done.

2022-09-02 16:43 UTC, amolpawar-kibo commented on __test__/e2e/integration/page-template/MyAccountTemplate/MyAccountTemplate.spec.tsx
> +
Done.

2022-09-02 17:12 UTC, kibo-chandradeeptalaha approved these changes
Looks good. just check this one thing

2022-09-02 17:12 UTC, kibo-chandradeeptalaha commented on components/my-account/AddressBook/AddressBook.tsx
> +  const { address1, address2, cityOrTown, stateOrProvince, postalOrZipCode } = address
if we are sending only CuAddress as param, we don't need the CrAddress type.

2022-09-02 21:02 UTC, kibo-kevinwatts approved these changes

2022-09-02 21:02 UTC, merged