feat(my-profile):icky 661 my account my profile
KiboSoftware/nextjs-storefront pull request #112
Opened 2022-08-25 04:13 UTC by kibo-Kripa

My account my profile. 
User can edit and save name, email id and password

2022-08-25 21:17 UTC, kibo-kevinwatts requested changes

2022-08-25 21:17 UTC, kibo-kevinwatts commented on components/my account/my profile/MyProfile.tsx
> +  const [currentUser, setCurrentUser] = useState({
nothing in here should set the 'currentUser' , if this is for "formData" please update the name

2022-08-25 21:17 UTC, kibo-kevinwatts commented on components/my account/my profile/MyProfile.tsx
> +  interface disable {
don't define typescript types within component, should be at top of the file

2022-08-25 21:17 UTC, kibo-kevinwatts commented on components/my account/my profile/MyProfile.tsx
> +      setDisableButton({ forName: true, forEmail: true })
We need more validation than this, check other forms, 'yup' for examples

2022-08-25 21:17 UTC, kibo-kevinwatts commented on components/my account/my profile/MyProfile.tsx
> +  } = useForm({
Take a look at other forms that use, "yup" for validation.
Also want to make use of "isValid" to check form state is valid and the "handleSubmit" methods that ensure the form is valid before taking some action.
Currently, your handlers (at least for password) are doing no validation

2022-08-30 07:05 UTC, kibo-chandradeeptalaha commented on components/my account/my profile/MyProfile.tsx
> +                <Password fontSize='small'></Password>
use "**********" instead of icon.

2022-08-30 07:05 UTC, kibo-chandradeeptalaha requested changes
Rebase the code. Remove the paading of the myProfile section.
Initial render doesn't show firstname/email.
Replace the password icon for display value with string "*************"

2022-08-30 14:08 UTC, kibo-Kripa commented on hooks/mutations/useProfile/useChangeCustomerData/useUpdateCustomerData.ts
> +export const useUpateUserMutations = () => {
resolved

2022-08-30 14:08 UTC, kibo-Kripa commented on components/my account/my profile/MyProfile.tsx
> +  const style = {
resolved

2022-09-01 01:42 UTC, kibo-Kripa commented on hooks/mutations/useProfile/useUpdateCustomerPassword/useUpdatePassword.ts
> +}
Done

2022-09-01 01:42 UTC, kibo-Kripa commented on components/my account/my profile/MyProfile.tsx
> +                  {editPassword ? 'Edit Password' : 'Password'}
Done

2022-09-01 01:42 UTC, kibo-Kripa commented on components/my account/my profile/MyProfile.tsx
> +                  {editEmail ? 'Edit Email' : 'Email'}
Resolved

2022-09-01 01:43 UTC, kibo-Kripa commented on components/my account/my profile/MyProfile.tsx
> +                  {editName ? 'Edit Customer Name' : 'Customer Name'}
resolved

2022-09-01 01:44 UTC, kibo-Kripa commented on components/my account/my profile/MyProfile.tsx
> +  interface disable {
resolved

2022-09-01 01:45 UTC, kibo-Kripa commented on components/my account/my profile/MyProfile.tsx
> +import { useUpdateUserPasswordMutations } from '@/hooks/mutations/useProfile/useUpdateCustomerPassword/useUpdatePassword'
Done

2022-09-01 01:47 UTC, kibo-Kripa commented on components/my account/my profile/MyProfile.tsx
> +  })
Done

2022-09-01 02:15 UTC, kibo-Kripa commented on components/my account/my profile/MyProfile.tsx
> +                  }}
Done

2022-09-01 04:19 UTC, kibo-Kripa commented on components/my account/my profile/MyProfile.tsx
> +                <Password fontSize='small'></Password>
done

2022-09-16 04:56 UTC, kibo-chandradeeptalaha requested changes
Please take a look

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/MyProfile/MyProfile.spec.tsx
> +    const editName = screen.getAllByText(/edit/i)
change editName to allEditLinks.

change all editName variables to editLink(singular) / allEditLinks(plural)

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/MyProfile/MyProfile.spec.tsx
> +    expect(editName[0]).toBeVisible()
assert if all the edit links are visible or not. No only the first one

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/MyProfile/MyProfile.spec.tsx
> +  it('should render component', () => {
Test the passed values from story are visible or not.

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/MyProfile/MyProfile.spec.tsx
> +const KiboTextBoxMock = () => <input data-testid="text-box-mock" onChange={onChangMock} />
Don't mock these. Try to test if firstName/Lastname textbox is visible or not if we click on the respective edit link. 
Do these for all

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/ProfileDetailsForm/ProfileDetailsForm.tsx
> +import React, { useEffect, useState } from 'react'
Add localization for strings that will be visible on the UI. eg: for error messages defined inside schema

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/ProfileDetailsForm/ProfileDetailsForm.tsx
> +import KiboTextBox from '@/components/common/KiboTextBox/KiboTextBox'
change to 

import { PasswordValidation, KiboTextBox  } from '@/components/common'

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/ProfileDetailsForm/ProfileDetailsForm.stories.tsx
> +  isEmailForm: false,
isPasswordForm missing

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/ProfileDetailsForm/ProfileDetailsForm.stories.tsx
> +  title: 'My Profile/ProfileDetailsForm',
add argTypes of 
onSaveProfileData , onCancel

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/ProfileDetailsForm/ProfileDetailsForm.spec.tsx
> +const KiboTextBoxMock = () => (
Don't mock. Try to test using the props. if isEmailForm is true, does the email textbox appears ? 
Try to do like this for all

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on components/my-account/ProfileDetailsForm/ProfileDetailsForm.spec.tsx
> +  it('should render component', () => {
More testcases required depending on the props passed

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useProfile/useUpdateUserData/useUpdateUserData.ts
> +  customerAccountInput: UpdateUserDataInput
We do have a type for CustomerAccountInput no ? Can you check ?

2022-09-16 04:56 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useProfile/useUpdateUserPassword/useUpdateUserPassword.ts
> +  passwordInfoInput: UpdateUserPasswordInput
check if we have types for passwordInfoInput

2022-09-26 22:51 UTC, kibo-kevinwatts requested changes

2022-09-26 22:51 UTC, kibo-kevinwatts commented on components/my-account/ProfileDetailsForm/ProfileDetailsForm.tsx
> +  const buildParam = (formData: ProfileDetails) => {
Should this function be in the component and not in the hook?
its mostly just returning the same object anyway?

2022-09-26 22:51 UTC, kibo-kevinwatts commented on hooks/mutations/useProfile/useUpdateUserPassword/useUpdateUserPassword.ts
> +        queryClient.invalidateQueries(loginKeys.user)
this isn't necessary

2022-09-26 22:51 UTC, kibo-kevinwatts commented on test-report.xml
> +<testExecutions version="1">
delete this and update git ignore to ignore report file

2022-09-26 22:51 UTC, kibo-kevinwatts commented on components/my-account/ProfileDetailsForm/ProfileDetailsForm.tsx
> +        return schema
Is this the same way we are doing password validation in other forms?
@kibo-sushant ?

2022-09-26 22:51 UTC, kibo-kevinwatts commented on components/my-account/MyProfile/MyProfile.tsx
> +    setCurrentUser({
What is this "currentUser" in this component for?

2022-09-27 07:24 UTC, kibo-chandradeeptalaha commented on components/my-account/ProfileDetailsForm/ProfileDetailsForm.tsx
> +  const buildParam = (formData: ProfileDetails) => {
I created this to pass the exact object based on the form type to the parent component.

2022-09-27 08:04 UTC, kibo-chandradeeptalaha commented on components/my-account/MyProfile/MyProfile.tsx
> +    setCurrentUser({
Removed it.

2022-09-27 08:04 UTC, kibo-chandradeeptalaha commented on test-report.xml
> +<testExecutions version="1">
Done

2022-09-27 08:04 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useProfile/useUpdateUserPassword/useUpdateUserPassword.ts
> +        queryClient.invalidateQueries(loginKeys.user)
Removed

2022-09-29 11:23 UTC, amolpawar-kibo commented on components/my-account/MyProfile/MyProfile.tsx
> +    try {
could you please destructure props & use it?
ex. const {oldPassword} = updatedPassword

2022-09-29 11:25 UTC, amolpawar-kibo commented on components/my-account/MyProfile/MyProfile.tsx
> +          firstName: profileFormData.firstName || firstName,
could you please destructure props & use it?

2022-09-29 11:35 UTC, amolpawar-kibo commented on components/my-account/MyProfile/MyProfile.tsx
> +                  setCurrentEditableField(each.id)
Could you please rewrite onClick={() => {
                  setCurrentEditableField(each.id)} to onClick={() => setCurrentEditableField(each.id)}

2022-10-03 21:25 UTC, kibo-kevinwatts approved these changes

2022-10-03 21:26 UTC, kibo-kevinwatts commented
lets resolve the conflicts and get this merged

2022-10-11 10:10 UTC, TriptiVermaXP approved these changes

2022-10-13 18:27 UTC, merged