feat(inventory): feature/icky 641 implemented nearby store with inventory for pdp
KiboSoftware/nextjs-storefront pull request #114
Opened 2022-08-25 09:27 UTC by TriptiVermaXP

2022-08-25 10:38 UTC, kibo-sushant commented on components/dialogs/Store/SearchStore/SearchStore.tsx
> +        )}
Storybook do not allow to type in Search
Without Inventory - should user able to open Store Info accordian?
                    Get Directions is not disabled

2022-08-25 10:38 UTC, kibo-sushant commented on components/dialogs/Store/StoreLocatorDialog/StoreLocatorDialog.tsx
> +  quantity?: number
No mandatory Prop?

2022-08-25 10:38 UTC, kibo-sushant commented on __mocks__/stories/ProductLocationInventoryMock.ts
> +}
As per the conventions used for other mock files, file name should be LocationInventoryCollectionMock

2022-08-25 17:36 UTC, kibo-kevinwatts requested changes
nice work!

2022-08-25 17:36 UTC, kibo-kevinwatts commented on components/dialogs/Store/StoreLocatorDialog/StoreLocatorDialog.tsx
> +  const locationInventory = useProductLocationInventory(
destructure like we do elsewhere,
`const { data: locationInventory } = useProductLocationInventory(`

2022-08-25 17:36 UTC, kibo-kevinwatts commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +  const productInventory = useProductLocationInventory(
destructure like we do with other react query hooks

2022-08-25 17:36 UTC, kibo-kevinwatts commented on hooks/queries/useProductLocationInventory/useProductLocationInventory.ts
> +  } = useQuery(inventoryKeys.all, () => loadProductLocationInventory(productCode, locationCodes), {
I think we need to include productCode / locationCodes in the key.

2022-08-29 11:25 UTC, TriptiVermaXP commented on components/common/KiboRadio/KiboRadio.tsx
> +              }
Done

2022-08-29 11:26 UTC, TriptiVermaXP commented on __mocks__/stories/ProductLocationInventoryMock.ts
> +}
done

2022-08-29 11:26 UTC, TriptiVermaXP commented on hooks/queries/useProductLocationInventory/useProductLocationInventory.ts
> +  } = useQuery(inventoryKeys.all, () => loadProductLocationInventory(productCode, locationCodes), {
Done

2022-08-29 11:26 UTC, TriptiVermaXP commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +  const productInventory = useProductLocationInventory(
Done

2022-08-29 11:26 UTC, TriptiVermaXP commented on components/dialogs/Store/StoreLocatorDialog/StoreLocatorDialog.tsx
> +  const locationInventory = useProductLocationInventory(
Done

2022-08-29 11:26 UTC, TriptiVermaXP commented on components/dialogs/Store/StoreLocatorDialog/StoreLocatorDialog.tsx
> +  quantity?: number
we need to show product and qty details on store locator dialog for PDP only, so created the optional parameter.

2022-08-29 11:26 UTC, TriptiVermaXP commented on components/common/ProductItem/ProductItem.tsx
> +                {options && <ProductOptionList options={options} />}
Done

2022-08-29 12:36 UTC, TriptiVermaXP commented on components/dialogs/Store/SearchStore/SearchStore.tsx
> +        )}
SearchTerm is passing value from Parent comp (storeLocatorDialog) and maintained the state on parent itself, that's why search input box is not functioning into the storybook here. Should we have another state in this comp (middle level comp) for storybook? 
It's working in Parent component's (storeLocatorDialog) storybook. 

Purposely not disabled the Store info accordion for no inventory location. Please suggest if we should disable it.
Now grayed out the Get Directions text color.

2022-08-30 06:52 UTC, kibo-chandradeeptalaha approved these changes

2022-08-30 10:48 UTC, kibo-sushant approved these changes

2022-08-30 16:12 UTC, kibo-kevinwatts approved these changes

2022-08-30 16:21 UTC, merged