feat(size selector): Product variant-size selector component
KiboSoftware/nextjs-storefront pull request #13
Opened 2022-03-04 19:05 UTC by kibo-chandradeeptalaha

2022-03-07 23:46 UTC, kibo-kevinwatts requested changes
Looks good

Add storybook / jest unit tests, check Pull Request 15 file components/common/HeaderAction/HeaderAction.spec.js for example

2022-03-14 03:07 UTC, kibo-sushant commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.tsx
> +export default ProductVariantSizeSelector
**1. Using right Types**
    interface SizeSelectorProps {
	  attributeFQN: string
	  values: ProductOptionValue[]
	  selectOption: (attributeFQN?: string | null, value?: string) => void
	}
	Instead of "attributeFQN?: string | null", it should be "attributeFQN?: string"

**2. Interface naming**
    As best practice while naming interface always name it like [ComponentName]Props
   ex. ProductVariantSizeSelectorProps
	
**3.  Reusing GraphQL Types**
interface SizeOptionsProps { …  }
Instead of defining "SizeOptionsProps" use existing "ProductOptionValue" from graphQL

**4. Avoid bloating Component**
Define SizeOptions outside ProductVariantSizeSelector component 
Ex. SuccessSlider at https://mui.com/customization/how-to-customize/
    
**5. Using event handlers at right place**
Instead of calling  onClick: () => selectOption(attributeFQN, value)  on 
   line no. 50, call it like <SizeOptions onClick={}/>
      
**6. Avoid inline functions**
   As best practice instead of using inline functions create separate function and call it
   ex. const handleOptionSelection = () =>{ selectOption(attributeFQN, value)  }
   <SizeOptions onClick={handleOptionSelection}/>
   (This way we can easily extend using useMemo or useCallback if required.)

2022-03-14 03:07 UTC, kibo-sushant commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.spec.js
> +})
**1. Naming Describe block**
  In describe block shold use Type name (like components/getters/composables) as identifier
  ex. describe([components] - )   

**2. Naming test**
   Use "Should When" over "Should If"
   
**2. Naming Mocks**
 As best practice Mock suffix whenever you mocks
 ex. const selectOptionMock = jest.fn()

3. Using case insensitive with RegX 
 As best practice use "/size-options/i" over "/size-options/"

**4. Testing only Essential things**
  I think we do not require the below test cases
  should have text.primary background color for the selected options
  should have opacity 0.3 for the disabled options
  (With the help of Kevin we can decide what is essential and what is not)
  
**5. Avoid test case duplication**
  Both test cases are exactly identical, I think we can delete one of them
  Also second test name is bit confusing.
   
  should call selectOption method if value is selected
  should call selectOption method if value if neither selected nor disabled

2022-03-14 07:29 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.spec.js
> +})
Done

2022-03-14 07:29 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.tsx
> +export default ProductVariantSizeSelector
Done

2022-03-21 21:26 UTC, kibo-kevinwatts requested changes

2022-03-21 21:26 UTC, kibo-kevinwatts commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.spec.js
> +  it('should have text.primary background color for the selected options', () => {
lets remove this test

2022-03-21 21:26 UTC, kibo-kevinwatts commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.spec.js
> +    expect(disabledOption).toHaveStyle(`opacity: 0.3`)
try testing if the option is disabled based on the functionality/behavior, ie, should a click handler not be called when it is clicked. 
Avoid testing based on a css property. If we change the opacity, this test starts failing

2022-03-22 07:14 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.spec.js
> +    expect(disabledOption).toHaveStyle(`opacity: 0.3`)
Done

2022-03-22 07:17 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.spec.js
> +  it('should have text.primary background color for the selected options', () => {
Done

2022-03-22 15:31 UTC, kibo-kevinwatts approved these changes

2022-03-22 15:31 UTC, merged