feat: empty wishlist view
KiboSoftware/nextjs-storefront pull request #130
Opened 2022-09-06 13:14 UTC by sss-bct

2022-09-08 03:14 UTC, kibo-sushant commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +      </>
Testcases are missing

2022-09-08 07:54 UTC, TriptiVermaXP requested changes
Please take a look.

2022-09-09 14:41 UTC, sss-bct commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +      </>
Done.

2022-09-09 14:43 UTC, sss-bct commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +                <MuiLink href="/" underline="none">
Yes , otherwise we  can not test href attribute.

2022-09-09 14:43 UTC, sss-bct commented on components/product/ProductCard/ProductCard.tsx
> +              <MuiLink href={link} underline="none">
Same.

2022-09-12 06:06 UTC, TriptiVermaXP approved these changes

2022-09-13 05:59 UTC, sushantj2050dev approved these changes

2022-09-13 05:59 UTC, sushantj2050dev approved these changes

2022-09-13 21:19 UTC, kibo-kevinwatts approved these changes
everything but the next link looks good to me. 
Let's address the next/link issue across the codebase in another pr

2022-09-13 21:19 UTC, kibo-kevinwatts commented on components/page-templates/WishlistTemplate/WishlistTemplate.tsx
> +                <MuiLink href="/" underline="none">
Are we doing this in multiple places? `passHref` should set the href of the child.
If you're saying it's just for the tests, lets address the tests / mocked component instead of writing next links this way

2022-09-14 09:51 UTC, kibo-sushant approved these changes

2022-09-14 09:51 UTC, merged