feat: pull home page contentfull data
KiboSoftware/nextjs-storefront pull request #139
Opened 2022-09-14 08:19 UTC by kibo-sushant

2022-09-14 18:50 UTC, kibo-chandradeeptalaha commented on lib/operations/get-page/index.ts
> +  if (currentCMS === 'contentstack') return getContentStackPage(params)
Let's put these string values in constant or create enums

2022-09-14 18:50 UTC, kibo-chandradeeptalaha commented on lib/operations/get-page/index.ts
> +  const response = await contentful.fetchContent()
directly return instead of storing in variable first

2022-09-15 12:32 UTC, amolpawar-kibo commented on lib/operations/get-page/index.ts
> +  if (currentCMS === 'contentstack') return getContentStackPage(params)
Resolved.

2022-09-15 12:33 UTC, amolpawar-kibo commented on lib/operations/get-page/index.ts
> +  const response = await contentful.fetchContent()
Done.

2022-09-15 13:16 UTC, TriptiVermaXP approved these changes

2022-09-15 13:19 UTC, TriptiVermaXP approved these changes
Looks good, but do we need to write tests for these?

2022-09-16 04:35 UTC, kibo-chandradeeptalaha commented on lib/getters/contentfulGetters.ts
> +const formatCMSProduct = (cmsProducts: any) => {
change function name to something related to formatContentfulProduct or normalizeContentfulProduct.

2022-09-16 04:36 UTC, kibo-chandradeeptalaha commented on lib/cms/contentful/index.js
> +const URL = `https://graphql.contentful.com/content/v1/spaces/${spaceId}/environments/master`
Can we make this configurable ?

2022-09-16 04:37 UTC, kibo-chandradeeptalaha requested changes
Please take a look

2022-09-16 07:48 UTC, amolpawar-kibo commented on lib/getters/contentfulGetters.ts
> +const formatCMSProduct = (cmsProducts: any) => {
I have modify with formatContentfulProduct but in future we have to decide on CMS response.

2022-09-21 21:15 UTC, merged