fix: spacing and heights
KiboSoftware/nextjs-storefront pull request #140
Opened 2022-09-16 06:20 UTC by kibo-chandradeeptalaha

2022-09-21 21:38 UTC, kibo-kevinwatts requested changes
The spacing / design changes look good, but looks like you have unneeded changes to type imports  in test

2022-09-21 21:38 UTC, kibo-kevinwatts commented on __test__/e2e/helper/index.ts
> +import { UserEvent } from '@testing-library/user-event/dist/types/setup/setup'
was this an accidental commit? no exports from there

2022-09-21 21:38 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/MyAccountTemplate/MyAccountTemplate.spec.tsx
> +import { UserEvent } from '@testing-library/user-event/dist/types/setup/setup'
was this an accidental commit? no exports from there

2022-09-21 21:38 UTC, kibo-kevinwatts commented on components/layout/Login/LoginContent/LoginContent.spec.tsx
> +import type { UserEvent } from '@testing-library/user-event/dist/types/setup/setup'
was this an accidental commit? no exports from there

2022-09-23 04:01 UTC, kibo-chandradeeptalaha commented on components/layout/Login/LoginContent/LoginContent.spec.tsx
> +import type { UserEvent } from '@testing-library/user-event/dist/types/setup/setup'
Yes. we need to remove this type

2022-09-26 22:16 UTC, kibo-kevinwatts approved these changes

2022-09-28 06:17 UTC, TriptiVermaXP approved these changes

2022-09-28 06:17 UTC, TriptiVermaXP commented on __test__/e2e/helper/index.ts
> +export const addNewCard = async (user: any) => {
Why we used any here?

2022-09-28 22:50 UTC, merged