chore: initial cleanup
KiboSoftware/nextjs-storefront pull request #142
Opened 2022-09-19 09:40 UTC by kibo-chandradeeptalaha

2022-09-28 09:12 UTC, TriptiVermaXP approved these changes
Overall looks good, please check few comments added.
We can directly get translation from common as only one file is there, no need of array wherever using const { t } = useTranslation(['common']).

2022-09-28 09:12 UTC, TriptiVermaXP commented on lib/getters/userGetters.ts
> +import { PaymentAndBilling, SavedCard } from '../types'
use type

2022-09-28 09:12 UTC, TriptiVermaXP commented on lib/getters/addressGetters.ts
> +import { LocationCustom, SavedBillingAddress } from '@/lib/types'
use type

2022-09-28 10:26 UTC, amolpawar-kibo commented on __test__/e2e/helper/index.ts
> +export const addNewCard = async (user: any) => {
Is there any specific reason we removed type UserEvent?

2022-09-28 11:20 UTC, amolpawar-kibo commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +import { orderGetters } from '@/lib/getters'
Can we merge in oneline

2022-09-28 11:35 UTC, kibo-chandradeeptalaha commented on components/common/AddressForm/AddressForm.tsx
>  import { Address, ContactForm } from '@/lib/types'
Done

2022-09-28 11:35 UTC, kibo-chandradeeptalaha commented on lib/getters/__tests__/productGetters.spec.tsx
> +import { ProductOption } from '@/lib/gql/types'
Done

2022-09-28 11:35 UTC, kibo-chandradeeptalaha commented on lib/getters/orderGetters.ts
> +  // getProductOptions,
Done

2022-09-28 11:35 UTC, kibo-chandradeeptalaha commented on components/page-templates/Checkout/Checkout.tsx
> +    shippingTotalLabel: t('standard-shopping'),
Done

2022-09-28 11:35 UTC, kibo-chandradeeptalaha commented on lib/getters/userGetters.ts
> +import { PaymentAndBilling, SavedCard } from '../types'
Done

2022-09-28 11:35 UTC, kibo-chandradeeptalaha commented on lib/getters/addressGetters.ts
> +import { LocationCustom, SavedBillingAddress } from '@/lib/types'
Done

2022-09-28 11:36 UTC, kibo-chandradeeptalaha commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +import { orderGetters } from '@/lib/getters'
Done

2022-09-29 07:26 UTC, kibo-sushant commented on lib/getters/orderGetters.ts
> +  getShippingMethodCode,
**In OrderGetters**

1) Instead of creating two separate types ShippingDetails and BillingDetails
we should create common type and use it (preferably).  Ex. Contact or ContactDetails
 or
We should create common interface/type and then extend it with the help of ShippingDetails and BillingDetails

2) As Below porperties are not getting used externally we should not expose it.
getPersonalDetails
getOrderStatus
getOrderPaymentBillingInfo
getId
getDiscountedTotal => Delete the code as not used internally or externally
getLineItemTotal  => Delete the code as not used internally or externally
getLineItemTaxTotal => Delete the code as not used internally or externally
getShippingDetails
getBillingDetails
getPaymentMethods
getOrderSummary

3) Naming convention consistency
getTaxTotal, getSubtotal, getDiscountedSubtotal, getLineItemTotal
some of the places Total is in camelCase where as some of the places it is in Pascal. 

4) Unnecessary Maybe In return (at some of the places)
some of the places we have used Maybe which is not required.
Ex. 
const getItemsByFulfillment = (order: Order, fulfillmentMethod: string): Maybe<CrOrderItem>[] => {
  return order?.items?.filter((lineItem) => lineItem?.fulfillmentMethod === fulfillmentMethod) || []
}

5) Comparison
Instead of comparing payment?.status === 'New', 
we should either convert it in lowercase or uppercase and then compare

6) Duplicate functionality
getPersonalDetails is subset of getShippingDetails expect email,
we can delete getPersonalDetails and use getShippingDetails by adding email

7) AddressGetter
 should have single responsibility
 should be generic
 should be used for both billing and shipping address
 should not contain specific information like getBillingDetails, getIsSameBillingShippingAddress

8) In OrderGetter, instead of implementing the below functions we should make use of the function defined in AddressGetters 
 getShippingFirstName
 getShippingMiddleNameOrInitial
 getShippingLastNameOrSurname
 getShippingPhoneHome
 getShippingPhoneMobile
 getShippingPhoneWork
 getShippingAddress

2022-09-29 10:29 UTC, kibo-sushant commented on lib/getters/productGetters.ts
>  }
As below properties are not getting used externally we should not expose it.

getProductTotalReviews		=> As not getting used internally and externally delete the code
getPriceRange
getDescription
getShortDescription
getProductGallery
getProperties
getSegregatedOptions
getSelectedFulfillmentOption
getProductId
validateAddToCart
getVariationProductCodeOrProductCode
getIsPackagedStandAlone

2022-09-29 10:29 UTC, kibo-sushant commented on lib/getters/productGetters.ts
>    // grouped
Delete commented code

2022-09-29 10:29 UTC, kibo-sushant commented on lib/getters/userGetters.ts
> +}
instead of any use specific types

2022-09-29 10:29 UTC, kibo-sushant commented on lib/getters/userGetters.ts
> +}
condition occurred twice
if (addresses?.length) if (addresses?.length)

We should handle condition (addresses?.length) inside the getAddresses instead of the caller function.

2022-09-29 10:29 UTC, kibo-sushant commented on lib/getters/userGetters.ts
> +}
As below properties are not getting used externally we should not expose it

getSavedCards
getFirstName
getLastName
getFullName
getEmailAddress
getUserId
getPersonalDetails => As this prop is not getting used internally and externally we should delete the code

2022-09-29 14:42 UTC, kibo-chandradeeptalaha commented on lib/getters/cardGetters.ts
>    getPaymentType,
in getCardDetails. further being used in PaymentStep

2022-09-30 08:10 UTC, kibo-chandradeeptalaha commented on lib/getters/userGetters.ts
> +}
Done

2022-09-30 08:20 UTC, kibo-chandradeeptalaha commented on lib/getters/productGetters.ts
> +
Done

2022-09-30 08:20 UTC, kibo-chandradeeptalaha commented on lib/getters/cardGetters.ts
> +import { Card, PaymentCard } from '../gql/types'
Done

2022-09-30 08:20 UTC, kibo-chandradeeptalaha commented on lib/getters/cardGetters.ts
>    getPaymentType,
in getCardDetails. further being used in PaymentStep

2022-09-30 08:50 UTC, kibo-chandradeeptalaha commented on lib/getters/orderGetters.ts
> +  getShippingMethodCode,
Done

2022-09-30 08:54 UTC, kibo-chandradeeptalaha commented on lib/getters/productGetters.ts
>  }
Done

2022-09-30 08:55 UTC, kibo-chandradeeptalaha commented on lib/getters/productGetters.ts
>    // grouped
Done

2022-09-30 08:57 UTC, kibo-chandradeeptalaha commented on lib/getters/userGetters.ts
> +}
Done

2022-10-03 21:00 UTC, kibo-kevinwatts requested changes

2022-10-03 21:00 UTC, kibo-kevinwatts commented on .storybook/i18n.js
> -const localeAssets = ['common', 'cart', 'product', 'checkout', 'orderhistory']
Dont' we need this for stories to have correct strings?

2022-10-03 21:00 UTC, kibo-kevinwatts commented on __test__/e2e/helper/index.ts
> +import { UserEvent } from '@testing-library/user-event/dist/types/setup'
Didn't we just remove this type in a recent pull request?

2022-10-03 21:00 UTC, kibo-kevinwatts commented on public/locales/en/common.json
> +  "nearby-stores": "Nearby stores"
Why merge all the locales into one big file?

2022-10-03 21:00 UTC, kibo-kevinwatts commented on lib/getters/orderGetters.ts
> +interface ShippingDetails extends ContactDetails {
should all these types be defined in /lib/types?

2022-10-10 06:50 UTC, kibo-chandradeeptalaha commented on __test__/e2e/helper/index.ts
> +import { UserEvent } from '@testing-library/user-event/dist/types/setup'
That was some vscode issue. Fixed it now.

2022-10-11 22:16 UTC, kibo-kevinwatts approved these changes

2022-10-12 06:30 UTC, kibo-sushant approved these changes

2022-10-12 06:35 UTC, merged