feat(home-page): build cms driven homepage content using amplience
KiboSoftware/nextjs-storefront pull request #149
Opened 2022-09-27 11:08 UTC by kibo-geetanshuchhabra

2022-09-28 08:56 UTC, kibo-sushant commented on lib/cms/amplience/index.js
> +    return response
return result directly

2022-09-28 08:56 UTC, kibo-sushant commented on lib/cms/amplience/index.js
> +    const slotId = 'c79e66ce-6de5-44e3-b87e-6cdf5601c817'
we should not hardcode slotId

2022-09-28 08:56 UTC, kibo-sushant commented on lib/cms/amplience/index.js
> +      hubName: 'kibo',
We shold not hardcode hubName

2022-09-28 08:56 UTC, kibo-sushant commented on lib/getters/amplienceGetters.ts
> +}
Everywhere 
1) return directly (instead of using return keyword)
2) destructure param instead of repeating it

2022-09-28 13:53 UTC, kibo-geetanshuchhabra commented on lib/cms/amplience/index.js
> +    return response
Resolved

2022-09-28 13:53 UTC, kibo-geetanshuchhabra commented on lib/cms/amplience/index.js
> +    const slotId = 'c79e66ce-6de5-44e3-b87e-6cdf5601c817'
Resolved

2022-09-28 13:53 UTC, kibo-geetanshuchhabra commented on lib/cms/amplience/index.js
> +      hubName: 'kibo',
Resolved

2022-09-28 13:53 UTC, kibo-geetanshuchhabra commented on lib/getters/amplienceGetters.ts
> +}
Resolved

2022-09-28 22:54 UTC, kibo-kevinwatts requested changes

2022-09-28 22:54 UTC, kibo-kevinwatts commented on next.config.js
> +      homePageContentId: 'c79e66ce-6de5-44e3-b87e-6cdf5601c817',
Is there any other way to fetch the home page data besides an ID
For example, a url slug?

2022-09-28 22:54 UTC, kibo-kevinwatts commented on lib/cms/amplience/index.js
> +    const slotId = publicRuntimeConfig.amplience.homePageContentId
Can we fetch the content by some other method besides a fixed ID?

2022-09-29 06:47 UTC, kibo-geetanshuchhabra commented on lib/cms/amplience/index.js
> +    const slotId = publicRuntimeConfig.amplience.homePageContentId
Resolved

2022-09-29 06:47 UTC, kibo-geetanshuchhabra commented on next.config.js
> +      homePageContentId: 'c79e66ce-6de5-44e3-b87e-6cdf5601c817',
Resolved

2022-09-29 11:43 UTC, kibo-sushant approved these changes

2022-09-29 21:08 UTC, kibo-kevinwatts approved these changes

2022-09-30 01:27 UTC, merged