feat(builderio): hamepage
KiboSoftware/nextjs-storefront pull request #153
Opened 2022-10-06 13:34 UTC by kibo-sushant

2022-10-11 14:16 UTC, TriptiVermaXP requested changes
Please check one review comment.

2022-10-11 14:16 UTC, TriptiVermaXP commented on pages/product/[productCode].tsx
> +        {page && <BuilderComponent model="page" content={page} />}
For Amplience setup, we are getting _product recommendation and customer also bought_ data from amplience and builder-io both. We need to handle either of one should show. 
Please verify for other cms as well.

2022-10-13 12:06 UTC, TriptiVermaXP approved these changes

2022-10-18 21:21 UTC, kibo-kevinwatts approved these changes

2022-11-02 16:01 UTC, closed without merging