feat: sticky checkout stepper and order summary implementation
KiboSoftware/nextjs-storefront pull request #160
Opened 2022-10-19 08:10 UTC by kibo-sahilarora

2022-10-21 08:53 UTC, kibo-sushant approved these changes

2022-10-27 19:45 UTC, kibo-kevinwatts requested changes
one small code style change

2022-10-27 19:45 UTC, kibo-kevinwatts commented on components/checkout/KiboStepper/KiboStepper.tsx
> +const StepperStyles = {
StepperStyles should be camel case or just "styles"

2022-10-28 06:23 UTC, kibo-sahilarora commented on components/checkout/KiboStepper/KiboStepper.tsx
> +const StepperStyles = {
Done.

2022-11-02 11:02 UTC, kibo-chandradeeptalaha approved these changes

2022-11-02 16:01 UTC, kibo-kevinwatts approved these changes

2022-11-04 07:00 UTC, merged