feature/icky 727
KiboSoftware/nextjs-storefront pull request #162
Opened 2022-10-20 12:11 UTC by kibo-chandradeeptalaha

2022-10-20 13:46 UTC, kibo-susantasamanta commented on components/layout/AppHeader/Common/KiboHeader.stories.tsx
> +    <KiboHeader {...args}></KiboHeader>
It can be a single tag component as no nested component present.

2022-10-20 15:23 UTC, kibo-susantasamanta commented on components/layout/AppHeader/Icons/StoreFinderIcon/StoreFinderIcon.spec.tsx
> +    user,
user and router can be removed as are not used anywhere.

2022-10-20 15:36 UTC, kibo-susantasamanta requested changes
Please take a look for change request.

2022-10-21 08:24 UTC, kibo-sushant commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +  const [isHeaderSmall, setIsHeaderSmall] = useState(false)
Use types explicitly with State ex. useState<boolean>(false)
 Group the logical code   Ex. group all the state declarations 
 Order inside Component
// declare your variables, state
// declare you custom hooks, functions, event handlers
// declare your useEffects, useCallback, etc
// declare any optional rendering functions
// return Jsx render

2022-10-21 08:24 UTC, kibo-sushant commented on components/layout/AppHeader/Icons/AccountIcon/AccountIcon.tsx
> +export default AccountIcon
No Story?

2022-10-21 08:43 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/AccountIcon/AccountIcon.tsx
> +export default AccountIcon
As discussed with @kibo-kevinwatts , no need of story.

2022-10-21 08:43 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/CartIcon/CartIcon.tsx
> +export default CartIcon
As discussed with @kibo-kevinwatts , no need of story.

2022-10-21 08:43 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/HamburgerIcon/HamburgerIcon.tsx
> +export default HamburgerIcon
As discussed with @kibo-kevinwatts , no need of story.

2022-10-21 08:43 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/StoreFinderIcon/StoreFinderIcon.tsx
> +export default StoreFinderIcon
As discussed with @kibo-kevinwatts , no need of story.

2022-10-21 09:18 UTC, kibo-chandradeeptalaha commented on context/HeaderContext.tsx
> +}
Added

2022-10-21 09:18 UTC, kibo-chandradeeptalaha commented on components/layout/HamburgerMenu/HamburgerMenu.tsx
> +  handleAccountIconClick: () => void
Done

2022-10-21 09:18 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/StoreFinderIcon/StoreFinderIcon.tsx
> +      }
changed

2022-10-21 09:18 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/StoreFinderIcon/StoreFinderIcon.tsx
> +  console.log('location', location)
Done

2022-10-21 09:18 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/StoreFinderIcon/StoreFinderIcon.tsx
> +  console.log('location', location)
Done

2022-10-21 09:18 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/StoreFinderIcon/StoreFinderIcon.tsx
> +}
Done

2022-10-21 09:18 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/CartIcon/CartIcon.tsx
> +  }
Done

2022-10-21 09:18 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Icons/CartIcon/CartIcon.tsx
> +}
Done

2022-10-21 09:19 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +  const [isHeaderSmall, setIsHeaderSmall] = useState(false)
Done

2022-10-21 09:19 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +}
Done

2022-10-21 09:19 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +        }}
Done

2022-10-21 09:19 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +            }}
Done

2022-10-21 09:19 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +  handleAccountIconClick: () => void
Done

2022-10-21 09:19 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +    }
Done

2022-10-21 09:19 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +  sticky?: boolean
Done

2022-10-21 14:26 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +export default KiboHeader
I tried but no easy solution I found. I'll keep looking !

2022-10-21 14:46 UTC, kibo-sushant approved these changes

2022-10-21 14:46 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +          {isHeaderSmall && !headerState.isSearchBarVisible && (
Done

2022-10-27 19:49 UTC, kibo-kevinwatts commented on components/layout/AppHeader/Checkout/CheckoutHeader.tsx
> +const CheckoutHeaderStyles = {
this should be camel cased

2022-10-27 20:01 UTC, kibo-kevinwatts commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +const KiboHeaderStyles = {
camel case

2022-10-27 20:01 UTC, kibo-kevinwatts commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +const TopHeaderStyles = {
camel case

2022-10-27 20:01 UTC, kibo-kevinwatts commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +const HeaderActionAreaStyles = {
camel case

2022-10-27 20:02 UTC, kibo-kevinwatts requested changes
Handful of code style changes to camel case.
The code looks good, but the animation for the scroll does look rough toward the top.
Is there anything we can do to improve it?

2022-11-02 06:20 UTC, kibo-susantasamanta approved these changes

2022-11-02 15:43 UTC, kibo-kevinwatts approved these changes

2022-11-04 06:45 UTC, merged