feat: initiate order return
KiboSoftware/nextjs-storefront pull request #166
Opened 2022-11-02 12:11 UTC by kibo-nehabhanushali

2022-11-09 08:38 UTC, TriptiVermaXP approved these changes

2022-11-09 10:55 UTC, kibo-sushant commented on components/common/ProductItem/ProductItem.spec.tsx
> +})
No need of describe(' 
Testcases name is not meaningful

Missing Testcases
should make the checkbox visible when isCheckboxVisible prop is true
should make the checkbox disable when isCheckboxDisabled prop is true
should call the callback function  when the user selects checkbox

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  const [isReturnRequestSuccess, setIsReturnRequestSuccess] = useState<boolean>(false)
use meaningful names ex. isReturnRequestSuccessful

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  const shipItems = orderGetters.getShipItems(order)
instead of calling orderGetters multiple times wouldn't it be nice if will call it once and get all the required values?

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  }
Make the code readable
Take the if condition outside and assign it to a variable and use that variable inside if
Before passing value to setSelectedReturnItems(), assign it to a variable and use it
Do we need to give Maybe<CrOrderItem> explicitly, is TypeScript not infering?

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +
if we are not using name then what is need of passing this parameter?

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                  isCheckboxVisible={true}
If we are always passing isCheckboxVisible={true} then what is the need of this prop?

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                  onItemSelection={(orderItemId: string) => handleReturnItems(orderItemId)}
Why are we passing function here, can't we directly pass handleReturnItems?

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                  onItemSelection={(orderItemId: string) => handleReturnItems(orderItemId)}
Why are we passing function here, can't we directly pass handleReturnItems?

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                  isCheckboxVisible={true}
If we are always passing isCheckboxVisible={true} then what is the need of this prop?

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/OrderReturnItems/OrderReturnItems.spec.tsx
> +})
Where are other unit test cases?

2022-11-09 10:55 UTC, kibo-sushant commented on components/order/ViewOrderDetails/ViewOrderDetails.tsx
> +  onItemsReturn?: () => void
Testcases missing

2022-11-09 10:55 UTC, kibo-sushant commented on components/page-templates/OrderHistoryTemplate/OrderHistoryTemplate.tsx
> +  const [isReturnItems, setIsReturnItems] = useState<boolean>(false)
Keep all the useState colocated

2022-11-09 10:55 UTC, kibo-sushant commented on components/dialogs/OrderReturnItemsDialog/OrderReturnItemsDialog.tsx
> +          }}
define the SX at top and use it here

2022-11-09 10:55 UTC, kibo-sushant commented on components/dialogs/OrderReturnItemsDialog/OrderReturnItemsDialog.spec.tsx
> +describe('[components] (OrderReturnItemsDialog)', () => {
remove the () from (OrderReturnItemsDialog)

2022-11-09 10:55 UTC, kibo-sushant commented on components/common/ProductItem/ProductItem.tsx
> +        {isCheckboxVisible && (
if parent is passing always true then no need of showing it conditionally

2022-11-09 10:55 UTC, kibo-sushant commented on components/page-templates/OrderHistoryTemplate/OrderHistoryTemplate.tsx
> +      )}
Missing testcases

2022-11-09 11:45 UTC, kibo-nehabhanushali commented on components/common/ProductItem/ProductItem.spec.tsx
> +})
Resolved for callback function , other two are covered in current test case itself

2022-11-09 11:48 UTC, kibo-nehabhanushali commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  const [isReturnRequestSuccess, setIsReturnRequestSuccess] = useState<boolean>(false)
Resolved updated name

2022-11-09 11:54 UTC, kibo-nehabhanushali commented on components/page-templates/OrderHistoryTemplate/OrderHistoryTemplate.tsx
> +  const [isReturnItems, setIsReturnItems] = useState<boolean>(false)
Resolved

2022-11-09 12:14 UTC, kibo-nehabhanushali commented on components/dialogs/OrderReturnItemsDialog/OrderReturnItemsDialog.tsx
> +          }}
Resolved

2022-11-09 12:15 UTC, kibo-nehabhanushali commented on components/dialogs/OrderReturnItemsDialog/OrderReturnItemsDialog.spec.tsx
> +describe('[components] (OrderReturnItemsDialog)', () => {
Resolved

2022-11-09 13:00 UTC, kibo-nehabhanushali commented on hooks/mutations/useOrderReturnMutations/useCreateOrderReturnItemsMutation/useCreateOrderReturnItemsMutation.ts
> +}
Resolved

2022-11-09 13:05 UTC, kibo-nehabhanushali commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  const shipItems = orderGetters.getShipItems(order)
Right now, we dont have getter that will give all required details in one getter call, should we handle it in this PR or handle it later?

2022-11-09 13:14 UTC, kibo-nehabhanushali commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  }
Resolved, yes need Maybe explicilty , typescript is not infering

2022-11-10 01:12 UTC, kibo-kevinwatts requested changes

2022-11-10 01:12 UTC, kibo-kevinwatts commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  }
this is still hard on the eyes. either pass the "checked" status up from the checkbox event handler or re-arrange some more to avoid the lengthy line breaks

2022-11-10 01:12 UTC, kibo-kevinwatts commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  const [isReturnRequestSuccess, setIsReturnRequestSuccess] = useState<boolean>(false)
This state should be based on the status on the Order, right?

2022-11-10 05:31 UTC, kibo-nehabhanushali commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  }
Resolved

2022-11-10 05:41 UTC, kibo-nehabhanushali commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  const [isReturnRequestSuccess, setIsReturnRequestSuccess] = useState<boolean>(false)
yes, we used this in on order return success

2022-11-10 08:17 UTC, kibo-chandradeeptalaha commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                    sx={{ mr: '1.563rem', mb: '1.563rem', backgroundColor: '#fff' }}
use common.white instead of hex

2022-11-10 10:14 UTC, kibo-amolpawar commented on components/common/ProductItem/ProductItem.tsx
> +  onItemSelection?: (orderItemId: string) => void
Resolved.

2022-11-10 10:17 UTC, kibo-amolpawar commented on components/common/ProductItem/ProductItem.tsx
> +          <Checkbox
Resolved. Removed from this component & handled in ReturnitemList component

2022-11-10 10:25 UTC, kibo-nehabhanushali commented on components/page-templates/OrderHistoryTemplate/OrderHistoryTemplate.tsx
> +      )}
Done , added it

2022-11-10 10:27 UTC, kibo-nehabhanushali commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                    sx={{ mr: '1.563rem', mb: '1.563rem', backgroundColor: '#fff' }}
done resolved

2022-11-10 14:13 UTC, kibo-amolpawar commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +
Resolve.

2022-11-10 14:15 UTC, kibo-amolpawar commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                  isCheckboxVisible={true}
Done.  Created new component - ReturnItems

2022-11-10 14:16 UTC, kibo-amolpawar commented on components/common/ProductItem/ProductItem.tsx
> +        {isCheckboxVisible && (
Done. Created New component - ReturnItems

2022-11-10 14:18 UTC, kibo-amolpawar commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                  isCheckboxVisible={true}
Done. Created New component - ReturnItems

2022-11-16 04:32 UTC, kibo-amolpawar commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                  onItemSelection={(orderItemId: string) => handleReturnItems(orderItemId)}
Resolve.

2022-11-16 04:36 UTC, kibo-nehabhanushali commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +                  onItemSelection={(orderItemId: string) => handleReturnItems(orderItemId)}
Resolved

2022-11-16 04:37 UTC, kibo-nehabhanushali commented on components/order/OrderReturnItems/OrderReturnItems.spec.tsx
> +})
Resolved

2022-11-16 04:38 UTC, kibo-nehabhanushali commented on components/order/ViewOrderDetails/ViewOrderDetails.tsx
> +  onItemsReturn?: () => void
Resolved

2022-11-21 10:19 UTC, kibo-amolpawar commented on components/order/ViewOrderDetails/ViewOrderDetails.tsx
> +  onItemsReturn?: () => void
ViewOrderDetails component called in <OrderStatusTemplate>  & there is no required pass onItemsReturn

2022-11-22 07:56 UTC, kibo-amolpawar commented on components/page-templates/OrderHistoryTemplate/OrderHistoryTemplate.tsx
> +          onItemsReturn={() => setIsReturnItems(true)}
Resolved.

2022-11-22 07:57 UTC, kibo-amolpawar commented on components/common/ReturnItemList/ReturnItemList.tsx
> +  onClickChangeStore?: () => void
Removed. As it is not in use

2022-11-22 07:57 UTC, kibo-amolpawar commented on components/common/ReturnItemList/ReturnItemList.tsx
> +      {items?.map((item: Maybe<CrOrderItem>) => {
Resolved.

2022-11-22 07:57 UTC, kibo-amolpawar commented on components/page-templates/OrderHistoryTemplate/OrderHistoryTemplate.tsx
> +  const [isReturnItems, setIsReturnItems] = useState<boolean>(false)
Resolved.

2022-11-22 07:58 UTC, kibo-amolpawar commented on components/order/OrderReturnItems/OrderReturnItems.tsx
> +  onGoBackToOrderDetails?: () => void
Resolved.

2022-11-23 21:39 UTC, kibo-kevinwatts commented on next.config.js
> +  swcMinify: false,
remove this

2022-11-24 04:16 UTC, kibo-amolpawar commented on next.config.js
> +  swcMinify: false,
Resolved.

2022-11-28 14:34 UTC, merged