feat: implement multi ship checkout
KiboSoftware/nextjs-storefront pull request #171
Opened 2022-11-09 16:49 UTC by kibo-susantasamanta

2022-11-10 08:26 UTC, kibo-chandradeeptalaha commented on components/checkout/ShippingStep/ShippingStep.tsx
> +  const [shippingOption, setShippingOption] = useState<string>('ShipToHome')
'ShipToHome' should be somewhere configurable. Either constants or enum ?

2022-11-10 08:28 UTC, kibo-chandradeeptalaha commented on components/checkout/ShippingStep/ShippingStep.tsx
> +    console.log('onChangeShippingOption', option)
remove console.log

2022-11-10 08:33 UTC, kibo-chandradeeptalaha commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              {':'}
handle it in localization

2022-11-10 08:34 UTC, kibo-chandradeeptalaha commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +                {userShippingAddresses[index]?.address?.address1},{' '}
use getters

2022-11-10 08:34 UTC, kibo-chandradeeptalaha commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              sx={{ fontWeight: 'bold', marginTop: '0 !important' }}
don't use important

2022-11-10 10:22 UTC, kibo-susantasamanta commented on components/checkout/ShippingStep/ShippingStep.tsx
> +  const [shippingOption, setShippingOption] = useState<string>('ShipToHome')
Done.

2022-11-10 10:22 UTC, kibo-susantasamanta commented on components/checkout/ShippingStep/ShippingStep.tsx
> +    console.log('onChangeShippingOption', option)
Done.

2022-11-10 10:22 UTC, kibo-susantasamanta commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              {':'}
Done.

2022-11-10 14:17 UTC, kibo-sahilarora commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +                {userShippingAddresses[index]?.address?.address1},{' '}
Done

2022-11-10 14:17 UTC, kibo-sahilarora commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              sx={{ fontWeight: 'bold', marginTop: '0 !important' }}
Done

2022-11-30 07:39 UTC, kibo-susantasamanta commented
Please don't consider the ShippingStep component for review as we modified it with new flow of multiShip in another ticket(icky-781).

2022-11-30 10:07 UTC, TriptiVermaXP requested changes
Please check the review comments.

2022-11-30 10:07 UTC, TriptiVermaXP commented on hooks/queries/useCheckoutDestinationQueries/useCheckoutDestinationQueries.tsx
> +    getCheckoutDestination(params)
do we need to use "enabled" here, if checkoutId and destinationId are not null then only call the api?

2022-11-30 10:07 UTC, TriptiVermaXP commented on hooks/queries/useCheckoutDestinationsQueries/useCheckoutDestinationsQueries.tsx
> +  } = useQuery(checkoutDestinationKeys.all, () => getCheckoutDestinations(params))
do we need to use "enabled" here, if checkoutId is not null/empty then only call the api?

2022-12-05 10:42 UTC, kibo-sushant commented on components/checkout/OrderReview/OrderReview.tsx
> +import { userAddressResponse } from '@/__mocks__/stories/userAddressMock'
remove the mock data

2022-12-05 10:42 UTC, kibo-sushant commented on components/checkout/OrderReview/OrderReview.tsx
> +                    )
missing unit testcases

2022-12-05 10:42 UTC, kibo-sushant commented on components/checkout/ShippingStep/ShippingStep.tsx
> +        </Stack>
missing Unit testcases

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.tsx
> +  ]
why are we hardcoding this? if it is getting replaced by api data then add suitable comment

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.tsx
> +  const [selectedAddresses, setSelectedAddresses] = useState<any>({})
Avoid using any type

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.spec.tsx
> +})
missing other unit testcases

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +import { userAddressResponse } from '@/__mocks__/stories/userAddressMock'
remove mock data

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              </Typography>
yes it looks odd, we should remove getters from JSX template. Also clean the code (remove {' '})

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.spec.tsx
> +    const productItems = screen.getAllByTestId('product-item-component-multi-ship')
Instead of testing whether the block with TestId is rendered or not, please test actual provided items are rendered or not.

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.spec.tsx
> +    const productItems = screen.getAllByTestId('product-item-component-multi-ship')
Instead of testing whether the block with TestId is rendered or not, please test actual provided items are rendered or not.

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +  ]
Why are we hardcoding data?

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +  const [selectShippingOptions, setSelectShippingOptions] = useState<any>({})
avoid using any type

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +  onClickEdit: () => void
onClickEdit is not meaningful, we can rename it to onAddressEdit or something meaningful

2022-12-05 10:42 UTC, kibo-sushant commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.spec.tsx
> +})
missing test cases. ex. not testing after clicking on edit button  onClickEdit is getting called or not

2022-12-08 08:32 UTC, kibo-sahilarora commented on components/checkout/OrderReview/OrderReview.tsx
> +import { userAddressResponse } from '@/__mocks__/stories/userAddressMock'
After merging of multiShip steps, it will be taken care of with API.

2022-12-08 08:48 UTC, kibo-sahilarora commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +import { userAddressResponse } from '@/__mocks__/stories/userAddressMock'
After merging of shipping and payment steps for multiShip, it will be taken care of with API.

2022-12-08 13:32 UTC, kibo-sahilarora commented on components/checkout/ReviewStep/ReviewStep.tsx
> +  const isMultiShipEnabled = publicRuntimeConfig.isMultiShipEnabled
Done.

2022-12-08 13:32 UTC, kibo-sahilarora commented on components/checkout/ReviewStep/ReviewStep.tsx
> +      )}
Done.

2022-12-08 13:33 UTC, kibo-sahilarora commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.tsx
> +  SxProps,
Done

2022-12-08 13:35 UTC, kibo-sahilarora commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              sx={{ fontWeight: 'bold' }}
Done

2022-12-08 13:37 UTC, kibo-sahilarora commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              {t('est-arrival')} Mon 20, Dec
Removed hardcoded value for now. Will be taken care of when payment and shipping steps for multiShip are done. Have left the comment.

2022-12-08 13:41 UTC, kibo-sahilarora commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              </Typography>
Have handled these through Typography as of now.  Removed {' '}.
A separate ticket is already created for multiShip review page; will be handled with actual data when payment and shipping steps for multiShip are done.

2022-12-08 13:42 UTC, kibo-sahilarora commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +  Stack,
Done

2022-12-08 13:46 UTC, kibo-sahilarora commented on components/checkout/OrderReview/OrderReview.tsx
> +                    )
Done

2022-12-08 13:47 UTC, kibo-sahilarora commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.spec.tsx
> +    const productItems = screen.getAllByTestId('product-item-component-multi-ship')
Duplicated comment.

2022-12-08 14:08 UTC, kibo-sahilarora commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.tsx
> +                  const formatedAddress = `${contact?.address?.address1}, ${contact?.address?.address2}, ${contact?.address?.cityOrTown}, ${contact?.address?.stateOrProvince}, ${contact?.address?.pos
Done

2022-12-08 14:09 UTC, kibo-sahilarora commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +                onChange={(_name, value) => hanndleSelectShippingOption(index, value)}
Done.

2022-12-09 06:08 UTC, kibo-sahilarora commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +                  4321 Another Address, Austin, TX 78741
This thing is already handled in ICKY-781.

2022-12-09 07:29 UTC, kibo-sahilarora commented on hooks/queries/useCheckoutDestinationQueries/useCheckoutDestinationQueries.tsx
> +    getCheckoutDestination(params)
Done.

2022-12-09 07:29 UTC, kibo-sahilarora commented on hooks/queries/useCheckoutDestinationsQueries/useCheckoutDestinationsQueries.tsx
> +  } = useQuery(checkoutDestinationKeys.all, () => getCheckoutDestinations(params))
Done.

2022-12-09 07:30 UTC, kibo-sahilarora commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +  ]
Removed (Not being used).

2022-12-09 10:30 UTC, kibo-sahilarora commented on components/checkout/ShippingStep/ShippingStep.tsx
> +        </Stack>
Shipping Step step is not be considered for review in this PR. Comment for the same is added above by Susanta.

2022-12-09 10:32 UTC, kibo-sahilarora commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.spec.tsx
> +})
Test cases for this file is handled in ticket ICKY-781.

2022-12-09 12:51 UTC, kibo-sahilarora commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.tsx
> +  const [selectedAddresses, setSelectedAddresses] = useState<any>({})
Done.

2022-12-09 12:52 UTC, kibo-sahilarora commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +  onClickEdit: () => void
Done.

2022-12-09 12:52 UTC, kibo-sahilarora commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.spec.tsx
> +})
Done.

2022-12-09 13:33 UTC, TriptiVermaXP approved these changes

2022-12-19 14:26 UTC, kibo-kevinwatts approved these changes

2022-12-22 07:23 UTC, merged