feat: implement create checkout hook for multi ship
KiboSoftware/nextjs-storefront pull request #175
Opened 2022-11-17 09:11 UTC by kibo-sahilarora

2022-11-23 06:24 UTC, kibo-sushant commented on __mocks__/stories/multiShipCheckoutMock.ts
> +const multiShipCheckoutResponse: Checkout = {
rename the file name to checkoutMock (We have used similar conventions for other file names)

2022-11-23 07:14 UTC, TriptiVermaXP approved these changes

2022-11-23 11:08 UTC, kibo-sushant approved these changes

2022-11-23 21:22 UTC, kibo-kevinwatts requested changes

2022-11-23 21:22 UTC, kibo-kevinwatts commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +      visitId
remove 
```      ipAddress
      sourceDevice
      visitId
      webSessionId
      customerInteractionType```

2022-11-23 21:22 UTC, kibo-kevinwatts commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +      shopperNotes {
remove shopperNotes

2022-11-23 21:22 UTC, kibo-kevinwatts commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +      isTaxExempt
remove ```   customerTaxId
      isTaxExempt```

2022-11-23 21:22 UTC, kibo-kevinwatts commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +        id
Grouping properties should be a fragment

2022-11-23 21:22 UTC, kibo-kevinwatts commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +import {
we should move this to a different folder, "multiship-checkout" or something to keep them separate from existing checkout mutations

2022-11-24 07:33 UTC, kibo-sahilarora commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +      visitId
Done

2022-11-24 07:33 UTC, kibo-sahilarora commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +      shopperNotes {
Done

2022-11-24 07:33 UTC, kibo-sahilarora commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +      isTaxExempt
Done

2022-11-24 07:33 UTC, kibo-sahilarora commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +        id
Done

2022-11-24 07:33 UTC, kibo-sahilarora commented on lib/gql/mutations/checkout/create-multi-ship-checkout-mutation.ts
> +import {
Done

2022-11-28 20:02 UTC, kibo-kevinwatts approved these changes

2022-11-28 20:18 UTC, kibo-kevinwatts approved these changes

2022-11-29 06:03 UTC, merged