feat: hook useCreateMultiShipOrderMutation
KiboSoftware/nextjs-storefront pull request #178
Opened 2022-11-18 10:55 UTC by kibo-amolpawar

2022-11-23 07:28 UTC, TriptiVermaXP approved these changes
Approving, please check few comments.

2022-11-23 07:28 UTC, TriptiVermaXP commented on lib/helpers/buildCreateCheckoutParams.ts
> +import { Checkout } from '../gql/types'
use type

2022-11-23 07:28 UTC, TriptiVermaXP commented on hooks/mutations/multiShip/useCreateCheckoutActionMutation/useCreateCheckoutActionMutation.tsx
> +export const useCreateMultiShipOrderMutation = useCreateCheckoutActionMutation
any specific reason behind reassigning useCreateCheckoutActionMutation to useCreateMultiShipOrderMutation ?
Can't we use useCreateCheckoutActionMutation for consistency with other files and also its already inside multiship folder?

2022-11-28 19:20 UTC, kibo-kevinwatts requested changes

2022-11-28 19:20 UTC, kibo-kevinwatts commented on lib/helpers/buildCreateCheckoutParams.ts
> +export const buildCreateCheckoutParams = (checkout: Checkout) => ({
I would suggest deleting this helper file and just creating arguments in the hook.

If you want to keep it though.
1. Change name so its related to "action". `buildCheckoutActionParams`
2. Function 'buildCheckoutActionParams' should take "actionName" as a parameter

2022-11-28 19:20 UTC, kibo-kevinwatts commented on hooks/mutations/multiShip/useCreateCheckoutActionMutation/useCreateCheckoutActionMutation.tsx
> +export interface OrderMultiShipInfo {
rename `OrderMultiShipInfo` to `MultiShipCreateActionParams` or something "action" related

2022-11-29 05:45 UTC, kibo-amolpawar commented on hooks/mutations/multiShip/useCreateCheckoutActionMutation/useCreateCheckoutActionMutation.tsx
> +export const useCreateMultiShipOrderMutation = useCreateCheckoutActionMutation
In standard checkout we have  the same "useCreateCheckoutActionMutation" so for preventing conflict & to keep the same structure

2022-11-29 06:18 UTC, kibo-amolpawar commented on hooks/mutations/multiShip/useCreateCheckoutActionMutation/useCreateCheckoutActionMutation.tsx
> +export interface OrderMultiShipInfo {
Resolved. Renamed

2022-11-29 06:19 UTC, kibo-amolpawar commented on lib/helpers/buildCreateCheckoutParams.ts
> +export const buildCreateCheckoutParams = (checkout: Checkout) => ({
Resolved. Deleted

2022-11-29 06:19 UTC, kibo-amolpawar commented on lib/helpers/buildCreateCheckoutParams.ts
> +import { Checkout } from '../gql/types'
Resolved. File deleted. not in use now.

2022-12-05 11:45 UTC, kibo-sushant approved these changes

2022-12-08 00:26 UTC, kibo-kevinwatts approved these changes

2022-12-08 00:26 UTC, merged