feat: ICKY490-fliter-by
KiboSoftware/nextjs-storefront pull request #18
Opened 2022-03-15 10:07 UTC by kibo-sushant

2022-03-15 23:03 UTC, kibo-kevinwatts requested changes

2022-03-16 08:49 UTC, kibo-sushant commented on components/common/Search/Search.tsx
> +  const placeholder = `Search ${facetName}`
yes, created prop

2022-03-16 08:50 UTC, kibo-sushant commented on components/common/Search/Search.tsx
> +    onSearch(event.target.value)
SearchBar is a stateless component, hence currently searchTerm is handled by a parent, but if needed we can convert it into a stateful component. Let me know your thought.

2022-03-16 08:51 UTC, kibo-sushant commented on components/common/Search/Search.tsx
> +    onSearch(event.target.value)
SearchBar is a stateless component, hence currently searchTerm is handled by a parent, but if needed we can convert it into a stateful component. Let me know your thought.

2022-03-16 08:51 UTC, kibo-sushant commented on components/common/Search/Search.tsx
> +const Search: FC<SearchProps> = (props) => {
done

2022-03-16 08:51 UTC, kibo-sushant commented on components/common/Search/Search.tsx
> +const Search: FC<SearchProps> = (props) => {
done

2022-03-16 09:02 UTC, kibo-sushant commented on components/filter-by/Facet/Facet.tsx
> +  const defaultNoOfItemsToShow = 6
done

2022-03-16 09:09 UTC, kibo-sushant commented on components/filter-by/Facet/Facet.tsx
> +import { Facet as FacetType, FacetValue, Maybe } from '@/lib/gql/types'
done

2022-03-16 09:09 UTC, kibo-sushant commented on components/filter-by/Facet/Facet.tsx
> +  const defaultNoOfItemsToShow = 6
done

2022-03-22 01:15 UTC, kibo-sushant commented on components/filter-by/FacetItem/FacetItem.tsx
> +      pathname: router.pathname,
created hook and used it

2022-03-22 01:15 UTC, kibo-sushant commented on components/filter-by/FacetItem/FacetItem.tsx
> +      pathname: router.pathname,
created hook and used it

2022-03-22 01:16 UTC, kibo-sushant commented on components/filter-by/Facet/Facet.tsx
> +import { Facet as FacetType, FacetValue, Maybe } from '@/lib/gql/types'
done

2022-03-23 22:02 UTC, kibo-kevinwatts requested changes
looks good!

2022-03-24 03:24 UTC, kibo-sushant commented on components/common/QuantitySelector/QuantitySelector.tsx
> +import React, { FC } from 'react'
resolved

2022-03-24 03:25 UTC, kibo-sushant commented on components/filter-by/FacetItem/FacetItem.tsx
> +    if (filters.includes(filterValue)) setChecked(true)
resolved
const [checked, setChecked] = useState<boolean>(isApplied)

2022-03-24 15:45 UTC, kibo-kevinwatts commented on components/filter-by/FacetItem/FacetItem.tsx
> +    if (filters.includes(filterValue)) setChecked(true)
do we still need useEffect check if pulling from "isApplied" for initial state?

2022-03-24 15:45 UTC, kibo-kevinwatts approved these changes

2022-03-24 15:50 UTC, merged