feat(multiship): multiShip hook-getCheckout
KiboSoftware/nextjs-storefront pull request #183
Opened 2022-11-23 10:00 UTC by kibo-geetanshuchhabra

2022-11-23 11:00 UTC, TriptiVermaXP approved these changes

2022-11-23 11:06 UTC, kibo-sushant commented on hooks/queries/multiShip/useCheckoutQueries/useCheckoutQueries.ts
> +  checkoutId?: string
can checkoutId nullable?

2022-11-23 11:06 UTC, kibo-sushant commented on hooks/queries/multiShip/useCheckoutQueries/useCheckoutQueries.ts
> +const getCheckout = async (checkoutId?: string | null) => {
In what senario checkoutId will be null?

2022-11-23 11:06 UTC, kibo-sushant approved these changes

2022-11-23 13:36 UTC, kibo-geetanshuchhabra commented on hooks/queries/multiShip/useCheckoutQueries/useCheckoutQueries.ts
> +  checkoutId?: string
Resolved

2022-11-23 13:36 UTC, kibo-geetanshuchhabra commented on hooks/queries/multiShip/useCheckoutQueries/useCheckoutQueries.ts
> +const getCheckout = async (checkoutId?: string | null) => {
Resolved

2022-11-28 20:13 UTC, kibo-kevinwatts requested changes

2022-11-28 20:13 UTC, kibo-kevinwatts commented on lib/gql/queries/checkout/get-multi-ship-checkout-query.ts
> +import {
I think we should name this folder something "multiship-checkout" to keep them separate.
Also, can you work with @kibo-sahilarora and make sure we re-use the same fragments / properties from this
https://github.com/KiboSoftware/nextjs-storefront/pull/175/files#diff-1a5bace280e3a7b4dee09ef29699a18383763fdcc105a3d5d800123ee7489453

2022-11-29 10:58 UTC, kibo-geetanshuchhabra commented on lib/gql/queries/checkout/get-multi-ship-checkout-query.ts
> +import {
Resolved

2022-12-05 20:45 UTC, merged