feat : implement multiship shipping
KiboSoftware/nextjs-storefront pull request #188
Opened 2022-12-09 15:34 UTC by kibo-susantasamanta

2022-12-16 08:27 UTC, kibo-sushant commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.stories.tsx
> +}
Storybook drop down is empty

2022-12-16 08:27 UTC, kibo-sushant commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.spec.tsx
> +})
missing Unit Test cases  (no checking whether onUpdateDestinationAddress and onSelectCreateOrSetDestinationAddress called or not)

2022-12-16 08:27 UTC, kibo-sushant commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +                }}
define sx at top and use it here

2022-12-16 08:27 UTC, kibo-sushant commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +                  ?.shippingRates?.map((shippingRate) => {
assign the result to const and use it here
ex const shippingRates = shippingMethods ?.find((shippingMethod) =>
                      shippingMethod.groupingId === destinationItemGroup?.groupingId )
                  ?.shippingRates

2022-12-16 08:27 UTC, kibo-sushant commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +                }}
define the sx at top and reuse it here

2022-12-16 08:27 UTC, kibo-sushant commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.stories.tsx
> +}
empty dropdown

2022-12-16 08:27 UTC, kibo-sushant commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.spec.tsx
> +})
missing Unit Test cases

2022-12-19 14:41 UTC, TriptiVermaXP requested changes
Please check the review comments.

2022-12-20 08:22 UTC, kibo-chandradeeptalaha requested changes
Please check

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/checkout/DetailsStep/DetailsStep.tsx
> +  const updatePersonalInfo = async (formData: PersonalDetails) =>
Do we need this function as it's internally calling another function?

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.spec.tsx
> +    setup()
Why is this test case? What are we trying to achieve with this ?

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +import AddressFormDialog from '@/components/dialogs/AddressFormDialog/AddressFormDialog'
use index file.

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +import type { MultiShipAddress } from '@/components/common/ProductItemWithAddressList/ProductItemWithAddressList'
add types to types folder and export from there not from component.

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +import { useModalContext } from '@/context/ModalContext'
use index file

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +    closeModal()
Shouldn't this closeModal be called after mutation success ?

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +    _shippingMethodName: string,
unused param. If needed, make this shippingMethodName as optional and remove the underscore from name

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +                  style={{ textTransform: 'none' }}
move this to sx

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/checkout/Shipping/OrderItems/ShippingMethod.tsx
> +                {`${item?.shippingMethodName} $${item?.price}`}
use localization for price

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.tsx
> +                  +
try this using ::before in css

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              {t('ship-to')}
use localization for :

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +                {' '}
remove this

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +                {userShippingAddresses[index]?.address?.address2},{' '}
use getters

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              {t('est-arrival')} Mon 20, Dec
hard coded value

2022-12-20 08:22 UTC, kibo-chandradeeptalaha commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              sx={{ fontWeight: 'bold', marginTop: '0 !important' }}
try not using !important

2022-12-22 14:06 UTC, kibo-amolpawar commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +  const deleteCheckoutCoupon = useDeleteCheckoutCouponMutation()
Done.

2022-12-22 14:16 UTC, kibo-amolpawar commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.stories.tsx
> +export const Common = Template.bind({})
Done.

2022-12-22 14:16 UTC, kibo-amolpawar commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.tsx
> +const CheckoutUITemplate = (props: CheckoutTemplateUIProps) => {
Done.

2022-12-22 14:16 UTC, kibo-amolpawar commented on components/page-templates/MultiShipCheckoutHeaderTemplate/MultiShipCheckoutHeaderTemplate.tsx
> +import { Checkout } from '@/lib/gql/types'
Done.

2022-12-22 14:23 UTC, kibo-amolpawar commented on components/page-templates/OrderStatusTemplate/OrderStatusTemplate.tsx
> +import { CrOrder } from '@/lib/gql/types'
Done.

2022-12-22 14:25 UTC, kibo-amolpawar commented on components/page-templates/StandardCheckoutHeaderTemplate/StandardCheckoutHeaderTemplate.tsx
> +import { CrOrder } from '@/lib/gql/types'
Done.

2022-12-23 08:35 UTC, kibo-amolpawar commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +                }}
Done.

2022-12-23 08:35 UTC, kibo-amolpawar commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +                }}
Done.

2022-12-23 08:35 UTC, kibo-amolpawar commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +                  ?.shippingRates?.map((shippingRate) => {
Done.

2022-12-23 08:36 UTC, kibo-amolpawar commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.tsx
> +                }}
Done.

2022-12-23 08:37 UTC, kibo-amolpawar commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.stories.tsx
> +}
Done.

2022-12-23 08:47 UTC, kibo-amolpawar commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.stories.tsx
> +}
Done.

2022-12-23 08:47 UTC, kibo-amolpawar commented on components/common/ShippingGroupsWithMethod/ShippingGroupsWithMethod.spec.tsx
> +})
Done.

2022-12-23 08:48 UTC, kibo-amolpawar commented on __mocks__/stories/checkoutDestinationsMock.ts
> +import { CrDestination } from '@/lib/gql/types'
Done.

2022-12-23 08:50 UTC, kibo-amolpawar commented on __mocks__/stories/createOrderPaymentActionMock.ts
> +import { CrOrder } from '@/lib/gql/types'
Done.

2022-12-23 08:50 UTC, kibo-amolpawar commented on __test__/e2e/integration/checkout/PaymentStep/PaymentStep.spec.tsx
> +import { CrOrder } from '@/lib/gql/types'
Done

2022-12-23 08:50 UTC, kibo-amolpawar commented on components/checkout/DetailsStep/DetailsStep.tsx
> +  updateCheckoutPersonalInfo: (params: any) => void //@to-do add generic type for this param as std/multi
Done.

2022-12-23 09:21 UTC, kibo-amolpawar commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  const isMultiShipPaymentStepValid = checkoutGetters.checkMultiShipPaymentValid(checkout)
Done.

2022-12-23 09:24 UTC, kibo-amolpawar commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +export default MultiShippingStep
Done.

2022-12-23 09:27 UTC, kibo-amolpawar commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +        formTitle: destinationInput?.destinationId ? 'Edit Address' : 'Add New Address',
Done.

2022-12-23 09:28 UTC, kibo-amolpawar commented on components/checkout/ReviewStep/ReviewStep.tsx
> +  const isMultiShipEnabled = publicRuntimeConfig.isMultiShipEnabled
This will replace by setting API response but now its not available

2022-12-23 09:29 UTC, kibo-amolpawar commented on components/checkout/ReviewStep/ReviewStep.tsx
> +          <Typography variant="h3" component="h3" sx={{ fontWeight: 'bold' }} color="text.primary">
Done.

2022-12-23 09:31 UTC, kibo-amolpawar commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.tsx
> +    console.log('split address need to be implemented when api will be available')
Done.

2022-12-23 09:39 UTC, kibo-amolpawar commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              sx={{ fontWeight: 'bold' }}
Done.

2022-12-23 09:44 UTC, kibo-amolpawar commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +import StandardCheckoutHeaderTemplate from '@/components/page-templates/StandardCheckoutHeaderTemplate/StandardCheckoutHeaderTemplate'
Done.

2022-12-23 09:45 UTC, kibo-amolpawar commented on components/layout/AppHeader/Common/KiboHeader.tsx
>    CheckoutHeader,
Done.

2022-12-23 09:50 UTC, kibo-amolpawar commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +      updateMode: 'ApplyToOriginal',
Done.

2022-12-23 10:01 UTC, kibo-amolpawar commented on components/checkout/DetailsStep/DetailsStep.tsx
> +  const updatePersonalInfo = async (formData: PersonalDetails) =>
Done.

2022-12-23 10:05 UTC, kibo-amolpawar commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +import AddressFormDialog from '@/components/dialogs/AddressFormDialog/AddressFormDialog'
Done.

2022-12-23 12:06 UTC, kibo-susantasamanta commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +import type { MultiShipAddress } from '@/components/common/ProductItemWithAddressList/ProductItemWithAddressList'
Resolved.

2022-12-23 12:07 UTC, kibo-susantasamanta commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +import { useModalContext } from '@/context/ModalContext'
Done.

2022-12-23 12:17 UTC, kibo-susantasamanta commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +    closeModal()
I think in that case user has to wait till the response not received and user user will be confused if button clicked or not as no progress bar is there in dialog . I error handling will cover this part.

2022-12-23 12:18 UTC, kibo-susantasamanta commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +                  style={{ textTransform: 'none' }}
Done.

2022-12-23 12:20 UTC, kibo-susantasamanta commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              {t('ship-to')}
Done.

2022-12-23 12:29 UTC, kibo-susantasamanta commented on components/checkout/MultiShippingStep/MultiShippingStep.spec.tsx
> +    setup()
Removed.

2022-12-27 15:01 UTC, kibo-susantasamanta commented on components/checkout/Shipping/OrderItems/ShippingMethod.tsx
> +                {`${item?.shippingMethodName} $${item?.price}`}
Done.

2022-12-27 15:01 UTC, kibo-susantasamanta commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.tsx
> +                  +
Done.

2022-12-27 15:01 UTC, kibo-susantasamanta commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +                {userShippingAddresses[index]?.address?.address2},{' '}
Done.

2022-12-27 15:01 UTC, kibo-susantasamanta commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +              sx={{ fontWeight: 'bold', marginTop: '0 !important' }}
Done.

2022-12-27 15:02 UTC, kibo-susantasamanta commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +                {' '}
Done.

2022-12-27 15:05 UTC, kibo-susantasamanta commented on src/pages/checkout/[checkoutId].tsx
> +          <StandardShipCheckoutTemplate {...rest} checkout={checkout as CrOrder} />
As our earlier discussions on progress we decided to go with this  , anyways we can change it later as per the recommendations. Unit test added.

2023-01-02 10:59 UTC, kibo-geetanshuchhabra commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +export default StandardShipCheckoutTemplate
Resolved

2023-01-02 11:29 UTC, kibo-sushant commented on __mocks__/stories/multiShippingRateMock.ts
> +export const multiShippingRateMock: { checkoutShippingMethods: CheckoutGroupRates[] } = {
As per the conventions used till now, file name should be CheckoutGroupRatesMock

2023-01-02 11:29 UTC, kibo-sushant commented on src/pages/checkout/[checkoutId].tsx
> +          <StandardShipCheckoutTemplate {...rest} checkout={checkout as CrOrder} />
Following unit test cases are missing
should render MultiShip Checkout Template template when multiship is enabled
should render StandardShip Checkout Template template when multiship is disabled

2023-01-02 11:29 UTC, kibo-sushant commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.stories.tsx
> +export const Common = Template.bind({})
storybook does not display stepper component (details, shipping and payment steps)

2023-01-02 11:29 UTC, kibo-sushant commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.spec.tsx
> +})
Mock KiboStepper component
Mock OrderSummary component which will accept {children}
Mock Order Confirmation component

describe('Details Step', () => {
	it('should render Details Step with Order Summery when active step is 0',()=>{})
	it('should make Shipping Step as active step when user clicks on go-to-shipping button',()=>{})
	it('should go-back button disabled',()=>{})
})

describe('Shipping Step', () => {
	it('should render Shipping Step with Order Summery when active step is 1',()=>{})
	it('should make Payment Step as active step when user clicks on go-to-payment button',()=>{})
	it('should make Details Step as active step when user clicks on go-back button',()=>{})
})

describe('Payment Step', () => {
	it('should render Payment Step with Order Summery when active step is 2',()=>{})
	it('should make Order Confirmation step as Step active when user clicks on review-order button',()=>{})
	it('should make Payment Step as active step when user clicks on go-back button',()=>{})
})

describe('Order Confirmation Step', () => {
	it('should render Order Confirmation Step when active step is 3',()=>{})
})

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/MultiShipCheckoutHeaderTemplate/MultiShipCheckoutHeaderTemplate.spec.tsx
> +}))
Where are we using useMediaQuery in code? Do we need to mock it?

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/StandardCheckoutHeaderTemplate/StandardCheckoutHeaderTemplate.spec.tsx
> +}))
Where are we using useMediaQuery in code? Do we need to mock it?

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/StandardCheckoutHeaderTemplate/StandardCheckoutHeaderTemplate.spec.tsx
> +})
Where are we using OrderSummary, OrderConfirmation,OrderReview and useMediaQuery in code?

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +import { PersonalDetails } from '@/components/checkout/DetailsStep/DetailsStep'
Not using indexfile to import?

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +const StandardShipCheckoutTemplate = (props: CheckoutProps) => {
Interface name and component name is not matching

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +    await updateStandardCheckoutPersonalInfo.mutateAsync(personalInfo)
shouldn't we pass data to updateStandardCheckoutPersonalInfo and call their buildParams, instead of building params here (similar pattern we followed other places)

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.stories.tsx
> +}
Storybook is not showing DetailsStep, PaymentStep and ReviewStep

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +        {((isAuthenticated && isSuccess) || !isAuthenticated) && (
Do we really need this condition?

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.spec.tsx
> +})
should mock DetailsStep, PaymentStep, ReviewStep and StandardShippingStep
should not mock MultiShippingStep because we are not using it

it('should render component', async () => {
 // check whether details steps is rendered or not
 // check whether PaymentStep step is rendered or not
 // check whether ReviewStep step is rendered or not
 // check whether MultiShippingStep is rendered or not 
})

it('should able apply new coupon code', async () => {})
it('should able remove coupon code', async () => {})

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +const MultiShipCheckoutTemplate = (props: CheckoutProps) => {
Component name and interface name should match

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +  }) => {
create type/interface and use it here

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +        {((isAuthenticated && isSuccess) || !isAuthenticated) && (
Do we really need this condition?

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.stories.tsx
> +}
Storybook is not showing DetailsStep and MultiShippingStep component

2023-01-03 08:13 UTC, kibo-sushant commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.spec.tsx
> +})
For code consistency, we should group all the assertions.

Missing Unit Testcases 
it('should able to apply Coupon Code', async () => {})
it('should able to remove Coupon Code', async () => {})
it('should able to update Checkout Personal Info', async () => {})
it('should able to update Checkout Personal Info', async () => {})
it('should able to create Checkout Destination', async () => {})
it('should able to update Checkout Shipping Method', async () => {})

2023-01-03 08:13 UTC, kibo-sushant commented on lib/getters/checkoutGetters.ts
> +import { MultiShipAddress } from '../types/MultiShip'
import type {

2023-01-03 08:13 UTC, kibo-sushant commented on lib/getters/checkoutGetters.ts
> +import { ShipOption } from '@/components/checkout/MultiShippingStep/MultiShippingStep'
not using index file to import?

2023-01-03 08:13 UTC, kibo-sushant commented on lib/getters/checkoutGetters.ts
> +}) => {
create type/interface and use it

2023-01-03 08:13 UTC, kibo-sushant commented on hooks/mutations/multiShip/useCreateCheckoutShippingMethodMutation/useCreateCheckoutShippingMethodMutation.tsx
> +}
Unit TestCases?

2023-01-03 09:08 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +const MultiShippingStep = (props: ShippingProps) => {
Component name and interface name should match

2023-01-03 09:08 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  }) => {
create type/interface and use it

2023-01-03 09:08 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +    }
Make it simple
const destinationId = existingDestinationAddress?.id ? destinationIdOrAddressId : await handleCreateDestinationAddress(destinationIdOrAddressId)
await updateSameDestinationForAllItems({ destinationId })

2023-01-03 10:48 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +    }
Make it simple
const destinationId = existingDestinationAddress?.id ? destinationIdOrAddressId : await handleCreateDestinationAddress(destinationIdOrAddressId)

await updateSameDestinationForAllItems({ destinationId })

2023-01-03 10:48 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  }
Make it simple

const destinationId = existingDestinationAddress?.id ? existingDestinationAddress?.id : await handleCreateDestinationAddress(value)

await updateItemDestination({
	itemId: id,
	destinationId: destinationId as string,
	checkoutId: checkout?.id as string,
})

2023-01-03 10:48 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  const shippingAddressRef = useRef()
What is use of this?

2023-01-03 10:48 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.stories.tsx
> +}
should rename common story to "Ship to more than one address"
and create one more story for Ship to Home (currently in storybook not able to select 'Ship to Home' option)

2023-01-03 10:48 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +      {shippingOption === shipOptions[0].value && (
For code readability purposes create const and use it
ex.
const shipToHome = 	shipOptions[0].value
const shipToMultiAddress = shipOptions[1].value

2023-01-03 10:48 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.spec.tsx
> +})
Missing TestCases

Mock AddressDetailsView, in such way that will able to call handleRadioChange
Mock ShippingMethod, in such way that will able to call onShippingMethodChange and handleStoreLocatorClick
Mock AddressForm, in such way that will accept {children} and able to call validateForm, onSaveAddress and onFormStatusChange
Mock ProductItemWithAddressList, in such way that will able to call onUpdateDestinationAddress and onSelectCreateOrSetDestinationAddress
Mock ShippingGroupsWithMethod, in such way that will able to call onClickEditMultiShippingDetails and onUpdateCheckoutShippingMethod

describe('Shipt TO Home', () => {
	
	it('should render component when initial Shipping Option is ShipToHome', async () => {})
	it('should save after address selection', async () => {})
	
	it('should show address form when user clicks on Add New Address button', async () => {})
	it('should enable save-shipping-address button only when address form is valid', async () => {})
	it('should save address when user clicks on save-shipping-address button', async () => {})
	it('should show saved addresses when user clicks on cancel button', async () => {})
		
	it('should save shipping method when user select it', async () => {})
	it('should open store locator when user clicks on Store Locator', async () => {})
	
})

describe('Ship To Multi Address', () => {
	
	it('should render component when initial Shipping Option is ShipToMultiAddress', async () => {})

	it('should ... when user selects address', async () => {})
	it('should ... when user clicks on Edit Address link', async () => {})
	it('should ... when user clicks on Add New Address link', async () => {})

	it('should render Shipping Groups With Method when user clicks on Continue button', async () => {})
	it('should ... when user selects shipping method ', async () => {})
	it('should ... when user clicks on Edit Multi Shipping Details', async () => {})
})

2023-01-03 19:56 UTC, kibo-kevinwatts commented on lib/constants/index.ts
> +export const PersonalInfoUpdateMode = { APPLYTOORIGINAL: 'ApplyToOriginal' }
change `PersonalInfoUpdateMode` to `CheckoutUpdateMode` and add underscores for readability. `APPLY_TO_ORIGINAL`

2023-01-03 20:52 UTC, kibo-kevinwatts requested changes

2023-01-03 20:52 UTC, kibo-kevinwatts commented on lib/getters/addressGetters.ts
> +  getPostalOrZipCode(contact?.address)
Don't think `getPostalOrZipCode` should be listed twice

2023-01-03 20:52 UTC, kibo-kevinwatts commented on lib/getters/checkoutGetters.ts
> +import { ShipOption } from '@/components/checkout/MultiShippingStep/MultiShippingStep'
why is this getter importing from components? 
Should we extract the type to "types"?

2023-01-03 20:52 UTC, kibo-kevinwatts commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +        <MultiShipCheckoutHeaderTemplate />
as discussed, only one `CheckoutHeader` is required.

2023-01-03 20:52 UTC, kibo-kevinwatts commented on components/checkout/Shipping/OrderItems/ShippingMethod.tsx
>  import { Typography, Box, MenuItem, Divider } from '@mui/material'
Why is this component in a nested 'Shipping/OrderItems' folder? Should be `components/checkout/ShippingMethod`

2023-01-03 20:52 UTC, kibo-kevinwatts commented on components/page-templates/StandardCheckoutHeaderTemplate/StandardCheckoutHeaderTemplate.tsx
> +import React from 'react'
No need for this component

2023-01-03 20:52 UTC, kibo-kevinwatts commented on components/page-templates/MultiShipCheckoutHeaderTemplate/MultiShipCheckoutHeaderTemplate.tsx
> +import React from 'react'
No need for this component

2023-01-03 20:52 UTC, kibo-kevinwatts commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.tsx
> +import React from 'react'
this component should be moved under `components/checkout` 
only components that represent a "page" should be in the page-templates folder

2023-01-03 20:52 UTC, kibo-kevinwatts commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.tsx
> +  isSuccess: boolean
this prop is unused and poorly named, delete

2023-01-03 20:52 UTC, kibo-kevinwatts commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +  const { data: savedUserAddressData, isSuccess } = useCustomerContactsQueries(user?.id as number)
what is 'isSuccess' used for?  if needed, can we rename?

2023-01-03 20:52 UTC, kibo-kevinwatts commented on lib/api/operations/get-category-tree.ts
>        cache.set(cacheKey, items, cacheTimeOut)
only call `cache.set` if items has value

2023-01-04 07:18 UTC, kibo-geetanshuchhabra commented on src/pages/checkout/[checkoutId].tsx
> +          <StandardShipCheckoutTemplate {...rest} checkout={checkout as CrOrder} />
Resolved

2023-01-04 07:20 UTC, kibo-geetanshuchhabra commented on lib/getters/checkoutGetters.ts
> +import { MultiShipAddress } from '../types/MultiShip'
Resolved

2023-01-04 09:11 UTC, kibo-chandradeeptalaha commented on lib/api/operations/get-category-tree.ts
>        cache.set(cacheKey, items, cacheTimeOut)
Done

2023-01-04 09:11 UTC, kibo-chandradeeptalaha commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.tsx
> +  isSuccess: boolean
Done

2023-01-04 09:11 UTC, kibo-chandradeeptalaha commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.tsx
> +import React from 'react'
Done

2023-01-04 09:12 UTC, kibo-chandradeeptalaha commented on components/page-templates/MultiShipCheckoutHeaderTemplate/MultiShipCheckoutHeaderTemplate.tsx
> +import React from 'react'
Removed

2023-01-04 09:12 UTC, kibo-chandradeeptalaha commented on components/page-templates/StandardCheckoutHeaderTemplate/StandardCheckoutHeaderTemplate.tsx
> +import React from 'react'
Removed

2023-01-04 09:12 UTC, kibo-chandradeeptalaha commented on components/checkout/Shipping/OrderItems/ShippingMethod.tsx
>  import { Typography, Box, MenuItem, Divider } from '@mui/material'
Done

2023-01-04 09:12 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +        <MultiShipCheckoutHeaderTemplate />
Done

2023-01-04 09:12 UTC, kibo-chandradeeptalaha commented on lib/getters/addressGetters.ts
> +  getPostalOrZipCode(contact?.address)
Done

2023-01-04 09:12 UTC, kibo-chandradeeptalaha commented on lib/constants/index.ts
> +export const PersonalInfoUpdateMode = { APPLYTOORIGINAL: 'ApplyToOriginal' }
Done

2023-01-04 10:15 UTC, kibo-geetanshuchhabra commented on components/checkout/MultiShippingStep/MultiShippingStep.stories.tsx
> +}
As discussed, not required because able to click ship to home radio button

2023-01-04 11:10 UTC, TriptiVermaXP commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +      {shippingOption === shipOptions[0].value && (
Done

2023-01-04 11:10 UTC, TriptiVermaXP commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  }
Done

2023-01-04 11:10 UTC, TriptiVermaXP commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +    }
Done

2023-01-04 11:10 UTC, TriptiVermaXP commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +    }
Done

2023-01-04 11:10 UTC, TriptiVermaXP commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  }) => {
Done

2023-01-04 11:11 UTC, TriptiVermaXP commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +const MultiShippingStep = (props: ShippingProps) => {
Done

2023-01-04 11:11 UTC, TriptiVermaXP commented on lib/getters/checkoutGetters.ts
> +}) => {
Done

2023-01-04 11:11 UTC, TriptiVermaXP commented on lib/getters/checkoutGetters.ts
> +import { ShipOption } from '@/components/checkout/MultiShippingStep/MultiShippingStep'
Done

2023-01-04 11:11 UTC, TriptiVermaXP commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +  }) => {
Done

2023-01-04 11:11 UTC, TriptiVermaXP commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +const MultiShipCheckoutTemplate = (props: CheckoutProps) => {
Done

2023-01-04 11:11 UTC, TriptiVermaXP commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +    await updateStandardCheckoutPersonalInfo.mutateAsync(personalInfo)
Done

2023-01-04 11:11 UTC, TriptiVermaXP commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +const StandardShipCheckoutTemplate = (props: CheckoutProps) => {
Done

2023-01-04 11:11 UTC, TriptiVermaXP commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +import { PersonalDetails } from '@/components/checkout/DetailsStep/DetailsStep'
Done

2023-01-04 11:12 UTC, TriptiVermaXP commented on __mocks__/stories/multiShippingRateMock.ts
> +export const multiShippingRateMock: { checkoutShippingMethods: CheckoutGroupRates[] } = {
Done

2023-01-04 12:40 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  const shippingAddressRef = useRef()
will check on this once dev10 is up.

2023-01-04 12:54 UTC, kibo-chandradeeptalaha commented on hooks/mutations/multiShip/useCreateCheckoutShippingMethodMutation/useCreateCheckoutShippingMethodMutation.tsx
> +}
Done

2023-01-04 13:45 UTC, kibo-chandradeeptalaha commented on components/page-templates/StandardCheckoutHeaderTemplate/StandardCheckoutHeaderTemplate.spec.tsx
> +})
File removed

2023-01-04 14:15 UTC, kibo-chandradeeptalaha commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.stories.tsx
> +export const Common = Template.bind({})
Resolved

2023-01-04 14:15 UTC, kibo-chandradeeptalaha commented on components/page-templates/MultiShipCheckoutHeaderTemplate/MultiShipCheckoutHeaderTemplate.stories.tsx
> +Common.args = checkoutMock.checkout
Removed Component

2023-01-04 14:15 UTC, kibo-chandradeeptalaha commented on components/page-templates/StandardCheckoutHeaderTemplate/StandardCheckoutHeaderTemplate.stories.tsx
> +Common.args = checkoutMock.checkout
Removed file

2023-01-04 14:16 UTC, kibo-chandradeeptalaha commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.stories.tsx
> +}
Resolved

2023-01-04 14:17 UTC, kibo-chandradeeptalaha commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.stories.tsx
> +}
Resolved

2023-01-04 15:08 UTC, kibo-geetanshuchhabra commented on components/page-templates/StandardCheckoutHeaderTemplate/StandardCheckoutHeaderTemplate.spec.tsx
> +}))
File removed

2023-01-04 15:08 UTC, kibo-geetanshuchhabra commented on components/page-templates/MultiShipCheckoutHeaderTemplate/MultiShipCheckoutHeaderTemplate.spec.tsx
> +}))
File removed

2023-01-06 12:30 UTC, kibo-sushant commented on components/page-templates/CheckoutUITemplate/CheckoutUITemplate.spec.tsx
> +})
Resolved all the comments

2023-01-10 09:59 UTC, TriptiVermaXP approved these changes

2023-01-10 10:10 UTC, kibo-chandradeeptalaha approved these changes

2023-01-10 15:04 UTC, kibo-sushant approved these changes

2023-01-10 23:31 UTC, kibo-kevinwatts approved these changes

2023-01-11 17:41 UTC, merged