feat: implement multiship review step
KiboSoftware/nextjs-storefront pull request #190
Opened 2022-12-16 10:37 UTC by kibo-susantasamanta

2022-12-20 13:00 UTC, TriptiVermaXP requested changes
Please check review comments.

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/checkout/ReviewStep/ReviewStep.stories.tsx
> +import type { CommonCheckout } from '@/components/page-templates/CheckoutUITemplate/CheckoutUITemplate'
use index file for import/export

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/checkout/ReviewStep/ReviewStep.stories.tsx
>  import { CheckoutStepProvider } from '@/context/CheckoutStepContext/CheckoutStepContext'
use index file for import/export

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/checkout/ReviewStep/ReviewStep.tsx
> +import { CommonCheckout } from '@/components/page-templates/CheckoutUITemplate/CheckoutUITemplate'
use index file for import/export

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +    console.log('handleCreateOrder called.....')
Please remove console.log, and what needs to be handled here?
add @to-do if there is anything

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
> +                  sx={{ '&::after': { content: "','", pr: 0.5 }, textTransform: 'capitalize' }}
instead of repeating css in each typography, can't we have common styles and use everywhere?

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
>  import { userAddressResponse } from '@/__mocks__/stories/userAddressMock'
what's need to be handled?

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/checkout/OrderReview/OrderReview.tsx
> +  // Need to be handled with API later
what need to be handled?

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/checkout/OrderReview/OrderReview.tsx
> +import { userAddressResponse } from '@/__mocks__/stories/userAddressMock'
what need to be handled?

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/common/ProductItemWithAddressList/ProductItemWithAddressList.tsx
> +    console.log('split address need to be implemented when api will be available')
what's need to be handled? Add @to-do if anything remaining.

2022-12-20 13:00 UTC, TriptiVermaXP commented on __mocks__/stories/checkoutDestinationsMock.ts
> +import { CrDestination } from '@/lib/gql/types'
use type

2022-12-20 13:00 UTC, TriptiVermaXP commented on __mocks__/stories/createOrderPaymentActionMock.ts
> +import { CrOrder } from '@/lib/gql/types'
use type

2022-12-20 13:00 UTC, TriptiVermaXP commented on __test__/e2e/integration/checkout/PaymentStep/PaymentStep.spec.tsx
> +import { CrOrder } from '@/lib/gql/types'
use type

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/checkout/OrderReview/OrderReview.tsx
> +  const { checkout, isMultiShipEnabled = true } = props
Why hardcoded here? this should be passed from parent comp.

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/checkout/ReviewStep/ReviewStep.tsx
> +      {/* multiShip array will be used later after API is handled instead on shipItems */}
what need to be handled?

2022-12-20 13:00 UTC, TriptiVermaXP commented on components/checkout/ReviewStep/ReviewStep.stories.tsx
> +  isMultiShipEnabled: true,
storybook is failing

2023-01-03 22:34 UTC, kibo-kevinwatts requested changes

2023-01-03 22:34 UTC, kibo-kevinwatts commented on components/common/ReviewProductItemsWithAddresses/ReviewProductItemsWithAddresses.tsx
>  import React from 'react'
Do we need this is a separate component?
Could we just display the addresses on the Review Step and use the re-use the same ProductItemList component?

2023-01-03 22:34 UTC, kibo-kevinwatts commented on components/checkout/ReviewStep/ReviewStep.tsx
> +import { CommonCheckout } from '@/components/page-templates/CheckoutUITemplate/CheckoutUITemplate'
This should be `import type` and/or possible moved to the type folder to make it clear.

2023-01-18 15:08 UTC, closed without merging