feat:subscription component dashboard implementation
KiboSoftware/nextjs-storefront pull request #192
Opened 2022-12-20 11:24 UTC by kibo-nehabhanushali

2022-12-21 00:42 UTC, kibo-kevinwatts requested changes

2022-12-21 00:42 UTC, kibo-kevinwatts commented on lib/gql/fragments/subscription.ts
> +    weightedOrderHandlingFee
Are we using all of these fields?

2022-12-21 00:42 UTC, kibo-kevinwatts commented on lib/gql/fragments/subscription.ts
> +  fragment baseSubscriptionFragment on Subscription {
I don't see this "baseSubscriptionFragment" used in any queries. What it is this for?

2022-12-21 00:42 UTC, kibo-kevinwatts commented on hooks/queries/subscription/useSubscriptionsQueries/useSubscriptionsQueries.ts
> +  try {
I don't think we are using this try catch pattern around any of the other hooks

2022-12-21 00:42 UTC, kibo-kevinwatts commented on components/my-account/Subscription/Subscription.tsx
> -
Why modify the existing single Subscription component to now handle a list of subscriptions?
We want to keep the single Subscription Component

2022-12-21 06:28 UTC, kibo-nehabhanushali commented on lib/gql/fragments/subscription.ts
> +    weightedOrderHandlingFee
No , Removed it

2022-12-21 06:30 UTC, kibo-nehabhanushali commented on hooks/queries/subscription/useSubscriptionsQueries/useSubscriptionsQueries.ts
> +  try {
sure, removed it

2022-12-21 08:12 UTC, TriptiVermaXP requested changes
Please check review comments

2022-12-21 08:12 UTC, TriptiVermaXP commented on components/my-account/Subscription/MySubscription.tsx
> +      <Stack sx={{ mt: '2%' }}>
We can directly use few props like margin, padding, fonts etc to Typography and stack tags, instead applying sx everywhere.

2022-12-21 08:12 UTC, TriptiVermaXP commented on components/my-account/Subscription/MySubscription.stories.tsx
> +  title: 'Subscription/Subscription',
component name and story book title mismatched

2022-12-21 08:12 UTC, TriptiVermaXP commented on components/my-account/Subscription/MySubscription.tsx
> +                  </Typography>
can we use ProductOption component instead typography for key pair value.
ex:
 <ProductOption option={{ name: t('subscription-number'), value: subscriptionGetters.getSubscriptionNumber(subscriptionItemData as Subscription)}} variant="body2" />

2022-12-21 08:12 UTC, TriptiVermaXP commented on components/my-account/Subscription/MySubscription.tsx
> +                  </Typography>
unit tests are missing for all subscription values.

2022-12-21 08:12 UTC, TriptiVermaXP commented on components/page-templates/MyAccountTemplate/MyAccountTemplate.tsx
> +        </Box>
unit test is missing

2022-12-21 09:28 UTC, kibo-nehabhanushali commented on lib/gql/fragments/subscription.ts
> +  fragment baseSubscriptionFragment on Subscription {
It was added for base but as there are only 2 properties we need from this , removed this fragment

2022-12-21 11:58 UTC, kibo-nehabhanushali commented on components/my-account/Subscription/Subscription.tsx
> -
Done , separeted subscription item and components

2022-12-21 13:38 UTC, kibo-nehabhanushali commented on components/my-account/Subscription/MySubscription.stories.tsx
> +  title: 'Subscription/Subscription',
done , updated

2022-12-21 13:39 UTC, kibo-nehabhanushali commented on components/my-account/Subscription/MySubscription.tsx
> +                  </Typography>
unit test cases are remaining , work is in progress

2022-12-21 13:53 UTC, kibo-nehabhanushali commented on components/my-account/Subscription/MySubscription.tsx
> +      <Stack sx={{ mt: '2%' }}>
done

2022-12-21 14:10 UTC, kibo-nehabhanushali commented on components/my-account/Subscription/MySubscription.tsx
> +                  </Typography>
done

2022-12-23 07:11 UTC, TriptiVermaXP approved these changes

2022-12-29 10:42 UTC, kibo-nehabhanushali commented on components/my-account/Subscription/MySubscription.tsx
> +                  </Typography>
done

2022-12-29 10:42 UTC, kibo-nehabhanushali commented on components/page-templates/MyAccountTemplate/MyAccountTemplate.tsx
> +        </Box>
done

2023-01-02 09:50 UTC, kibo-sushant commented on components/my-account/Subscription/SubscriptionList/SubscriptionList.stories.tsx
> +}
I think, storybook should show multiple subscriptions

2023-01-02 09:50 UTC, kibo-sushant commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.spec.tsx
> +import * as stories from './SubscriptionItem.stories' // import all stories from the stories file
Should render component - not verifying whether following things are rendered or not

SubscriberName
SubscriberAddress
Edit Frequency
Edit Order Date
Cancel An Item
Edit Billing Information
Edit Shipping Address
Pause Subscription

2023-01-02 09:50 UTC, kibo-sushant commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.tsx
> +}
Do we need this as a separate component?

2023-01-02 09:50 UTC, kibo-sushant commented on components/my-account/Subscription/SubscriptionList/SubscriptionList.spec.tsx
> +}))
we are not passing any children in actual component, hence its not required
change subscription-item-list-mock to subscription-item-mock

2023-01-02 09:50 UTC, kibo-sushant commented on components/my-account/Subscription/SubscriptionList/SubscriptionList.spec.tsx
> +  })
actually we are calling subscriptionItem in loop, so we should check whether same number of subscription-item-mock are rendered or not

2023-01-02 09:52 UTC, TriptiVermaXP approved these changes

2023-01-03 12:02 UTC, TriptiVermaXP commented on components/my-account/Subscription/SubscriptionList/SubscriptionList.spec.tsx
> +  })
Done

2023-01-03 12:02 UTC, TriptiVermaXP commented on components/my-account/Subscription/SubscriptionList/SubscriptionList.spec.tsx
> +}))
Done

2023-01-03 12:03 UTC, kibo-sushant approved these changes

2023-01-03 12:03 UTC, TriptiVermaXP commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.tsx
> +}
Done

2023-01-03 12:03 UTC, TriptiVermaXP commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.spec.tsx
> +import * as stories from './SubscriptionItem.stories' // import all stories from the stories file
Done

2023-01-03 12:03 UTC, TriptiVermaXP commented on components/my-account/Subscription/SubscriptionList/SubscriptionList.stories.tsx
> +}
Done

2023-01-03 22:25 UTC, kibo-kevinwatts approved these changes

2023-01-04 06:14 UTC, merged