feat: orderSubscriptionNow implementation
KiboSoftware/nextjs-storefront pull request #195
Opened 2022-12-21 14:47 UTC by kibo-chandradeeptalaha

2022-12-22 11:13 UTC, TriptiVermaXP requested changes

2022-12-22 11:13 UTC, TriptiVermaXP commented on hooks/mutations/subscription/useOrderSubscriptionNowMutation.ts
> +export const useOrderSubscriptionNowMutation = () => {
please do the documentation using typedoc

2022-12-22 11:13 UTC, TriptiVermaXP commented on components/my-account/Subscription/SubscriptionItemList/SubscriptionItemList.tsx
> +                      handleShipItemNow({ id: subscriptionItemData?.id as string })
test case is missing

2022-12-22 15:31 UTC, kibo-chandradeeptalaha commented on hooks/mutations/subscription/useOrderSubscriptionNowMutation.ts
> +export const useOrderSubscriptionNowMutation = () => {
Updated

2022-12-22 15:31 UTC, kibo-chandradeeptalaha commented on components/my-account/Subscription/SubscriptionItemList/SubscriptionItemList.tsx
> +                      handleShipItemNow({ id: subscriptionItemData?.id as string })
Added

2023-01-03 22:48 UTC, kibo-kevinwatts approved these changes

2023-01-03 22:50 UTC, kibo-kevinwatts requested changes
needs hook unit tests

2023-01-09 08:19 UTC, kibo-sushant commented on hooks/mutations/subscription/useOrderSubscriptionNow/useOrderSubscriptionNowMutation.ts
> +import { useMutation, useQueryClient } from 'react-query'
missing

/**
 * @module ...
 */

2023-01-09 17:08 UTC, kibo-chandradeeptalaha commented on hooks/mutations/subscription/useOrderSubscriptionNow/useOrderSubscriptionNowMutation.ts
> +import { useMutation, useQueryClient } from 'react-query'
Done

2023-01-10 00:16 UTC, kibo-kevinwatts approved these changes

2023-01-10 06:49 UTC, TriptiVermaXP approved these changes

2023-01-10 06:57 UTC, merged