feat: initial commit
KiboSoftware/nextjs-storefront pull request #197
Opened 2022-12-22 08:13 UTC by kibo-sushant

2022-12-22 10:02 UTC, kibo-chandradeeptalaha commented on components/dialogs/EditSubscriptionFrequencyDialog/EditSubscriptionFrequencyDialog.tsx
> +    const isUnitPlural = unit.charAt(unit.length - 1).toLowerCase() === 's'
Do we need this ? According to the discussion I dont think so it matters

2022-12-22 10:03 UTC, kibo-chandradeeptalaha approved these changes

2022-12-22 10:27 UTC, TriptiVermaXP requested changes
Please check review comments

2022-12-22 10:27 UTC, TriptiVermaXP commented on components/dialogs/EditSubscriptionFrequencyDialog/EditSubscriptionFrequencyDialog.tsx
> +import KiboDialog from '@/components/common/KiboDialog/KiboDialog'
import directly from index file
import { KiboSelect, KiboDialog } from '@/components/common'

2022-12-22 10:27 UTC, TriptiVermaXP commented on components/dialogs/EditSubscriptionFrequencyDialog/EditSubscriptionFrequencyDialog.tsx
> +import { SbProductPropertyValue } from '@/lib/gql/types'
use type

2022-12-22 10:27 UTC, TriptiVermaXP commented on components/dialogs/EditSubscriptionFrequencyDialog/EditSubscriptionFrequencyDialog.tsx
> +  }
we can do like 
  const handleFrequencyChange = async (_name: string, value: string) => setSelectedFrequency(value)

2022-12-22 10:27 UTC, TriptiVermaXP commented on components/my-account/Subscription/SubscriptionItemList/SubscriptionItemList.tsx
> +      (property) => property?.name === 'Subscription Frequency'
we may use constant for 'Subscription Frequency'

2022-12-22 10:27 UTC, TriptiVermaXP commented on components/my-account/Subscription/SubscriptionItemList/SubscriptionItemList.tsx
> +  const handleEditFrequency = (subscriptionId: string, itemsArray: SbSubscriptionItem[]) => {
can we rename to items or subscriptonItems instead itemsArray?

2022-12-22 11:20 UTC, kibo-sushant commented on components/dialogs/EditSubscriptionFrequencyDialog/EditSubscriptionFrequencyDialog.tsx
> +    const isUnitPlural = unit.charAt(unit.length - 1).toLowerCase() === 's'
Yes, its required

2023-01-03 23:51 UTC, kibo-kevinwatts requested changes

2023-01-03 23:51 UTC, kibo-kevinwatts commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.tsx
> +      (property) => property?.name === SubscriptionProductProperties.SUBSCRIPTION_FREQUENCY
I suggest making this a re-usable function (maybe a getter) that takes the product as an argument. We'll probably need for Product Details page.
Also, perform the lookup using `property?.attributeFQN` instead of `property.name` the name is not unique

2023-01-04 10:09 UTC, kibo-sushant commented on components/dialogs/EditSubscriptionFrequencyDialog/EditSubscriptionFrequencyDialog.tsx
> +import KiboDialog from '@/components/common/KiboDialog/KiboDialog'
resolved

2023-01-04 10:09 UTC, kibo-sushant commented on components/dialogs/EditSubscriptionFrequencyDialog/EditSubscriptionFrequencyDialog.tsx
> +import { SbProductPropertyValue } from '@/lib/gql/types'
resolved

2023-01-04 10:09 UTC, kibo-sushant commented on components/dialogs/EditSubscriptionFrequencyDialog/EditSubscriptionFrequencyDialog.tsx
> +  }
resolved

2023-01-04 10:11 UTC, kibo-sushant commented on components/my-account/Subscription/SubscriptionItemList/SubscriptionItemList.tsx
> +      (property) => property?.name === 'Subscription Frequency'
resolved

2023-01-04 10:11 UTC, kibo-sushant commented on components/my-account/Subscription/SubscriptionItemList/SubscriptionItemList.tsx
> +  const handleEditFrequency = (subscriptionId: string, itemsArray: SbSubscriptionItem[]) => {
resolved

2023-01-05 08:57 UTC, kibo-chandradeeptalaha commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.tsx
> +      (property) => property?.name === SubscriptionProductProperties.SUBSCRIPTION_FREQUENCY
Done

2023-01-09 04:14 UTC, kibo-kevinwatts approved these changes

2023-01-09 06:26 UTC, TriptiVermaXP approved these changes

2023-01-09 06:26 UTC, merged