feat(useProductPrice): feature/icky 808 useProductPrice hook
KiboSoftware/nextjs-storefront pull request #201
Opened 2023-01-11 20:10 UTC by kibo-Kripa

2023-01-17 23:53 UTC, kibo-kevinwatts requested changes
One small change requested on test case description

2023-01-17 23:53 UTC, kibo-kevinwatts commented on hooks/queries/useProductPriceQueries/useProductPriceQueries.spec.ts
> +  it('should return product search result when facet filters is selected', async () => {
update test case description to be relevant to use case

2023-01-18 14:32 UTC, kibo-chandradeeptalaha approved these changes

2023-01-18 20:19 UTC, kibo-Kripa commented on hooks/queries/useProductPriceQueries/useProductPriceQueries.spec.ts
> +  it('should return product search result when facet filters is selected', async () => {
Done

2023-01-18 21:31 UTC, kibo-kevinwatts approved these changes

2023-01-18 21:32 UTC, merged