feat: payment step with unit test cases
KiboSoftware/nextjs-storefront pull request #202
Opened 2023-01-13 10:09 UTC by kibo-chandradeeptalaha

2023-01-17 18:09 UTC, kibo-Kripa commented on components/checkout/CheckoutUITemplate/CheckoutUITemplate.stories.tsx
> +const handleUpdateCheckoutPersonalInfo = async () => undefined
Is async needed here?

2023-01-18 00:23 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +    it('should call saveCardDataToOrder function', () => {
what is saveCardDataToOrder?

2023-01-18 06:44 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +    it('should call saveCardDataToOrder function', () => {
It's called when we click on "go to review" button. internally it calls onVoidPayment and onAddPayment props methods

2023-01-18 07:18 UTC, kibo-chandradeeptalaha commented on components/checkout/CheckoutUITemplate/CheckoutUITemplate.stories.tsx
> +const handleUpdateCheckoutPersonalInfo = async () => undefined
yes

2023-01-19 12:15 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +  }: {
validateForm property is missing, we should add that and trigger that as well

2023-01-19 12:15 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +    onFormStatusChange,
validateForm prop is missing, we should add it and trigger this as wel

2023-01-19 12:15 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +  default: () => <div data-testid="saved-payment-method-view-mock" />,
onPaymentCardSelection prop is missing, we should add it and trigger it through testcase

2023-01-19 12:15 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +      expect(screen.getAllByTestId('saved-payment-method-view-mock').length).toBe(1)
Instead of testing just for one card, test for multiple items

2023-01-19 12:15 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +      expect(onAddPaymentMock).toBeCalled()
**naming convention should be more meaningful.** 
 instead of 
 "Saved Customer Address and Previously saved Payment Info is available"
 something like 'show/display Saved Customer Addresses and Payment Info"

**naming should be scenario based instead of technical keywords.** 
instead of "should call handleInitialCardDetailsLoad and add a new Card details"
something like "should display/render previously saved payments"

instead of "should call saveCardDataToOrder function"
something like "should save card details when ... "

**Some of the scenarios are missing**
should able to select previously saved payment

should display save-payment-method checkbox only when user is loggedin
should ... when user is loggedIn and selects save-payment-method checkbox 

should open add new form when user clicks on add-payment-method method
should copy shipping address when user clicks on billing-address-same-as-shipping checkbox
should display content in address form when user enters it
should save the address when user clicks on Save button
should close the address form when user clicks on Cancel button

2023-01-19 12:25 UTC, kibo-sushant requested changes

2023-01-19 12:25 UTC, kibo-sushant commented on hooks/mutations/multiShip/useUpdateCheckoutPaymentActionMutation/useUpdateCheckoutPaymentActionMutation.ts
> + * @module useUpdateMultiShipCheckoutPaymentActionMutation
name is not matching

2023-01-19 12:25 UTC, kibo-sushant commented on hooks/mutations/multiShip/useUpdateCheckoutPaymentActionMutation/useUpdateCheckoutPaymentActionMutation.ts
> + * [Mutation hook] useUpdateMultiShipCheckoutPaymentActionMutation uses the graphQL mutation
name is incorrect

2023-01-19 12:25 UTC, kibo-sushant commented on hooks/mutations/multiShip/useUpdateCheckoutPaymentActionMutation/useUpdateCheckoutPaymentActionMutation.ts
> + * <b>updateCheckoutPayment(checkoutId: String!,paymentId: String!,paymentActionInput: PaymentActionInput): Checkout</b>
params are incorrect

2023-01-20 07:06 UTC, kibo-chandradeeptalaha commented on hooks/mutations/multiShip/useUpdateCheckoutPaymentActionMutation/useUpdateCheckoutPaymentActionMutation.ts
> + * @module useUpdateMultiShipCheckoutPaymentActionMutation
Rename is pending in another ticket

2023-01-20 07:06 UTC, kibo-chandradeeptalaha commented on hooks/mutations/multiShip/useUpdateCheckoutPaymentActionMutation/useUpdateCheckoutPaymentActionMutation.ts
> + * [Mutation hook] useUpdateMultiShipCheckoutPaymentActionMutation uses the graphQL mutation
Rename is pending in another ticket

2023-01-24 09:32 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +      expect(onAddPaymentMock).toBeCalled()
Changed test cases

2023-01-24 10:05 UTC, kibo-sushant requested changes

2023-01-24 10:05 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.tsx
> +          )}
1. Card number textbox is little big comparing to other textboxes
2. "Go Back" button is not working 
3. "Save Payment Method" functionality is not working
4. For logged in user, application is not allowing to create new Payment Method with existing address
5. Tabs are taking user to back step but not front though step is valid (nice to have functionality)

2023-01-24 10:44 UTC, kibo-sushant requested changes

2023-01-24 10:44 UTC, kibo-sushant commented on components/checkout/ReviewStep/ReviewStep.tsx
> +      )}
1. remove commented code   // expectedDeliveryDate={expectedDeliveryDate}
2. Missing the Unit Test cases

2023-01-24 12:17 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +          )}
"Save Payment Method" functionality is not working
- Not a bug. Payment is saved after checkout process is successful.

For logged in user, application is not allowing to create new Payment Method with existing address
- Need separate ticket

Tabs are taking user to back step but not front even though step is valid (nice to have functionality)
-Need separate ticket for this feature.

"Go Back" button is not working.
-Need a bug ticket

2023-01-24 12:22 UTC, kibo-chandradeeptalaha commented on components/checkout/ReviewStep/ReviewStep.tsx
> +      )}
Will cover in icky-810

2023-01-24 12:23 UTC, kibo-sushant approved these changes

2023-01-31 00:33 UTC, kibo-kevinwatts approved these changes

2023-01-31 08:27 UTC, merged