Feature/icky 802
KiboSoftware/nextjs-storefront pull request #207
Opened 2023-01-23 14:38 UTC by kibo-chandradeeptalaha

2023-01-24 08:17 UTC, kibo-sushant requested changes

2023-01-24 08:17 UTC, kibo-sushant commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
>          <Box pt={2} display="flex" sx={{ justifyContent: 'space-between' }}>
Unable to test using Storybook
Unit Testcases are missing

2023-01-24 08:31 UTC, kibo-sushant requested changes

2023-01-24 08:31 UTC, kibo-sushant commented on lib/getters/productGetters.ts
> +    productSubscriptionPrice: getSubscriptionPrice(subscriptionPrice),
Update the unit testcases accordingly.

2023-01-24 08:31 UTC, kibo-sushant commented on lib/getters/subscriptionGetters.ts
> +  getSubscriptionFrequencyUnit,
Update the unit testcases accordingly.

2023-01-24 08:50 UTC, kibo-sushant requested changes

2023-01-24 08:50 UTC, kibo-sushant commented on lib/getters/subscriptionGetters.ts
> +const getSubscriptionFrequencyUnit = (selectedFrequency: string) => {
name is not meaningful (we are returning both unit and value)

2023-01-24 08:50 UTC, kibo-sushant commented on components/page-templates/ProductDetail/ProductDetailTemplate.spec.tsx
> +
alongwith handlePurchaseTypeSelection also pass selected prop and verify it
Not mocking KiboSelect, Price, QuantitySelector ?
Unit Test is not covering all the scenarios of the code

2023-01-24 08:50 UTC, kibo-sushant commented on components/page-templates/ProductDetail/ProductDetailTemplate.spec.tsx
> +
alongwith handlePurchaseTypeSelection also pass selected prop and verify it
Not mocking KiboSelect, Price, QuantitySelector ?
Unit Test is not covering all the scenarios of the code

2023-01-25 11:25 UTC, Kibo-TriptiV commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
>          <Box pt={2} display="flex" sx={{ justifyContent: 'space-between' }}>
Done

2023-01-25 11:26 UTC, Kibo-TriptiV commented on lib/getters/productGetters.ts
> +    productSubscriptionPrice: getSubscriptionPrice(subscriptionPrice),
Done

2023-01-25 11:26 UTC, Kibo-TriptiV commented on lib/getters/subscriptionGetters.ts
> +  getSubscriptionFrequencyUnit,
Done

2023-01-25 11:26 UTC, Kibo-TriptiV commented on lib/getters/subscriptionGetters.ts
> +const getSubscriptionFrequencyUnit = (selectedFrequency: string) => {
Done

2023-01-25 11:27 UTC, Kibo-TriptiV commented on components/page-templates/ProductDetail/ProductDetailTemplate.spec.tsx
> +
Not required to mock for subscription tests, I have covered unit test for subscription now. Need to refactor existing tests.

2023-01-25 11:28 UTC, Kibo-TriptiV commented on components/page-templates/ProductDetail/ProductDetailTemplate.spec.tsx
> +
Done

2023-01-31 00:52 UTC, kibo-kevinwatts requested changes

2023-01-31 00:52 UTC, kibo-kevinwatts commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +  const { data: subscriptionPrice } = useProductPriceQueries(
we always want to use the price returned from the `useProductPriceQuery` not just when its subscription price. we should rename and make changes for hook to always load

2023-01-31 00:52 UTC, kibo-kevinwatts commented on hooks/queries/useProductPriceQueries/useProductPriceQueries.ts
> +      enabled: !!(productCode && useSubscriptionPricing),
as mentioned in pdp template comment, don't disable based on `useSubscriptionPricing`

2023-02-01 09:53 UTC, kibo-sushant approved these changes

2023-02-02 08:36 UTC, Kibo-TriptiV commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +  const { data: subscriptionPrice } = useProductPriceQueries(
Done

2023-02-02 08:37 UTC, Kibo-TriptiV commented on hooks/queries/useProductPriceQueries/useProductPriceQueries.ts
> +      enabled: !!(productCode && useSubscriptionPricing),
Done

2023-02-06 20:52 UTC, kibo-kevinwatts approved these changes

2023-02-07 07:03 UTC, merged