feat(colorVariant) : implement product color variant
KiboSoftware/nextjs-storefront pull request #21
Opened 2022-03-21 13:41 UTC by sss-bct

2022-03-21 13:59 UTC, kibo-chandradeeptalaha requested changes
Please check

2022-03-21 13:59 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.spec.js
> +import ProductVariantColorSelectorStories, * as stories from './ProductVariantColorSelector.stories' // import all stories from the stories file
fix import statement

2022-03-21 13:59 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.spec.js
> +    expect(colorSelector).toBeVisible()
check the length of colors passed as well

2022-03-21 13:59 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.spec.js
> +  it('should render a color and call onChange when clicked', () => {
duplicate testcase

2022-03-21 13:59 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.stories.tsx
> +import { blue } from '@mui/material/colors'
unused import

2022-03-21 13:59 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.tsx
> +    width: '1.938rem',
create nested style for paper. Put all the styles in there and use that

2022-03-21 14:20 UTC, sss-bct commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.stories.tsx
> +import { blue } from '@mui/material/colors'
Removed

2022-03-21 14:21 UTC, sss-bct commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.spec.js
> +  it('should render a color and call onChange when clicked', () => {
Separated  now..

2022-03-21 14:35 UTC, sss-bct commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.spec.js
> +    expect(colorSelector).toBeVisible()
Included

2022-03-21 14:39 UTC, sss-bct commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.tsx
> +    width: '1.938rem',
Followed your existing approach.

2022-03-21 15:48 UTC, kibo-sushant commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.tsx
> +}
**Using Arrow functions over normal one**
instead of export default function KiboColorPicker
Prefer export default KiboColorPicker = ()=> {}

**Using right TypeScript types**
Instead of colors?: Array<string>
Prefer colors?: string[]

**Avoid hard coding**
React.useState('#fff')
Do we need default selectedColor?

**Use Types**
Use proper types along with State and events
React.useState('#fff')

**Group the code**
Always group the related code and provide spacing between each group.
Ex. give space between below two lines.

const [selectedColor, changeSelectedColor] = React.useState('#fff')
const handleChange = (color: string) => {

**Use meaningful names**
Instead of  {colors.map((each, i) => {
Prefer {colors.map((color, index) => {

Instead of [selectedColor, changeSelectedColor]
Prefer [selectedColor, setSelectedColor]

Instead of = React.useState('#fff')
prefer useState('')


**Should consider if there will by many color (for mobile)
On color hover its should show pointer as cursor (hand)
Inner part of loop should be separate component
**

2022-03-21 15:48 UTC, kibo-sushant commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.stories.tsx
> +export const NoColor = Template.bind({})
Instead of VariantColorSector make the title as ColorSelector
 Stories should be
  Common
  With Selected

2022-03-21 15:48 UTC, kibo-sushant commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.spec.js
> +})
**Remove  noColorSetup()**
Instead of that pass arguments to setup()

As per me there should be only two or three tests
**should render component only when color presents**
 test without passing colors
 test with colors
 test length of the component
 
**should call eventHanlder when user selects color**
 instead of userEvent.click(colorOptions[0])
 provide data-testId={color}
 get perticular color and click on it.
 Apart from expect(onChangeMock).toHaveBeenCalled()
 also check whether same color has been passed along with  onChange(color) or not?

2022-03-23 12:45 UTC, sss-bct commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.tsx
> +}
All are taken care. now we are not handling state so this is no longer present.

2022-03-23 12:46 UTC, sss-bct commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.stories.tsx
> +export const NoColor = Template.bind({})
Taken care. All are shown in common only i.e. with selected, disabled, enabled etc.

2022-03-23 12:48 UTC, sss-bct commented on components/product/ProductVariantColorSelector/ProductVariantColorSelector.spec.js
> +})
All are updated as per the implementation with Product Options.

2022-03-30 22:01 UTC, kibo-kevinwatts requested changes

2022-03-30 22:01 UTC, kibo-kevinwatts commented on components/product/ColorSelector/ColorSelector.tsx
> +          key={index}
avoid using index as key

2022-03-31 14:29 UTC, sss-bct commented on components/product/ColorSelector/ColorSelector.tsx
> +          key={index}
Fixed.

2022-04-01 18:18 UTC, kibo-chandradeeptalaha commented on components/product/ColorSelector/ColorSelector.tsx
> +    borderColor: `${grey[300]}`,
we can use "grey[300]" also. Can you please check ?

2022-04-01 18:18 UTC, kibo-chandradeeptalaha approved these changes

2022-04-04 05:35 UTC, sss-bct commented on components/product/ColorSelector/ColorSelector.tsx
> +    borderColor: `${grey[300]}`,
I tried but it's not working..

2022-04-04 16:58 UTC, kibo-kevinwatts approved these changes

2022-04-04 16:59 UTC, merged