feat(Delete Subscription): feature/icky-832-My-Account-Delete-Subscription
KiboSoftware/nextjs-storefront pull request #211
Opened 2023-02-01 04:40 UTC by kibo-Kripa

2023-02-06 11:09 UTC, Kibo-TriptiV requested changes
Please take a look.

2023-02-06 11:09 UTC, Kibo-TriptiV commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.tsx
> +    }
Should we have separate buildSubscriptionParam file and build params for all the subscription actions?
Also please take action name from constant file.

2023-02-06 11:09 UTC, Kibo-TriptiV commented on hooks/mutations/useSubscription/useDeleteSubscriptionMutation/useDeleteSubscriptionMutation.ts
> + * @returns 'response?.subscription' which contains next order date when the order will be placed
Something wrong description written for delete subscription.
Also, graphql accepts 3 or 4 params, not only subscriptionId
deleteSubscriptionItem(subscriptionId: String!, subscriptionItemId: String!, updateMode: String, subscriptionReasonInput: SubscriptionReasonInput): Subscription

2023-02-06 11:09 UTC, Kibo-TriptiV commented on __mocks__/stories/subscriptionCollectionMock.ts
> +export const deleteSubscriptionMock: { subscription: SubscriptionReason } = {
Return type of delete subscription is Subscription, should we move it to SubscriptionMock instead SubscriptionCollectionMock file?

2023-02-06 11:09 UTC, Kibo-TriptiV commented on hooks/mutations/useSubscription/useDeleteSubscriptionMutation/useDeleteSubscriptionMutation.ts
> +import { SubscriptionReasonInput } from '@/lib/gql/types'
use type

2023-02-06 22:15 UTC, kibo-Kripa commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.tsx
> +    }
Done

2023-02-06 22:15 UTC, kibo-Kripa commented on hooks/mutations/useSubscription/useDeleteSubscriptionMutation/useDeleteSubscriptionMutation.ts
> + * @returns 'response?.subscription' which contains next order date when the order will be placed
Done

2023-02-06 22:15 UTC, kibo-Kripa commented on __mocks__/stories/subscriptionCollectionMock.ts
> +export const deleteSubscriptionMock: { subscription: SubscriptionReason } = {
Done

2023-02-06 22:16 UTC, kibo-Kripa commented on hooks/mutations/useSubscription/useDeleteSubscriptionMutation/useDeleteSubscriptionMutation.ts
> +import { SubscriptionReasonInput } from '@/lib/gql/types'
done

2023-02-08 07:40 UTC, kibo-sushant commented on hooks/mutations/useSubscription/useDeleteSubscriptionMutation/useDeleteSubscriptionMutation.ts
> + * @module useSkipNextSubscriptionMutation
is this name correct?

2023-02-09 19:33 UTC, kibo-Kripa commented on hooks/mutations/useSubscription/useDeleteSubscriptionMutation/useDeleteSubscriptionMutation.ts
> + * @module useSkipNextSubscriptionMutation
Corrected

2023-02-10 07:37 UTC, Kibo-TriptiV requested changes
PauseSubscription and DeleteSubscription PRs are almost similar, please do changes according to both review comments, if missing anything.

2023-02-10 07:37 UTC, Kibo-TriptiV commented on lib/helpers/buildSubscriptionParams.ts
> +export const buildSubscriptionParams = (subscriptionId: string, subscriptionItemId: string) => {
Not changes as per comment on Pause PR.

2023-02-10 07:37 UTC, Kibo-TriptiV commented on __mocks__/stories/subscriptionMock.ts
> +export const deleteSubscriptionMock: { subscription: SubscriptionReason } = {
Not changes as per comment on Pause PR.

2023-02-10 15:50 UTC, kibo-Kripa commented on lib/helpers/buildSubscriptionParams.ts
> +export const buildSubscriptionParams = (subscriptionId: string, subscriptionItemId: string) => {
Sorry I missed that! Done now

2023-02-10 15:50 UTC, kibo-Kripa commented on __mocks__/stories/subscriptionMock.ts
> +export const deleteSubscriptionMock: { subscription: SubscriptionReason } = {
done

2023-02-10 15:58 UTC, kibo-sushant approved these changes

2023-02-10 16:21 UTC, Kibo-TriptiV approved these changes

2023-02-10 17:19 UTC, merged