feat(pauseSubscription): feature/icky-831-My-Account-Pause-Subscription
KiboSoftware/nextjs-storefront pull request #213
Opened 2023-02-02 20:08 UTC by kibo-Kripa

2023-02-06 11:11 UTC, Kibo-TriptiV requested changes
Please take a look.

2023-02-06 11:11 UTC, Kibo-TriptiV commented on __mocks__/stories/pauseSubscriptionMock.ts
> +export const subscriptionPauseMock: { subscription: SubscriptionReason } = {
Do we need to create separate mock file, can't we use existing SubscriptionMock?

2023-02-06 11:11 UTC, Kibo-TriptiV commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.tsx
> +    }
Should we have separate buildSubscriptionParam file and build param for all the subscription actions?
Also please take action name from constant file.

2023-02-06 11:11 UTC, Kibo-TriptiV commented on hooks/mutations/useSubscription/usePerformSubscriptionAction/usePerformSubscriptionActionMutation.ts
> + * @returns 'response?.subscription' which contains next order date when the order will be placed
Something wrong description written for pause subscription.
Also graphql accepts 2 params, 
performSubscriptionAction(subscriptionId: String!, subscriptionActionInput: SubscriptionActionInput): Subscription

2023-02-06 11:11 UTC, Kibo-TriptiV commented on __mocks__/stories/pauseSubscriptionMock.ts
> +import { SubscriptionReason } from '@/lib/gql/types'
use type

2023-02-06 11:13 UTC, Kibo-TriptiV commented on hooks/mutations/useSubscription/usePerformSubscriptionAction/usePerformSubscriptionActionMutation.ts
> +import { SubscriptionActionInput } from '@/lib/gql/types'
use type

2023-02-07 17:07 UTC, kibo-Kripa commented on __mocks__/stories/pauseSubscriptionMock.ts
> +export const subscriptionPauseMock: { subscription: SubscriptionReason } = {
done

2023-02-07 17:08 UTC, kibo-Kripa commented on __mocks__/stories/pauseSubscriptionMock.ts
> +import { SubscriptionReason } from '@/lib/gql/types'
done

2023-02-07 17:08 UTC, kibo-Kripa commented on hooks/mutations/useSubscription/usePerformSubscriptionAction/usePerformSubscriptionActionMutation.ts
> +import { SubscriptionActionInput } from '@/lib/gql/types'
done

2023-02-08 07:11 UTC, kibo-sushant commented on lib/helpers/buildSubscriptionParams.ts
> +export const buildSubscriptionParams = (subscriptionId: string) => {
should not use generic name, please change the same.

2023-02-08 07:11 UTC, kibo-sushant commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.tsx
> +  buildSubscriptionParams,
should not use generic name.

2023-02-08 07:11 UTC, kibo-sushant commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.spec.tsx
> +  describe('pause-shipment', () => {
shouldn't it be pause-subscription instead of pause-shipment?

2023-02-09 11:24 UTC, kibo-sushant commented on __mocks__/msw/handlers.js
> +    return res(ctx.data(subscriptionPauseMock))
should return entire subscription object (not only {
    actionName: 'Pause',
  }).

2023-02-09 11:24 UTC, kibo-sushant commented on __mocks__/stories/subscriptionMock.ts
> +}
should reuse existing subscriptionMock object, destructor it and modify according to your need.
Same will be applicable to delete Subscription also

2023-02-10 05:19 UTC, kibo-Kripa commented on lib/helpers/buildSubscriptionParams.ts
> +export const buildSubscriptionParams = (subscriptionId: string) => {
done

2023-02-10 05:20 UTC, kibo-Kripa commented on components/my-account/Subscription/SubscriptionItem/SubscriptionItem.tsx
> +  buildSubscriptionParams,
done

2023-02-10 05:20 UTC, kibo-Kripa commented on __mocks__/msw/handlers.js
> +    return res(ctx.data(subscriptionPauseMock))
done

2023-02-10 05:20 UTC, kibo-Kripa commented on __mocks__/stories/subscriptionMock.ts
> +}
done

2023-02-10 07:32 UTC, Kibo-TriptiV approved these changes

2023-02-10 09:52 UTC, merged