feat: icky-810 multiship integration test and fixes
KiboSoftware/nextjs-storefront pull request #216
Opened 2023-02-13 13:56 UTC by kibo-chandradeeptalaha

2023-02-16 10:48 UTC, kibo-sushant requested changes

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/DetailsStep/DetailsStep.spec.tsx
> +    })
should render component
- should verify whether all the items are rendered or not (features section and email input)

should not render sign-into-your-account button
- should verify items those should not be rendered

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.spec.tsx
> +  }) => (
To make code readable separate type/interface and use it

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +  }) => (
To make the code readable separate the type/interface and apply it
Destructor params to next line

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +  }) => (
To make the code readable separate the type/interface and apply it
Destructor params to next line

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +  }) => (
To make the code readable separate the type/interface and apply it
Destructor params to next line

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +        }
To make code readable assign values to one const and use it here

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +    onShippingMethodChange: (shippingMethodCode: string) => void
missing onStoreLocatorClick

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +    onFormStatusChange,
validateForm is missing
should accept children and render it

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +      })
**Test case names are not meaningfull**
should display shipping address(saved in account) radio buttons and select a radio button to select Shipping Methods
should select a shipping address radio button and shippingMethod should be selected

**Missing Testcases**
should able to save new address when user fills the address form and clicks on Save button

**Stories do not display Shipping Methods**

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.stories.tsx
> +// }
Remove unused imports customerAccountCardsMock, userAddressMock

There no is difference between following stories
 WithoutSavedPayment
 WithSavedPayment
 MultiShip

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  CustomerContactCollection,
unused imports MultiShipAddress, CrOrderItem

2023-02-16 10:48 UTC, kibo-sushant commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  }, [checkout?.groupings?.length])
To make the code readable assign result to const and use the const in if
ex.
 const shipItems = checkout?.groupings?.filter((group) => group?.fulfillmentMethod === FulfillmentOptions.SHIP
 if(shipItems.length < 2) setShippingOption(shipToHome)

2023-02-16 10:48 UTC, kibo-sushant commented on components/common/PasswordValidation/PasswordValidation.spec.tsx
> +import theme from '../../../styles/theme'
use @/styles/theme

2023-02-16 10:48 UTC, kibo-sushant commented on components/common/Price/Price.spec.js
> +import theme from '../../../styles/theme'
use @/styles/theme

2023-02-16 10:48 UTC, kibo-sushant commented on components/core/ImageGallery/ImageGallery.stories.tsx
> +import { imageGalleryData } from '../../../__mocks__/stories/imageGalleryDataMock'
use @/__mocks__/stories/imageGalleryDataMock

2023-02-16 10:48 UTC, kibo-sushant commented on components/core/ImageGallery/ImageGallery.spec.js
> +import { imageGalleryData } from '../../../__mocks__/stories/imageGalleryDataMock'
use @/__mocks__/stories/imageGalleryDataMock

2023-02-16 10:48 UTC, kibo-sushant commented on components/layout/RegisterAccount/RegisterAccountDialog/RegistAccountDialog.spec.tsx
> +import { KiboDialogProps } from '../../../common/KiboDialog/KiboDialog'
use @/components/common/KiboDialog/KiboDialog

2023-02-16 10:48 UTC, kibo-sushant commented on components/product/ProductOptionSelect/ProductOptionSelect.spec.js
> +import { productOptionSelectValuesMock } from '../../../__mocks__/stories/productOptionSelectMock'
use @/__mocks__/stories/productOptionSelectMock

2023-02-16 10:48 UTC, kibo-sushant commented on __test__/e2e/integration/checkout/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.spec.tsx
> +jest.mock('next/router', () => require('next-router-mock'))
No need of this, as its already defined in jest.setup

2023-02-16 10:48 UTC, kibo-sushant commented on __test__/e2e/integration/checkout/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.spec.tsx
> +        })
**1) Define all the static data at top and use it whenever is required with server.use 
  (To make the code readable)**
ex.
  const getMultiShipCheckoutData = []
  const getCheckoutShippingMethods = []
  ...
 
  server.use(
    graphql.query('getMultiShipCheckout', (_req, res, ctx) => res( ctx.data({...getMultiShipCheckoutData }) ))
  )

**2) To many nested describe blocks.**
   Are we handling For UnAuthenticated user? If not then no need of  describe('Authenticated user')

 describe('[integration] MultiShipCheckoutTemplate', () => {
  describe('Authenticated user', () => {
    describe("user doesn't have any saved addresses", () => {
      describe('checking out for one single ship to home and one pickup in store item', () => {
	 it('should handle the checkout flow', async () => {
      describe('checking out for more than one single ship to home', () => {
	 it('should handle checkout flow', async () => {

**3) should convert function to corresponding testcases** @kibo-kevinwatts , your thoughts please.
ex. 
 should activate Shipping step when user fills the Details Step and Clicks on go-to-shipping button
 should activate Payment step when user fills the Shipping Step and Clicks on go-to-payment button
 ...
 ...

2023-02-16 10:52 UTC, kibo-sushant requested changes

2023-02-16 10:52 UTC, kibo-sushant commented on components/checkout/OrderReview/OrderReview.tsx
> +                <Typography variant="body1">{paymentMethod?.expiry}</Typography>
unused variable 
 const storeLocations = storeLocationGetters.getLocations(locations as Maybe<Location>[])

2023-02-17 17:53 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.stories.tsx
> +// }
Done

2023-02-17 17:53 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  CustomerContactCollection,
Done

2023-02-17 17:53 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.tsx
> +  }, [checkout?.groupings?.length])
Done

2023-02-17 17:53 UTC, kibo-chandradeeptalaha commented on components/common/PasswordValidation/PasswordValidation.spec.tsx
> +import theme from '../../../styles/theme'
Done

2023-02-17 17:53 UTC, kibo-chandradeeptalaha commented on components/common/Price/Price.spec.js
> +import theme from '../../../styles/theme'
Done

2023-02-17 17:53 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.stories.tsx
> +import { imageGalleryData } from '../../../__mocks__/stories/imageGalleryDataMock'
Done

2023-02-17 17:53 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.spec.js
> +import { imageGalleryData } from '../../../__mocks__/stories/imageGalleryDataMock'
Done

2023-02-17 17:53 UTC, kibo-chandradeeptalaha commented on components/layout/RegisterAccount/RegisterAccountDialog/RegistAccountDialog.spec.tsx
> +import { KiboDialogProps } from '../../../common/KiboDialog/KiboDialog'
Done

2023-02-17 17:53 UTC, kibo-chandradeeptalaha commented on components/product/ProductOptionSelect/ProductOptionSelect.spec.js
> +import { productOptionSelectValuesMock } from '../../../__mocks__/stories/productOptionSelectMock'
Done

2023-02-17 17:54 UTC, kibo-chandradeeptalaha commented on __test__/e2e/integration/checkout/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.spec.tsx
> +jest.mock('next/router', () => require('next-router-mock'))
Done

2023-02-17 17:54 UTC, kibo-chandradeeptalaha commented on __test__/e2e/integration/checkout/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.spec.tsx
> +        })
1. Done.
2. Done

2023-02-17 19:44 UTC, kibo-chandradeeptalaha commented on components/checkout/MultiShippingStep/MultiShippingStep.spec.tsx
> +  }) => (
Done

2023-02-17 19:44 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +  }) => (
Done

2023-02-17 19:45 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +  }) => (
Done

2023-02-17 19:45 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +  }) => (
Done

2023-02-17 19:45 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +    onFormStatusChange,
Done

2023-02-17 19:45 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +      })
Test case name changed.

Missing test case name changed: Handled in Integration test.

2023-02-20 07:39 UTC, kibo-chandradeeptalaha commented on components/checkout/DetailsStep/DetailsStep.spec.tsx
> +    })
Already covered

2023-02-20 07:41 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +        }
Done

2023-02-20 07:44 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +    onShippingMethodChange: (shippingMethodCode: string) => void
feature not implemented yet. Need separate ticket for this.

2023-02-20 07:46 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.spec.tsx
> +      })
@kibo-sushant  Stories do not display Shipping Methods // any specific scenario ?

2023-02-20 07:50 UTC, kibo-chandradeeptalaha commented on components/checkout/OrderReview/OrderReview.tsx
> +                <Typography variant="body1">{paymentMethod?.expiry}</Typography>
Removed

2023-02-21 15:24 UTC, kibo-sushant approved these changes

2023-03-14 18:45 UTC, kibo-kevinwatts approved these changes

2023-03-14 20:17 UTC, merged