feat(image-gallery): mobile and desktop Gallery component with stories and tests
KiboSoftware/nextjs-storefront pull request #22
Opened 2022-03-24 11:40 UTC by kibo-chandradeeptalaha

2022-03-24 20:23 UTC, kibo-kevinwatts requested changes

2022-03-24 20:23 UTC, kibo-kevinwatts commented on components/core/ImageGallery/ImageGallery.tsx
> +                    key={i}
avoid using index for key

2022-03-24 20:23 UTC, kibo-kevinwatts commented on components/core/ImageGallery/ImageGallery.tsx
> +                      alt={`kibo-image-thumbnail-${i}`}
should use altText as a prop, check the type ProductImage

2022-03-24 20:23 UTC, kibo-kevinwatts commented on components/core/ImageGallery/ImageGallery.tsx
> +                      alt="selected-image"
should use altText from ProductImage

2022-03-24 20:23 UTC, kibo-kevinwatts commented on components/core/ImageGallery/ImageGallery.tsx
> +    down: images?.length > 4,
can this ( 4 )  be configured as prop?

2022-03-24 20:23 UTC, kibo-kevinwatts commented on components/core/ImageGallery/ImageGallery.stories.tsx
> +Zoomed.args = {
Add two stories showing 1 item and no images

2022-03-25 17:09 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.tsx
> +                    key={i}
Done

2022-03-25 17:09 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.tsx
> +                      alt={`kibo-image-thumbnail-${i}`}
Done

2022-03-25 17:09 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.tsx
> +                      alt="selected-image"
Done

2022-03-25 17:09 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.tsx
> +    down: images?.length > 4,
Yes. Configured

2022-03-25 17:09 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.stories.tsx
> +Zoomed.args = {
Done

2022-03-30 22:08 UTC, kibo-kevinwatts commented on components/core/ImageGallery/ImageGallery.tsx
> +          <Typography variant="body1">Pinch Image to Zoom</Typography>
Pinch image to Zoom should be a prop and not hardcoded

2022-03-31 05:40 UTC, kibo-sushant commented on components/core/ImageGallery/ImageGallery.tsx
> +export default ImageGallery
**Using TypeScript**
Instead of useRef<HTMLDivElement>()
use useRef<HTMLDivElement | null>(null)

**For Code readability**
1. Instead of inline destructiring, destrucre it in next line

2. Instead of using && use 'If condition' in below case
if (dir === 'left') {
  selectedImage.index !== images.length - 1 **&&**
	setSelectedImage({
	  image: images[selectedImage.index + 1],
	  index: selectedImage.index + 1,
	})
} 

**Avoid Hardcoding**
1. Instead of hardcoding Image widths and other numbers like 136, 119 at to many places
define constant at the top and reuse it  

**Meaningful naming conventions**
1. instead of initialThumbnailDisplayCount use thumbnailDisplayCount

**Other**
const [selectedImage, setSelectedImage] = useState({
    image: images[0],
    index: 0,
  })
Instead of storing both image and Index, we can just store selectedIndex and find out corresponding image

2022-03-31 19:09 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.tsx
> +          <Typography variant="body1">Pinch Image to Zoom</Typography>
As this is the button text and we are using it only here, I think this may not be a prop but I have added localization for this.

2022-03-31 19:09 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.tsx
> +export default ImageGallery
Resolved

2022-04-01 14:41 UTC, kibo-sushant approved these changes

2022-04-04 19:04 UTC, kibo-kevinwatts approved these changes

2022-04-05 07:22 UTC, kibo-sushant approved these changes

2022-04-05 12:23 UTC, merged