feat: handling shipping step in checkout for only BOPIS items
KiboSoftware/nextjs-storefront pull request #225
Opened 2023-03-15 09:06 UTC by kibo-chandradeeptalaha

2023-03-20 08:15 UTC, kibo-sushant commented on __test__/e2e/integration/checkout/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.spec.tsx
> +  // expect(within(personalDetailsSection).getByText(checkoutData.email as string)).toBeVisible()
remove unwanted code

2023-03-20 08:15 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.tsx
> +      console.log(stepStatus, isAddingNewPayment)
delete console

2023-03-20 08:15 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.tsx
> +      console.log(stepStatus, isAddingNewPayment)
delete console

2023-03-20 10:16 UTC, Kibo-TriptiV requested changes
Please check minor review comments

2023-03-20 10:16 UTC, Kibo-TriptiV commented on __test__/e2e/integration/checkout/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.spec.tsx
> +    it.only('should handle the checkout flow', async () => {
Remove only

2023-03-20 10:16 UTC, Kibo-TriptiV commented on components/checkout/MultiShippingStep/MultiShippingStep.spec.tsx
> +    checkoutId: 'test-checkout-id-1' as string,
Why we have added test-checkout-id-1, give proper checkout id in spec as well.

2023-03-20 10:16 UTC, Kibo-TriptiV commented on components/common/ProductItem/ProductItem.tsx
> +  hideChangeStore?: boolean
Naming conventions should be positive, instead hide use isShowChangeStore.

2023-03-20 15:46 UTC, kibo-chandradeeptalaha commented on __test__/e2e/integration/checkout/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.spec.tsx
> +  // expect(within(personalDetailsSection).getByText(checkoutData.email as string)).toBeVisible()
Updated

2023-03-20 15:47 UTC, kibo-chandradeeptalaha commented on components/common/ProductItem/ProductItem.tsx
> +  hideChangeStore?: boolean
updated

2023-03-21 05:56 UTC, kibo-sushant commented on __test__/e2e/integration/checkout/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.spec.tsx
> +  // expect(within(personalDetailsSection).getByText(checkoutData.email as string)).toBeVisible()
still I can see commented code

2023-03-21 22:05 UTC, kibo-kevinwatts approved these changes

2023-03-21 22:05 UTC, kibo-kevinwatts commented on components/common/ProductItem/ProductItem.tsx
> +    isShowChangeStore,
I suggest renaming prop to "showChangeStoreLink", its currently a little confusing

2023-03-22 02:26 UTC, kibo-sushant approved these changes

2023-03-22 12:06 UTC, kibo-chandradeeptalaha commented on components/common/ProductItem/ProductItem.tsx
> +    isShowChangeStore,
Done

2023-03-22 12:58 UTC, Kibo-TriptiV approved these changes

2023-03-22 12:58 UTC, merged