feat: Loading buttons and CartItem delete transition added
KiboSoftware/nextjs-storefront pull request #228
Opened 2023-03-20 07:51 UTC by kibo-chandradeeptalaha

2023-03-20 08:44 UTC, kibo-sushant commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +      setShowLoadingButton(false)
I think no need of creating separate state
we can use createMultiShipCheckoutFromCart.isLoading directly.

2023-03-20 08:44 UTC, kibo-sushant commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +    })
use addToCart.isLoading instead of manually switching loading on and off

2023-03-20 08:44 UTC, kibo-sushant commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +    })
can useWishList return isLoading state instead of manually switching loading on and off here

2023-03-20 08:44 UTC, kibo-sushant commented on components/cart/CartItemList/CartItemList.tsx
> +          // orientation="horizontal"
remove commented code

2023-03-20 15:09 UTC, kibo-chandradeeptalaha commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +      setShowLoadingButton(false)
Not exactly. We need to wait for the route to change as well. Hence keeping the separate state.

2023-03-20 15:09 UTC, kibo-chandradeeptalaha commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +    })
Done

2023-03-20 15:09 UTC, kibo-chandradeeptalaha commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +    })
Done

2023-03-20 15:10 UTC, kibo-chandradeeptalaha commented on components/cart/CartItemList/CartItemList.tsx
> +          // orientation="horizontal"
Done

2023-03-21 21:59 UTC, kibo-kevinwatts approved these changes

2023-03-21 21:59 UTC, kibo-kevinwatts commented on styles/theme.ts
> +import type {} from '@mui/lab/themeAugmentation'
what is this empty import?

2023-03-22 02:25 UTC, kibo-sushant approved these changes

2023-03-22 02:52 UTC, kibo-sushant requested changes

2023-03-22 02:52 UTC, kibo-sushant commented on hooks/mutations/useCustomerAddressMutations/useDeleteCustomerAddressMutation.ts
> +        queryClient.setQueryData(customerAccountContactsKeys.all, context?.previousAddresses)
1) newAddresses should be previousAddresses - current Addresss (why are we ...previousAddresses and how its working?)

2) While optimistically updating new value we are using "customerAccountContactsKeys.addressById" as query Key,
where as on error we are using "customerAccountContactsKeys.all" 

we should use either one of them (I think customerAccountContactsKeys.addressById is correct one ), not both.

2023-03-22 05:58 UTC, kibo-chandradeeptalaha commented on styles/theme.ts
> +import type {} from '@mui/lab/themeAugmentation'
This is MUI specific in order to override lab components from theme

2023-03-22 09:21 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useCustomerAddressMutations/useDeleteCustomerAddressMutation.ts
> +        queryClient.setQueryData(customerAccountContactsKeys.all, context?.previousAddresses)
Done

2023-03-22 12:59 UTC, kibo-sushant approved these changes

2023-03-22 13:07 UTC, Kibo-TriptiV approved these changes

2023-03-23 09:56 UTC, merged