feat: refactored login code
KiboSoftware/nextjs-storefront pull request #229
Opened 2023-03-21 06:29 UTC by kibo-sushant

2023-03-21 11:37 UTC, kibo-chandradeeptalaha commented on context/AuthContext.tsx
> +import { removeClientCookie } from '@/lib/helpers/cookieHelper'
use index file

2023-03-23 10:09 UTC, Kibo-TriptiV approved these changes

2023-03-23 19:38 UTC, kibo-chandradeeptalaha requested changes
please check

2023-03-23 19:39 UTC, kibo-chandradeeptalaha approved these changes

2023-05-09 19:48 UTC, kibo-kevinwatts approved these changes
changes approved, 
@kibo-sushant please resolve conflicts

2023-06-07 07:32 UTC, merged