chore: refactored hooks name
KiboSoftware/nextjs-storefront pull request #231
Opened 2023-03-22 12:35 UTC by Kibo-TriptiV

2023-03-23 12:28 UTC, kibo-chandradeeptalaha requested changes
Please take a look

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.tsx
> +  const updateCheckoutShippingInfo = useUpdateOrderShippingInfo()
change this to updateOrderShippingInfo

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Checkout/CheckoutHeader.tsx
> +  const { data: checkout } = useGetCurrentOrder({
change `{ data : checkout }` to `{ data : order }`

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +  const { createFromCart } = useInitiateOrder()
change createFromCart to initiateOrder

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +  const { createMultiShipCheckoutFromCart } = useInitiateCheckout()
change this to initiate checkout

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +  const updateMultiShipCheckoutPaymentAction = useVoidCheckoutPayment()
change this to voidCheckoutPayment

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +  const createMultiShipCheckoutPaymentAction = useAddCheckoutPayment()
change this to addCheckoutPayment

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/page-templates/MultiShipCheckoutTemplate/MultiShipCheckoutTemplate.tsx
> +  const createOrder = useCreateCheckout()
change this to createCheckout

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +  const { data: checkout } = useGetCurrentOrder({
change this to order

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +  const updateOrderPaymentAction = useVoidOrderPayment()
change this to voidOrderPayment

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +  const createOrderPaymentMethod = useAddOrderPaymentInfo()
change this to addOrderPayment

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on components/page-templates/StandardShipCheckoutTemplate/StandardShipCheckoutTemplate.tsx
> +  const updateCheckoutBillingInfo = useUpdateOrderBillingInfo()
change this to updateOrderBillingInfo

2023-03-23 12:28 UTC, kibo-chandradeeptalaha commented on hooks/mutations/standardCheckout/useUpdateOrderShippingInfo/useUpdateCheckoutShippingInfoMutation.ts
change file name

2023-03-27 05:35 UTC, kibo-chandradeeptalaha approved these changes

2023-03-28 02:09 UTC, kibo-sushant approved these changes

2023-05-09 19:51 UTC, kibo-kevinwatts approved these changes

2023-05-10 13:53 UTC, merged