Task/sync latest
KiboSoftware/nextjs-storefront pull request #238
Opened 2023-06-20 13:43 UTC by Kibo-TriptiV

2023-06-30 13:36 UTC, kibo-chandradeeptalaha approved these changes

2023-06-30 13:36 UTC, kibo-geetanshuchhabra approved these changes

2023-07-03 20:07 UTC, kibo-kevinwatts requested changes

2023-07-03 20:07 UTC, kibo-kevinwatts commented on context/RQNotificationContext/RQNotificationContext.tsx
> +  if (context === undefined) console.log('Something went wrong')
we want to throw error in this case

2023-07-03 20:07 UTC, kibo-kevinwatts commented on context/ModalContext.tsx
> +  if (context === undefined) showSnackbar('Modal Context not found', 'warning')
we want to throw error if no context, dont show error message to shopper

2023-07-03 20:07 UTC, kibo-kevinwatts commented on context/HeaderContext.tsx
> +  if (context === undefined) showSnackbar('Header Context not found', 'warning')
we want to throw error if no context, dont show error message to shopper

2023-07-03 20:07 UTC, kibo-kevinwatts commented on context/CheckoutStepContext/CheckoutStepContext.tsx
> +    showSnackbar('CheckoutStep Context not found', 'warning')
we want to throw error if no context, dont show error message to shopper

2023-07-03 20:07 UTC, kibo-kevinwatts commented on context/AuthContext.tsx
> +  if (context === undefined) showSnackbar('Auth Context not found', 'warning')
we want to throw error if no context, dont show error message to shopper

2023-07-03 20:07 UTC, kibo-kevinwatts commented on components/checkout/CheckoutUITemplate/CheckoutUITemplate.tsx
> +      <ReCaptchaProvider reCaptchaKey={reCaptchaKey}>
Whether or not recaptcha is used should be configurable view the next config

2023-07-03 20:07 UTC, kibo-kevinwatts commented on components/checkout/CheckoutUITemplate/CheckoutUITemplate.tsx
> +  if (!showCheckoutSteps) {
The template here should not be responsible for directing to the Confirmation Page.
The getServerSideProps route handler should do this AND the successful action on Order Placement

2023-07-03 20:07 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep.tsx
> +    await reTokenizeCreditCardPayment(card, pciHost, apiHost)
why is retokenize a new fn instead of reusing existing tokenize fn?

2023-07-03 20:07 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep.tsx
> +    'savedPaymentBillingDetails====================================================',
remove console log

2023-07-03 20:07 UTC, kibo-kevinwatts commented on components/checkout/StandardShippingStep/StandardShippingStep.tsx
> +  const submitFormWithRecaptcha = ({ contact }: { contact: CrContact }) => {
Whether or not to use Recaptcha should be configurable.
I also do not think recaptcha is needed for all checkout interactions, Payment step only or Order placement should suffice.

2023-07-03 20:07 UTC, kibo-kevinwatts commented on lib/getters/checkoutGetters.ts
> +  return checkout.itemLevelProductDiscountTotal + checkout?.orderLevelProductDiscountTotal
revert any / all changes where we are doing client side calculation on order values 
Or use a property that exists on the object from the server
for example here, use `checkout.discountedSubtotal`

2023-07-03 20:07 UTC, kibo-kevinwatts commented on lib/getters/orderGetters.ts
> +  return (order?.handlingTotal as number) + (order?.shippingTotal as number) || 0
revert any / all changes where we are doing client side calculation on order values
Or use a property that exists on the object from the server

2023-07-03 20:07 UTC, kibo-kevinwatts commented on lib/getters/orderGetters.ts
> +    : format(new Date(order?.auditInfo?.createDate), DateFormat.DATE_FORMAT)
Don't use the auditinfo create date for this. They are not the same

2023-07-03 20:07 UTC, kibo-kevinwatts commented on lib/getters/orderGetters.ts
> +const getOrderPayments = (order: CrOrder) => {
Where is this being used?
"getOrderPayments" but filtering on "new" is not consistent with the name "getOrderPayments". 
There are other statuses for payments (after submit)

2023-07-03 20:07 UTC, kibo-kevinwatts commented on lib/getters/productGetters.ts
> +  const occasionAttributeFQN = publicRuntimeConfig?.occasionAttributeFQN?.toLowerCase()
remove the "occasion" reference

2023-07-03 20:07 UTC, kibo-kevinwatts commented on lib/getters/productGetters.ts
> +      (prop) => prop.value !== 'false' && prop.attributeFQN?.toLowerCase() === occasionAttributeFQN
remove occasion reference

2023-07-03 20:07 UTC, kibo-kevinwatts commented on lib/getters/productGetters.ts
> +    availabilityAttribute: getProductAvailability(product?.inventoryInfo as ProductInventoryInfo),
rename "availabilityAttribute", "attribute" has a very specific meaning with products on our platform and this isn't an attribute

2023-07-03 20:07 UTC, kibo-kevinwatts commented on lib/gql/queries/get-orders.ts
> +        auditInfo {
why the use of audit info?

2023-07-03 20:07 UTC, kibo-kevinwatts commented on src/pages/_document.tsx
> +            dangerouslySetInnerHTML={{
remove this

2023-07-03 20:07 UTC, kibo-kevinwatts commented on src/pages/product/[...productSlug].tsx
> +    routeHandle(router, product)
lets discuss this on our next standup

2023-07-04 05:37 UTC, Kibo-TriptiV commented on components/checkout/CheckoutUITemplate/CheckoutUITemplate.tsx
> +  if (!showCheckoutSteps) {
Not clarified, lets discuss in standup

2023-07-04 05:42 UTC, Kibo-TriptiV commented on lib/getters/orderGetters.ts
> +const getOrderPayments = (order: CrOrder) => {
lets discuss on standup

2023-07-04 05:42 UTC, Kibo-TriptiV commented on lib/getters/orderGetters.ts
> +  return (order?.handlingTotal as number) + (order?.shippingTotal as number) || 0
lets discuss on standup

2023-07-04 07:52 UTC, kibo-chandradeeptalaha commented on src/pages/_document.tsx
> +            dangerouslySetInnerHTML={{
Done

2023-07-04 07:52 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +    'savedPaymentBillingDetails====================================================',
Done

2023-07-04 07:52 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +    await reTokenizeCreditCardPayment(card, pciHost, apiHost)
Done

2023-07-04 07:52 UTC, kibo-chandradeeptalaha commented on components/checkout/CheckoutUITemplate/CheckoutUITemplate.tsx
> +      <ReCaptchaProvider reCaptchaKey={reCaptchaKey}>
Done

2023-07-04 07:55 UTC, kibo-chandradeeptalaha commented on components/checkout/StandardShippingStep/StandardShippingStep.tsx
> +  const submitFormWithRecaptcha = ({ contact }: { contact: CrContact }) => {
Done

2023-07-04 07:57 UTC, kibo-geetanshuchhabra commented on context/RQNotificationContext/RQNotificationContext.tsx
> +  if (context === undefined) console.log('Something went wrong')
Resolved

2023-07-04 07:58 UTC, kibo-geetanshuchhabra commented on context/ModalContext.tsx
> +  if (context === undefined) showSnackbar('Modal Context not found', 'warning')
Resolved

2023-07-04 07:58 UTC, kibo-geetanshuchhabra commented on context/HeaderContext.tsx
> +  if (context === undefined) showSnackbar('Header Context not found', 'warning')
Resolved

2023-07-04 07:58 UTC, kibo-geetanshuchhabra commented on context/CheckoutStepContext/CheckoutStepContext.tsx
> +    showSnackbar('CheckoutStep Context not found', 'warning')
Resolved

2023-07-04 07:59 UTC, kibo-geetanshuchhabra commented on context/AuthContext.tsx
> +  if (context === undefined) showSnackbar('Auth Context not found', 'warning')
Resolved

2023-07-04 08:00 UTC, kibo-geetanshuchhabra commented on lib/getters/productGetters.ts
> +  const occasionAttributeFQN = publicRuntimeConfig?.occasionAttributeFQN?.toLowerCase()
Resolved

2023-07-04 08:00 UTC, kibo-geetanshuchhabra commented on lib/getters/productGetters.ts
> +      (prop) => prop.value !== 'false' && prop.attributeFQN?.toLowerCase() === occasionAttributeFQN
Resolved

2023-07-04 08:00 UTC, kibo-geetanshuchhabra commented on lib/getters/productGetters.ts
> +    availabilityAttribute: getProductAvailability(product?.inventoryInfo as ProductInventoryInfo),
Resolved

2023-07-04 08:22 UTC, kibo-geetanshuchhabra commented on lib/getters/orderGetters.ts
> +    : format(new Date(order?.auditInfo?.createDate), DateFormat.DATE_FORMAT)
Resolved

2023-07-04 08:22 UTC, kibo-geetanshuchhabra commented on lib/gql/queries/get-orders.ts
> +        auditInfo {
Resolved

2023-07-06 05:33 UTC, kibo-sushant commented on src/pages/product/[...productSlug].tsx
> +    routeHandle(router, product)
currently used serversideProps will change later once any suitable alternative founds

2023-07-06 07:48 UTC, kibo-geetanshuchhabra commented on lib/getters/orderGetters.ts
> +  return (order?.handlingTotal as number) + (order?.shippingTotal as number) || 0
Resolved

2023-07-06 07:49 UTC, kibo-geetanshuchhabra commented on components/checkout/CheckoutUITemplate/CheckoutUITemplate.tsx
> +  if (!showCheckoutSteps) {
Resolved

2023-07-06 07:51 UTC, kibo-geetanshuchhabra commented on lib/getters/checkoutGetters.ts
> +  return checkout.itemLevelProductDiscountTotal + checkout?.orderLevelProductDiscountTotal
Need to discuss.

2023-07-06 08:49 UTC, kibo-geetanshuchhabra commented on lib/getters/orderGetters.ts
> +const getOrderPayments = (order: CrOrder) => {
Resolved

2023-07-07 13:45 UTC, kibo-kevinwatts approved these changes

2023-07-09 08:47 UTC, merged