feat: checkout-address
KiboSoftware/nextjs-storefront pull request #24
Opened 2022-03-30 14:06 UTC by kibo-sushant

2022-03-30 22:39 UTC, kibo-kevinwatts requested changes
nice work!

2022-03-30 22:39 UTC, kibo-kevinwatts commented on styles/theme.ts
> +          //   fontSize: '1.75rem',
delete the commented code

2022-03-30 22:39 UTC, kibo-kevinwatts commented on components/common/KiboTextBox/KiboTextBox.tsx
> +KiboTextBox.displayName = 'KiboTextBox'
do we want to do this? I don't see a lot of value, but I don't see an issue. Just need to decide and be consistent

2022-03-30 22:39 UTC, kibo-kevinwatts commented on components/common/AddressForm/AddressForm.tsx
> +              label={t('save-shipping-address')}
label should be prop (this can be used for both billing and shipping)

2022-03-30 22:39 UTC, kibo-kevinwatts commented on components/common/AddressForm/AddressForm.tsx
> +                <Checkbox onChange={() => setSaveShippingAddress((prevState) => !prevState)} />
remove 'shipping' from setSaveShippingAddress

2022-03-30 22:39 UTC, kibo-kevinwatts commented on components/common/AddressForm/AddressForm.stories.tsx
> +  title: 'Common/AddressForm',
if you add  `argTypes: { onSave: { action: 'clicked' } }` to better integrate your actions with storybook
https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation

2022-03-30 22:39 UTC, kibo-kevinwatts commented on components/common/AddressForm/AddressForm.tsx
> +export interface Contact {
is there a grapqhl Contact type to reuse instead?

2022-03-31 11:59 UTC, kibo-sushant commented on styles/theme.ts
> +          //   fontSize: '1.75rem',
done

2022-03-31 12:01 UTC, kibo-sushant commented on components/common/KiboTextBox/KiboTextBox.tsx
> +KiboTextBox.displayName = 'KiboTextBox'
Actually, I had used forwordref in this component, linter was complaining. To satisfy linter I had used it. But as forwordref is no longer required, I have removed the above code. Resolved.

2022-03-31 12:02 UTC, kibo-sushant commented on components/common/AddressForm/AddressForm.tsx
> +              label={t('save-shipping-address')}
Now passing saveAddressLabel as prop. Resolved.

2022-03-31 12:02 UTC, kibo-sushant commented on components/common/AddressForm/AddressForm.tsx
> +                <Checkbox onChange={() => setSaveShippingAddress((prevState) => !prevState)} />
Resolved

2022-03-31 12:02 UTC, kibo-sushant commented on components/common/AddressForm/AddressForm.stories.tsx
> +  title: 'Common/AddressForm',
Resolved

2022-03-31 12:06 UTC, kibo-sushant commented on components/common/AddressForm/AddressForm.tsx
> +export interface Contact {
We have graphQL Contact type, which have self-referencing _root property  ( _root?: Maybe<Contact> ).
Because of that, we are getting TypeScript validation errors. To avoid I have created Contact interface

2022-04-01 06:21 UTC, kibo-chandradeeptalaha commented on components/common/AddressForm/AddressForm.tsx
> +    countries.map((country) => {
use ?

2022-04-01 09:07 UTC, kibo-sushant commented on components/common/AddressForm/AddressForm.tsx
> +    countries.map((country) => {
For generating country options

2022-04-04 16:44 UTC, kibo-kevinwatts approved these changes

2022-04-04 16:44 UTC, kibo-kevinwatts commented on components/common/AddressForm/AddressForm.tsx
> +export interface Data {
use more descriptive name for "Data"

2022-04-05 06:11 UTC, merged