feat(ATC): modal popup
KiboSoftware/nextjs-storefront pull request #26
Opened 2022-04-04 04:53 UTC by amolpawar-kibo

2022-04-04 10:27 UTC, kibo-chandradeeptalaha requested changes
Modal header font size incorrect
AddToCart not responsive

There are not 2 variants of Modal specified. Please try to develop that.

2022-04-04 10:27 UTC, kibo-chandradeeptalaha commented on components/common/Modal/Modal.tsx
> +      <Button variant="outlined" onClick={handleClickOpen}>
This can be different right ? From where we are calling the modal. This shouldn't be a part of this component. It can be setup in stories maybe ? @kibo-kevinwatts any thoughts ?

2022-04-04 10:27 UTC, kibo-chandradeeptalaha commented on components/AddToCart/AddToCart.tsx
> +          borderColor: `${grey[500]}`,
Can be used string as well. No need for template literal

2022-04-07 07:17 UTC, amolpawar-kibo commented on components/common/Modal/Modal.tsx
> +      <Button variant="outlined" onClick={handleClickOpen}>
Resolved.

2022-04-07 07:27 UTC, kibo-sushant commented on components/AddToCart/AddToCart.tsx
> +export default AddToCart
**TypeScript usage**
(fullfillmentOption: string, subtotal: string, tax: string, total: string) 
I think subtotal, tax and total should be an integer

Instead of using inline types create an interface and use it.

**Use localization**
Instead of hardcoding 'Product Component' use localization

2022-04-07 07:27 UTC, kibo-sushant commented on components/AddToCart/AddToCart.spec.tsx
> +})
Unnecessary describe('Default Add To Cart', () => { statement
UnitTestCases - Should mock children component
IntegrationTestCases - Should write separate integration test without mocking child component

**Unit Test Cases**
should render component

**Integration Test Cases**
Should render component
  verify that it renders the title
  verify that it renders content
  verify that it renders actions
should close modal when user clicks on close icon
should redirect user to Cart page when user clicks on 'GO TO CART' button
should redirect user 'PLP' page when user clicks on 'Continue Shopping'

2022-04-07 07:28 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.tsx
> +          borderColor: `${grey[500]}`,
Resolved

2022-04-07 22:15 UTC, kibo-kevinwatts requested changes

2022-04-07 22:15 UTC, kibo-kevinwatts commented on components/AddToCart/AddToCart.spec.tsx
> +import React from 'react'
rename "Add To Cart" to AddToCartModal or something. Its unclear

2022-04-07 22:15 UTC, kibo-kevinwatts commented on components/AddToCart/AddToCart.stories.tsx
> +  const handleClose = () => updateArgs({ open: !open })
Instead of actually updating the args, configure the handle to work with storybook actions 
https://storybook.js.org/docs/react/essentials/actions

```
component: AddToCart,
argTypes: { onClose: { action: 'clicked close!' } },
```

2022-04-07 22:15 UTC, kibo-kevinwatts commented on components/common/Modal/Modal.common.mocks.tsx
> +export const useArgs = jest.mock('@storybook/client-api', () => {
If you update the stories, I don't think you will need this useArgs mock

onClose mock should be defined in the unit test file

2022-04-07 22:15 UTC, kibo-kevinwatts commented on components/common/Modal/Modal.tsx
> +export default Modal
There is already a "Modal" in MUI
Lets rename this to KiboDialog or something Dialog related since that's what it is.

2022-04-08 04:52 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.tsx
> +        <Typography gutterBottom>Product Component</Typography>
Tripti, have created component in PR https://github.com/KiboSoftware/nextjs-storefront/pull/28 but its not merged so after merging it will replace in this place

2022-04-14 14:05 UTC, amolpawar-kibo commented on components/common/Modal/Modal.tsx
> +export default Modal
Resolved

2022-04-14 14:05 UTC, amolpawar-kibo commented on components/common/Modal/Modal.spec.js
> +})
Resolved.

2022-04-14 14:05 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.tsx
> +export default AddToCart
Resolved.

2022-04-14 14:06 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.spec.tsx
> +})
Resolved.

2022-04-14 14:06 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.tsx
> +            {t('cart-sub-total', { quantity: 2 })}
Resolved

2022-04-14 15:27 UTC, amolpawar-kibo commented on components/common/Modal/Modal.common.mocks.tsx
> +export const useArgs = jest.mock('@storybook/client-api', () => {
Resolved.

2022-04-14 15:28 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.spec.tsx
> +import React from 'react'
Resolved

2022-04-14 15:28 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.tsx
> +    router.push('product/MS-JKT-001')
Resolved.

2022-04-14 15:30 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.tsx
> +            ${subtotal}
Resolved

2022-04-14 15:30 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.tsx
> +          ${total}
Resolved.

2022-04-14 15:31 UTC, amolpawar-kibo commented on components/AddToCart/AddToCart.stories.tsx
> +  const handleClose = () => updateArgs({ open: !open })
Resolved.

2022-04-19 17:17 UTC, kibo-kevinwatts requested changes

2022-04-19 17:17 UTC, kibo-kevinwatts commented on components/add-to-cart-dialog/Actions/Actions.tsx
> +  const continueButtonStyle = {
creating a "styled" definition for all of these styles would be better approach

Prefer "rem" units instead of 'px' for font size in general

Use a theme font variant or set font size globally for buttons

use "grey" from theme config instead of importing material ui

2022-04-19 17:17 UTC, kibo-kevinwatts commented on components/add-to-cart-dialog/Content/Content.tsx
> +  subtotal: number
subtotal, tax, total should be strings

2022-04-19 17:17 UTC, kibo-kevinwatts commented on components/common/KiboDialog/KiboDialog.tsx
> +import { grey } from '@mui/material/colors'
use grey defined in our theme instead of material

2022-04-19 17:17 UTC, kibo-kevinwatts commented on components/add-to-cart-dialog/AddToCartDialog/AddToCartDialog.tsx
> +  const handleAddToCart = () => {
handleAddToCart should be `handleGoToCart`

2022-04-19 17:17 UTC, kibo-kevinwatts commented on components/add-to-cart-dialog/Actions/Actions.tsx
> +  onAddToCart: () => void
`onAddToCart` should be `onGoToCart`

2022-04-20 13:55 UTC, amolpawar-kibo commented on components/add-to-cart-dialog/AddToCartDialog/AddToCartDialog.tsx
> +  const handleAddToCart = () => {
Resolved.

2022-04-20 13:55 UTC, amolpawar-kibo commented on components/common/KiboDialog/KiboDialog.tsx
> +import { grey } from '@mui/material/colors'
Resolved.

2022-04-20 13:56 UTC, amolpawar-kibo commented on components/add-to-cart-dialog/Actions/Actions.tsx
> +  const continueButtonStyle = {
Resolved.

2022-04-26 06:38 UTC, kibo-chandradeeptalaha commented on components/common/KiboDialog/KiboDialog.tsx
> +      {!!Title && (
we don't need !!

2022-04-26 06:38 UTC, kibo-chandradeeptalaha commented on components/common/KiboDialog/KiboDialog.tsx
> +            <StyledIconButton aria-label="close" onClick={onClose}>
change onClose to handleClose

2022-04-26 06:46 UTC, kibo-chandradeeptalaha commented on components/add-to-cart-dialog/Actions/Actions.tsx
> +  color: theme?.palette.grey[500],
Can these be set to global as this style might be reused ?

2022-04-26 06:51 UTC, kibo-chandradeeptalaha requested changes
Please take a look!

2022-04-26 06:51 UTC, kibo-chandradeeptalaha commented on components/add-to-cart-dialog/Content/Content.tsx
> +      <StyledPriceSection>
This section is being used in OrderSummary as well. Can we make this common ? @kibo-kevinwatts what do you think ?

2022-04-26 13:42 UTC, amolpawar-kibo commented on components/common/KiboDialog/KiboDialog.tsx
> +      {!!Title && (
Resolved.

2022-04-26 20:37 UTC, kibo-kevinwatts requested changes

2022-04-26 20:37 UTC, kibo-kevinwatts commented on components/common/ProductItem/ProductItem.tsx
> +                    price={t('currency', { val: price })}
revert this, format price before and pass it as a prop formatted

2022-04-28 20:18 UTC, kibo-kevinwatts approved these changes

2022-04-29 04:29 UTC, kibo-chandradeeptalaha approved these changes

2022-04-29 04:30 UTC, merged