feat: order summary changes including handling charges
KiboSoftware/nextjs-storefront pull request #263
Opened 2023-10-12 13:17 UTC by kibo-chandradeeptalaha

2023-10-16 11:46 UTC, Kibo-TriptiV requested changes
Please check review comments.

2023-10-16 11:46 UTC, Kibo-TriptiV commented on components/common/OrderPrice/OrderPrice.tsx
> +import { Checkout, CrCart, CrOrder } from '@/lib/gql/types'
use type

2023-10-16 11:46 UTC, Kibo-TriptiV commented on components/common/OrderSummary/OrderSummary.tsx
> +import { Checkout, CrCart, CrOrder } from '@/lib/gql/types'
use type

2023-10-16 11:46 UTC, Kibo-TriptiV commented on components/common/OrderPrice/OrderPrice.stories.tsx
> +  },
please add story argument where we can test discount and their impact .

2023-10-16 11:46 UTC, Kibo-TriptiV commented on components/checkout/CheckoutUITemplate/CheckoutUITemplate.tsx
> +    orderPriceDetails: checkout,
Here variable name is different than passing the value. It could be order details or checkout details or something better, as Checkout/Order/Cart are not holding only pricing details.

2023-10-19 10:43 UTC, kibo-sushant approved these changes

2023-10-26 10:36 UTC, kibo-geetanshuchhabra approved these changes

2023-10-26 11:27 UTC, Kibo-TriptiV approved these changes

2023-10-26 12:57 UTC, merged