feat(cart): Cart Edit Action Mobile Component.
KiboSoftware/nextjs-storefront pull request #27
Opened 2022-04-04 11:57 UTC by kibo-geetanshuchhabra

2022-04-04 19:03 UTC, kibo-kevinwatts requested changes

2022-04-05 06:57 UTC, kibo-sushant commented on components/common/Cart/CartEditActionMobile/CartEditActionMobile.tsx
> +}
**Combine the imports**
import Menu from '@mui/material/Menu'
import MenuItem from '@mui/material/MenuItem'

**Use meaningful naming conventions**
ex instead of onClick use onMenuItemSelection or something meaningful
instead of open use isOpen

**Use Arrow functions over normal functions**
export default CartEditAction = (props: CartEditActionProps) => {}

**Follow DRY Principle**
Instead of React.useState and React.MouseEvent, define React at top and just use useState and MouseEvent

**Group Similar code, and use space to differntiate non similar code.**
ex. 
const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null)
const open = Boolean(anchorEl)

const handleClick = ()=>{}

**Follow the sequence mentioned in the Guide**
ex.  Destructure props at the top of the Component instead of the middle 

**Use Localization**
instead of hardcoding aria-label="more", use localization

**Follow single responsibility principle**
In component we are defining Option
also we are calling options in loop - {options.map((option) => (
Separate it out

**Avoid hardCoding**
Instead of maxHeight: ITEM_HEIGHT * 4.5, find out how many options are there in an array and use it

**Use PX over Inch**
Instead of  width: '20ch', use px so that we can easily compare it with UX design

**Reduce Return Signature**
Define style, anchorOrigin, and transformOrigin values at the Top and use it where ever is required


**Other**
Instead of making  anchorEl={anchorEl} dynamic make it static
and onClick just maintain the state of open
ex const [isOpen, setIsOpen] useState<boolean>(false)

2022-04-05 06:57 UTC, kibo-sushant commented on components/common/Cart/CartEditActionMobile/CartEditActionMobile.spec.js
> +})
**Follow DRY principle**
 use setup() function instead of defining render(<CartAction />) again and again

**Use userEvent over fireEvent**

**I think we should have the following test cases**
 should render component
 should show/display popover menu when user click icon
  also test here whether it display all the props or not (as you have done)
 should hide popover menu when user clicks outside icon

2022-04-06 08:31 UTC, kibo-geetanshuchhabra commented on components/common/Cart/CartEditActionMobile/CartEditActionMobile.spec.js
> +  it('should render button', () => {
Resolved

2022-04-06 08:31 UTC, kibo-geetanshuchhabra commented on components/common/Cart/CartEditActionMobile/CartEditActionMobile.tsx
> +}
As discussed with sushant, we are following MUI approach for maintaining the state for anchorEl.
Remaining points are resolved.

2022-04-08 07:55 UTC, kibo-sushant approved these changes

2022-04-13 17:53 UTC, kibo-chandradeeptalaha approved these changes

2022-04-13 21:58 UTC, kibo-kevinwatts approved these changes

2022-04-14 06:24 UTC, merged