feat: icky 1038 preview mode
KiboSoftware/nextjs-storefront pull request #298
Opened 2024-03-28 11:50 UTC by kibo-chandradeeptalaha

2024-04-03 17:14 UTC, kibo-kevinwatts requested changes

2024-04-03 17:14 UTC, kibo-kevinwatts commented on src/pages/api/preview.ts
> +  const redirectTo = (req?.query?.redirect as string) || '/'
add a try { } catch around the inner function, return 500 status with error message in case of exception
add an env variable DISALLOW_KIBO_PREVIEW, if DISALLOW_KIBO_PREVIEW == true dont allow cookies to set
no need for res.end() 
cookies should be http only to prevent client side modification

why only add mz_pricelist to setPreviewData?

2024-04-03 17:14 UTC, kibo-kevinwatts commented on lib/helpers/cookieHelper.ts
> +export const setPreviewPriceListCookie = (cookieValue: string) => {
Why are these helpers not being used by "/api/preview"?

2024-04-03 17:14 UTC, kibo-kevinwatts commented on src/pages/preview.tsx
> +export const getServerSideProps = async (context: GetServerSidePropsContext) => {
whats this page for?

2024-04-03 17:14 UTC, kibo-kevinwatts commented on hooks/custom/useProductDetailTemplate/useProductDetailTemplate.ts
> +      JSON.stringify(currentProduct?.price) !== JSON.stringify(productPriceResponse?.price) ||
this doesnt look right, why manually compare them?
shouldn't we always set it to productPriceResponse?

2024-04-03 17:14 UTC, kibo-kevinwatts commented on hooks/custom/useProductDetailTemplate/useProductDetailTemplate.ts
> +      JSON.stringify(currentProduct?.price) !== JSON.stringify(productPriceResponse?.price) ||
also is this related to preview mode? maybe should be in different pr?

2024-04-03 17:14 UTC, kibo-kevinwatts commented on src/pages/api/clear-preview-mode-cookies.ts
> +  res.end()
no need for res.end

2024-04-03 17:14 UTC, kibo-kevinwatts commented on src/pages/product/[productCode].tsx
> +  productWithPreview?: Product
whats the purpose of productWithPreview?
 should still be the product, front end shouldn't care if its product with preview

2024-04-03 17:14 UTC, kibo-kevinwatts commented on lib/api/util/get-additional-header.ts
> +  //   req?.body?.operationName === 'getCurrentCart' &&
remove commented codes

2024-04-03 17:14 UTC, kibo-kevinwatts commented on src/pages/product/[productCode].tsx
> +  const { data: productWithPreview } = useGetProduct(query)
Why is the hook added here?

2024-04-04 09:43 UTC, kibo-chandradeeptalaha commented on src/pages/api/preview.ts
> +  const redirectTo = (req?.query?.redirect as string) || '/'
Resolved

2024-04-04 09:43 UTC, kibo-chandradeeptalaha commented on lib/helpers/cookieHelper.ts
> +export const setPreviewPriceListCookie = (cookieValue: string) => {
Removed the helpers to handle cookies serverside for preview

2024-04-04 09:43 UTC, kibo-chandradeeptalaha commented on src/pages/preview.tsx
> +export const getServerSideProps = async (context: GetServerSidePropsContext) => {
Removed unused page

2024-04-04 09:44 UTC, kibo-chandradeeptalaha commented on src/pages/api/clear-preview-mode-cookies.ts
> +  res.end()
Removed

2024-04-04 09:44 UTC, kibo-chandradeeptalaha commented on src/pages/product/[productCode].tsx
> +  productWithPreview?: Product
Resolved

2024-04-04 09:44 UTC, kibo-chandradeeptalaha commented on lib/api/util/get-additional-header.ts
> +  //   req?.body?.operationName === 'getCurrentCart' &&
Done

2024-04-05 21:41 UTC, kibo-kevinwatts commented
One of the unit tests is breaking, fix that. otherwise i think we're good to merge

2024-04-10 15:10 UTC, merged