Story/icky 1091 - Cart Takeover - Auth Exchange - Headless Storefront Claim AuthTicket
KiboSoftware/nextjs-storefront pull request #323
Opened 2024-06-19 09:00 UTC by kibo-snehanerekar

2024-06-19 17:35 UTC, kibo-chandradeeptalaha requested changes
Please address these comments.

2024-06-19 17:35 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +            <StoreFinderIcon
1. The condition !isCSR should be enough.
2. wrap these components inside a fragment and put the condition on that fragment.

2024-06-19 17:35 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +                {!isCSR && isCSR === undefined && (
add this check above like 
`!isCSR && navLinks?.map(...`

2024-06-19 17:35 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.stories.tsx
> +      <StoreFinderIcon></StoreFinderIcon>
Why are we adding this here ?

2024-06-19 17:35 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.spec.tsx
> +  xit('should open b2b account request form dialog when user clicks on B2B Account Request link', async () => {
remove x

2024-06-19 17:35 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Mobile/MobileHeader.tsx
> +        {!isCSR && isCSR === undefined && (
!isCSR check should be enough

2024-06-19 17:35 UTC, kibo-chandradeeptalaha commented on components/layout/HamburgerMenu/HamburgerMenu.tsx
> +                  {!isCSR && isCSR === undefined && (
add this check above like
`!isCSR && navLinks?.map(...`

2024-06-19 17:35 UTC, kibo-chandradeeptalaha commented on hooks/queries/cart-takeover/useGetCartTakeover.ts
> + * [Query hook] useGetCartTakeover uses the graphQL query
Please correct this description

2024-06-19 17:35 UTC, kibo-chandradeeptalaha commented on hooks/queries/cart-takeover/useGetCartTakeover.ts
> +    // cacheTime: 0,
remove commented code

2024-06-20 10:47 UTC, kibo-snehanerekar commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +            <StoreFinderIcon
Earlier, the app was not respecting the condition !isCSR on local hence added an undefined one, tested on local again without the undefined condition and it's working fine so removed it.
Wrapped the components in one fragment with a single condition

2024-06-20 10:47 UTC, kibo-snehanerekar commented on components/layout/AppHeader/Common/KiboHeader.tsx
> +                {!isCSR && isCSR === undefined && (
done

2024-06-20 10:47 UTC, kibo-snehanerekar commented on components/layout/AppHeader/Common/KiboHeader.stories.tsx
> +      <StoreFinderIcon></StoreFinderIcon>
removed

2024-06-20 10:47 UTC, kibo-snehanerekar commented on components/layout/AppHeader/Common/KiboHeader.spec.tsx
> +  xit('should open b2b account request form dialog when user clicks on B2B Account Request link', async () => {
removed

2024-06-20 10:47 UTC, kibo-snehanerekar commented on components/layout/AppHeader/Mobile/MobileHeader.tsx
> +        {!isCSR && isCSR === undefined && (
done

2024-06-20 10:47 UTC, kibo-snehanerekar commented on components/layout/HamburgerMenu/HamburgerMenu.tsx
> +                  {!isCSR && isCSR === undefined && (
done

2024-06-20 10:47 UTC, kibo-snehanerekar commented on hooks/queries/cart-takeover/useGetCartTakeover.ts
> + * [Query hook] useGetCartTakeover uses the graphQL query
done

2024-06-20 10:47 UTC, kibo-snehanerekar commented on hooks/queries/cart-takeover/useGetCartTakeover.ts
> +    // cacheTime: 0,
done

2024-06-24 11:19 UTC, kibo-sushant approved these changes

2024-06-24 11:49 UTC, kibo-chandradeeptalaha approved these changes

2024-07-11 05:43 UTC, merged