feat: allow b2b users to be assigned to groups and allow b2b users To approve quotes if they are in correct group
KiboSoftware/nextjs-storefront pull request #324
Opened 2024-07-05 14:35 UTC by kibo-geetanshuchhabra

1.  feat/icky-1140: allow b2b users to be assigned to groups
2.  feat/icky-1141: allow b2b users To approve quotes if they are in correct group

2024-07-08 07:00 UTC, kibo-chandradeeptalaha requested changes
Please take a look

2024-07-08 07:00 UTC, kibo-chandradeeptalaha commented on components/b2b/BuyerQuoteActions/BuyerQuoteActions.tsx
> +                  !quoteGetters.isApproveQuoteDisabled(
prop and function name doesn't match or confusing. 
`quoteGetters.isApproveQuoteDisabled` , this potentially mean if approve quote is disabled or not. We are setting disabled prop to this when approve quote is not disabled.

2024-07-08 07:00 UTC, kibo-chandradeeptalaha commented on components/b2b/User/GroupTransferText/GroupTransferList.tsx
> +        {t('all-groups')}
use something like this inside customList, line no 106
`subheader={
        <ListSubheader component="div" id="nested-list-subheader">
          Nested List Items
        </ListSubheader>
      }`
      
Reference: https://mui.com/material-ui/react-list/#nested-list

2024-07-08 07:00 UTC, kibo-chandradeeptalaha commented on components/b2b/User/GroupTransferText/GroupTransferList.tsx
> +        {t('selected-groups')}
Please Follow above comment

2024-07-08 07:00 UTC, kibo-chandradeeptalaha commented on src/pages/my-account/b2b/users/index.tsx
> +  // const response = await getGroups(context.req as NextApiRequest, context.res as NextApiResponse)
please remove commented code

2024-07-08 07:53 UTC, kibo-sushant commented on lib/api/util/fetch-gql.ts
> +export const gqlFetch = async ({ query, variables }: any, options: any) => {
Why separeate gqlFetch? Can't we use fetcher?

2024-07-08 07:53 UTC, kibo-sushant commented on hooks/mutations/groups/useAddUserToGroup/useAddUserToGroup.ts
> +  const response = await fetch('/api/add-user-to-group', {
We should use GraphQLClient instead of calling api directly?

2024-07-08 07:53 UTC, kibo-sushant commented on hooks/mutations/groups/useAddUserToGroup/useAddUserToGroup.ts
> +const addUserToGroup = async (params: UserGroupParam) => {
Missing return type

2024-07-08 07:53 UTC, kibo-sushant commented on hooks/mutations/groups/useRemoveUserFromGroup/useRemoveUserFromGroup.ts
> +  const response = await fetch('/api/remove-user-from-group', {
use  makeGraphQLClient instead of calling api directly.

2024-07-08 07:53 UTC, kibo-sushant commented on hooks/mutations/groups/useRemoveUserFromGroup/useRemoveUserFromGroup.ts
> +const removeUserFromGroup = async (params: UserGroupParam) => {
return type missing

2024-07-08 07:53 UTC, kibo-sushant commented on src/pages/api/add-user-to-group.ts
> +const handler = async (req: NextApiRequest, res: NextApiResponse) => {
do not mix api and handler code. refer get-groups. also use withLogger.

2024-07-08 07:53 UTC, kibo-sushant commented on src/pages/api/add-user-to-group.ts
> +    const addUserToGroupResponse: any = await gqlFetch(
can we use Fetcher instead of gqlFetch?

2024-07-08 07:53 UTC, kibo-sushant commented on src/pages/api/execute-task.ts
> +const handler = async (req: NextApiRequest, res: NextApiResponse) => {
do not mix api and handler code. refer get-groups. also use withLogger.

2024-07-08 07:53 UTC, kibo-sushant commented on src/pages/api/remove-user-from-group.ts
> +const handler = async (req: NextApiRequest, res: NextApiResponse) => {
do not mix api and handler code. refer get-groups. also use withLogger.

2024-07-08 07:53 UTC, kibo-sushant commented on public/locales/en/common.json
> +  "task-executed-message": "Task Executed successfully!"
update fr file accordingly

2024-07-08 07:53 UTC, kibo-sushant commented on lib/types/B2bTypes.ts
> +}
For consistency purpose either use type or interface. As UserGroupCode is not getting used any were so no need to create separate interface.

2024-07-08 07:53 UTC, kibo-sushant commented on lib/api/handlers/get-groups.ts
> +    return res.status(405).json({ message: 'Method Not Allowed' })
use Translation everywere

2024-07-08 07:53 UTC, kibo-sushant commented on lib/api/handlers/get-groups.ts
> +  let correlationId: any = ''
why any?

2024-07-08 07:53 UTC, kibo-sushant commented on lib/api/handlers/get-groups.ts
> +    const removeUserFromGroupResponse: any = await gqlFetch(
can we use Fetcher instead of gqlFetch?

2024-07-08 07:53 UTC, kibo-sushant commented on components/b2b/User/UserTable/UserTable.tsx
> +                        {!(b2bUserFetching && b2bUser.userId === editUserId) && (
Instead of repeating b2bUserFetching && b2bUser.userId === editUserId twice, create constant and use it

2024-07-08 07:53 UTC, kibo-sushant commented on components/b2b/User/GroupTransferText/GroupTransferList.spec.tsx
> +      expect(rightListItems).toHaveLength(3)
ideally, we should check actual items are moved or not instead of just checking count

2024-07-08 07:53 UTC, kibo-sushant commented on components/b2b/User/GroupTransferText/GroupTransferList.spec.tsx
> +      expect(leftListItems).toHaveLength(3)
ideally, we should check actual items are moved or not instead of just checking count

2024-07-08 07:53 UTC, kibo-sushant commented on components/b2b/User/GroupTransferText/GroupTransferList.spec.tsx
> +      expect(leftListItems).toHaveLength(3)
ideally, we should check actual items are moved or not instead of just checking count

2024-07-08 07:53 UTC, kibo-sushant commented on components/b2b/User/GroupTransferText/GroupTransferList.spec.tsx
> +      expect(rightListItems).toHaveLength(2)
ideally, we should check actual items are moved or not instead of just checking count

2024-07-08 12:42 UTC, kibo-geetanshuchhabra commented on components/b2b/BuyerQuoteActions/BuyerQuoteActions.tsx
> +                  !quoteGetters.isApproveQuoteDisabled(
Resolved

2024-07-08 12:43 UTC, kibo-geetanshuchhabra commented on src/pages/my-account/b2b/users/index.tsx
> +  // const response = await getGroups(context.req as NextApiRequest, context.res as NextApiResponse)
Resolved

2024-07-08 12:43 UTC, kibo-geetanshuchhabra commented on lib/api/util/fetch-gql.ts
> +export const gqlFetch = async ({ query, variables }: any, options: any) => {
Resolved

2024-07-08 12:43 UTC, kibo-geetanshuchhabra commented on hooks/mutations/groups/useAddUserToGroup/useAddUserToGroup.ts
> +  const response = await fetch('/api/add-user-to-group', {
Resolved

2024-07-08 12:43 UTC, kibo-geetanshuchhabra commented on hooks/mutations/groups/useAddUserToGroup/useAddUserToGroup.ts
> +const addUserToGroup = async (params: UserGroupParam) => {
Resolved

2024-07-08 12:43 UTC, kibo-geetanshuchhabra commented on hooks/mutations/groups/useRemoveUserFromGroup/useRemoveUserFromGroup.ts
> +  const response = await fetch('/api/remove-user-from-group', {
Resolved

2024-07-08 12:43 UTC, kibo-geetanshuchhabra commented on hooks/mutations/groups/useRemoveUserFromGroup/useRemoveUserFromGroup.ts
> +const removeUserFromGroup = async (params: UserGroupParam) => {
Resolved

2024-07-08 12:43 UTC, kibo-geetanshuchhabra commented on src/pages/api/add-user-to-group.ts
> +const handler = async (req: NextApiRequest, res: NextApiResponse) => {
Resolved

2024-07-08 12:43 UTC, kibo-geetanshuchhabra commented on src/pages/api/add-user-to-group.ts
> +    const addUserToGroupResponse: any = await gqlFetch(
Resolved

2024-07-08 12:44 UTC, kibo-geetanshuchhabra commented on src/pages/api/execute-task.ts
> +const handler = async (req: NextApiRequest, res: NextApiResponse) => {
Resolved

2024-07-08 12:44 UTC, kibo-geetanshuchhabra commented on src/pages/api/remove-user-from-group.ts
> +const handler = async (req: NextApiRequest, res: NextApiResponse) => {
Resolved

2024-07-08 12:44 UTC, kibo-geetanshuchhabra commented on lib/types/B2bTypes.ts
> +}
Resolved

2024-07-08 12:44 UTC, kibo-geetanshuchhabra commented on lib/api/handlers/get-groups.ts
> +    return res.status(405).json({ message: 'Method Not Allowed' })
Resolved

2024-07-08 12:45 UTC, kibo-geetanshuchhabra commented on lib/api/handlers/get-groups.ts
> +  let correlationId: any = ''
Resolved

2024-07-08 12:45 UTC, kibo-geetanshuchhabra commented on lib/api/handlers/get-groups.ts
> +    const removeUserFromGroupResponse: any = await gqlFetch(
Resolved

2024-07-08 13:38 UTC, Kibo-TriptiV commented on components/b2b/User/GroupTransferText/GroupTransferList.spec.tsx
> +      expect(rightListItems).toHaveLength(2)
done

2024-07-08 13:38 UTC, Kibo-TriptiV commented on components/b2b/User/GroupTransferText/GroupTransferList.spec.tsx
> +      expect(leftListItems).toHaveLength(3)
done

2024-07-08 13:38 UTC, Kibo-TriptiV commented on components/b2b/User/GroupTransferText/GroupTransferList.spec.tsx
> +      expect(leftListItems).toHaveLength(3)
done

2024-07-08 13:38 UTC, Kibo-TriptiV commented on components/b2b/User/GroupTransferText/GroupTransferList.spec.tsx
> +      expect(rightListItems).toHaveLength(3)
done

2024-07-08 13:39 UTC, Kibo-TriptiV commented on components/b2b/User/UserTable/UserTable.tsx
> +                        {!(b2bUserFetching && b2bUser.userId === editUserId) && (
done, handled with ternary operator as b2buser is under map

2024-07-08 13:39 UTC, Kibo-TriptiV commented on public/locales/en/common.json
> +  "task-executed-message": "Task Executed successfully!"
we are not maintaining the fr or other localization file here.

2024-07-08 13:39 UTC, Kibo-TriptiV commented on components/b2b/User/GroupTransferText/GroupTransferList.tsx
> +        {t('selected-groups')}
done

2024-07-08 13:39 UTC, Kibo-TriptiV commented on components/b2b/User/GroupTransferText/GroupTransferList.tsx
> +        {t('all-groups')}
done

2024-07-10 06:42 UTC, kibo-sushant commented on lib/api/handlers/graphqlWithoutUserClaims.ts
> +    const userClaims = await getUserClaimsFromRequest(req, res)
Where are we using this userClaims?

2024-07-10 06:42 UTC, kibo-sushant commented on lib/api/handlers/graphqlWithoutUserClaims.ts
> +class GraphQLError extends Error {
instead of repeating GraphQLError class, take it common and reuse it every were

2024-07-10 06:42 UTC, kibo-sushant commented on hooks/mutations/b2b/quotes/useExecuteTask/useExecuteTask.ts
> +const executeTask = async (params: ExecuteTaskParams) => {
add return type

2024-07-10 06:42 UTC, kibo-sushant commented on hooks/queries/groups/useGetGroups/useGetGroups.ts
> +const getGroups = async () => {
add return type

2024-07-10 09:10 UTC, kibo-sushant approved these changes

2024-07-10 11:17 UTC, kibo-geetanshuchhabra commented on hooks/queries/groups/useGetGroups/useGetGroups.ts
> +const getGroups = async () => {
Resolved

2024-07-10 11:17 UTC, kibo-geetanshuchhabra commented on hooks/mutations/b2b/quotes/useExecuteTask/useExecuteTask.ts
> +const executeTask = async (params: ExecuteTaskParams) => {
Resolved

2024-07-10 11:17 UTC, kibo-geetanshuchhabra commented on lib/api/handlers/graphqlWithoutUserClaims.ts
> +class GraphQLError extends Error {
Resolved

2024-07-10 11:17 UTC, kibo-geetanshuchhabra commented on lib/api/handlers/graphqlWithoutUserClaims.ts
> +    const userClaims = await getUserClaimsFromRequest(req, res)
Resolved

2024-07-11 04:53 UTC, kibo-chandradeeptalaha approved these changes

2024-07-15 12:36 UTC, merged