feat: paypal multiparty changes
KiboSoftware/nextjs-storefront pull request #328
Opened 2024-07-22 08:58 UTC by kibo-sushant

2024-07-23 09:33 UTC, kibo-chandradeeptalaha requested changes
Please take a look at these minor things. Otherwise looks good

2024-07-23 09:33 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  const isPayPalEnabled = useIsPayPalEnabled()
I think the hook name should be usePaypal() that should expose the isEnabled property.

2024-07-23 09:33 UTC, kibo-chandradeeptalaha commented on hooks/custom/useIsPayPalEnabled/useIsPayPalEnabled.tsx
> +          process.env.NEXT_PUBLIC_URL ? process.env.NEXT_PUBLIC_URL : ''
I don't think we need this conditional render, Next should handle that api route calling by itself

2024-07-24 06:02 UTC, kibo-sushant commented on hooks/custom/useIsPayPalEnabled/useIsPayPalEnabled.tsx
> +          process.env.NEXT_PUBLIC_URL ? process.env.NEXT_PUBLIC_URL : ''
We are following same syntax everywhere, Just added it for consistency purpose.
export function makeGraphQLClient(endpoint?: string) {
  endpoint =
    endpoint || `${process.env.NEXT_PUBLIC_URL ? process.env.NEXT_PUBLIC_URL : ''}/api/graphql`
  return new GraphQLClient(endpoint)
}

2024-07-24 06:06 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  const isPayPalEnabled = useIsPayPalEnabled()
As there are multiple hooks related to PayPal (usePayPalBearerToken, useIsPayPalEnabled) hence we cannot keep generic name

2024-07-24 06:57 UTC, Kibo-TriptiV approved these changes

2024-07-24 08:18 UTC, kibo-chandradeeptalaha approved these changes

2024-07-24 08:35 UTC, merged