feat(category): Category Facet
KiboSoftware/nextjs-storefront pull request #34
Opened 2022-04-22 05:20 UTC by kibo-geetanshuchhabra

2022-04-22 05:50 UTC, kibo-chandradeeptalaha commented on components/category/CategoryFacet/CategoryFacet.tsx
> +      <Typography variant="subtitle1" sx={{ color: `${grey[900]}` }}>
use "grey.900"

2022-04-22 09:43 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFacet/CategoryFacet.tsx
> +      <Typography variant="subtitle1" sx={{ color: `${grey[900]}` }}>
Resolved

2022-04-25 12:31 UTC, kibo-chandradeeptalaha commented on components/category/CategoryFacet/CategoryFacet.spec.tsx
> +      <CategoryFacets
Is this CategoryFacet or CategoryFacets ?

2022-04-25 12:32 UTC, kibo-chandradeeptalaha commented on components/category/CategoryFacet/CategoryFacet.stories.tsx
> +    backgroundColor: { control: 'color' },
remove this

2022-04-25 12:33 UTC, kibo-chandradeeptalaha commented on components/category/CategoryFacet/CategoryFacet.tsx
> +    color: '#2b2b2b',
Use theme color

2022-04-25 12:34 UTC, kibo-chandradeeptalaha reviewed
Please take a look

2022-04-25 18:07 UTC, kibo-kevinwatts requested changes

2022-04-25 18:07 UTC, kibo-kevinwatts commented on components/category/CategoryFacet/CategoryFacet.tsx
> +  const initialItemsToShow = 5
allow `initialItemsToShow` to be a prop that defaults to 5

2022-04-25 18:07 UTC, kibo-kevinwatts commented on public/locales/en/category-page.json
> +  "view-more": "View More"
both of these exist inside "common", use that instead

2022-04-25 18:07 UTC, kibo-kevinwatts commented on components/category/CategoryFacet/CategoryFacet.tsx
> +    onCategoryChildrenSelection(`/c/${categoryCode}`)
don't add the `/c/`, just categoryCode

2022-04-26 08:13 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFacet/CategoryFacet.spec.tsx
> +      <CategoryFacets
Resolved

2022-04-26 08:13 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFacet/CategoryFacet.stories.tsx
> +    backgroundColor: { control: 'color' },
Resolved

2022-04-26 08:13 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFacet/CategoryFacet.tsx
> +    color: '#2b2b2b',
Resolved

2022-04-26 08:17 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFacet/CategoryFacet.tsx
> +  const initialItemsToShow = 5
Resolved

2022-04-26 08:17 UTC, kibo-geetanshuchhabra commented on public/locales/en/category-page.json
> +  "view-more": "View More"
Resolved

2022-04-26 08:17 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFacet/CategoryFacet.tsx
> +    onCategoryChildrenSelection(`/c/${categoryCode}`)
Resolved

2022-04-26 20:00 UTC, kibo-kevinwatts approved these changes

2022-04-27 06:59 UTC, kibo-sushant commented on components/category/CategoryFacet/CategoryFacet.tsx
> +export default CategoryFacet
**Using TypeScript**
onCategoryChildrenSelection: (category?: Maybe<string>) => void
const handleCategoryLink = (categoryCode?: Maybe<string>) 

instead of Maybe<string> can we use 'string'?

**Using proper naming conventions**
goBackToPreviousRoute => onBackButtonClick
handleViewMoreClick => onViewMoreClick
valuesLength => childrenLangth
isVisible => isViewMoreVisible
isButtonVisible => isViewMoreButtonVisible

**Unnecessary Code**
 handleViewMoreClick()
 const filtered = categoryFacet.children
No need of above code

2022-04-27 06:59 UTC, kibo-sushant commented on components/category/CategoryFacet/CategoryFacet.spec.tsx
> +})
**should render component**
Should test actual elements are rendered or not, currently, we are missing it.

**Using proper test case names**
should call 'onCategoryChildSelection' when user selects specific category
should call 'onBackButtonClick' when user clicks on 'Back' button
should display all the children when user clicks on 'View More' button

In last testcase we should verify how many items were getting displayed before and after clicking on 'View More' button

2022-04-27 08:57 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFacet/CategoryFacet.spec.tsx
> +})
Resolved

2022-04-27 08:57 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFacet/CategoryFacet.tsx
> +export default CategoryFacet
Resolved

2022-05-04 07:55 UTC, kibo-sushant approved these changes

2022-05-04 07:55 UTC, merged