feat: appHeader implementation
KiboSoftware/nextjs-storefront pull request #35
Opened 2022-04-25 09:48 UTC by kibo-chandradeeptalaha

2022-04-25 17:41 UTC, kibo-kevinwatts requested changes
looks good!

2022-04-25 17:41 UTC, kibo-kevinwatts commented on components/layout/AppHeader/KiboHeader.tsx
> +  navLinks: {
pass these navlinks to the hamburger navigation menu

2022-04-25 17:41 UTC, kibo-kevinwatts commented on components/layout/AppHeader/KiboHeader.tsx
> +                  <HeaderAction title="Find a Store" subtitle="View All" icon={FmdGoodIcon} />
use translations for the three header actions

2022-04-25 19:01 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/KiboHeader.tsx
> +  navLinks: {
Hamburger menu code is commented for now. Will add that once the codes get merged.

2022-04-25 19:01 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/KiboHeader.tsx
> +                  <HeaderAction title="Find a Store" subtitle="View All" icon={FmdGoodIcon} />
Done

2022-04-26 09:57 UTC, amolpawar-kibo commented on components/common/HeaderAction/HeaderAction.tsx
> +      marginX={2}
can we combine marginX &  SX?

2022-04-26 15:37 UTC, kibo-kevinwatts approved these changes

2022-04-26 15:40 UTC, merged