feat: icky-508-checkout-personal-info
KiboSoftware/nextjs-storefront pull request #36
Opened 2022-04-25 12:49 UTC by kibo-sushant

2022-05-04 22:56 UTC, kibo-kevinwatts reviewed
Can we add "Step" to the "Detail", "Payment", etc names?
"ReviewStep" "ShippingStep", "DetailsStep"

Also, let me know what you think about adding this to our storybook setup
https://storybook.js.org/addons/msw-storybook-addon

2022-05-04 22:56 UTC, kibo-kevinwatts commented on pages/_app.tsx
We should init a new query client instance from inside the App scope
https://react-query.tanstack.com/guides/ssr#using-hydration

```
const App = (props: KiboAppProps) => {
     ...
     const [queryClient] = React.useState(() => generateQueryClient())
}
```

2022-05-04 22:56 UTC, kibo-kevinwatts commented on __mocks__/msw/server.js
> +export const server = setupServer(...handlers)
If we add this here and call on jest-setup, how can we customize/mock the responses per test suite?

2022-05-04 22:56 UTC, kibo-kevinwatts commented on __test__/e2e/integration/checkout/Checkout/checkout.spec.tsx
> +  useLoadCheckout: (_checkoutId: string) => ({
these should be jest.mock fn's

2022-05-04 22:56 UTC, kibo-kevinwatts commented on __test__/e2e/integration/checkout/Checkout/checkout.spec.tsx
> +    expect(passwordInput).toHaveValue(password)
Do we need to make any other assertions from clicking the "nextButton"?

2022-05-04 22:56 UTC, kibo-kevinwatts commented on __test__/e2e/integration/checkout/Details/details.spec.tsx
> +describe('[components] Details', () => {
Good coverage in this component!

2022-05-04 22:56 UTC, kibo-kevinwatts commented on public/locales/en/checkout.json
> +  "at-least-eight-characters-long": "at least 8 characters long",
Remove the password related validation messages that exist in common

2022-05-04 22:56 UTC, kibo-kevinwatts commented on react-query/queryClient.ts
> +import React from 'react'
move the react-query folder under `lib`

2022-05-04 23:02 UTC, kibo-kevinwatts commented on components/page-templates/Checkout/Checkout.tsx
> +  const handlePerosnalDetails = (userEnteredPersonalDetails: PersonalDetails) => {
Maybe we just mark this as a TODO for now, it was outside the scope of this ticket
We need to the separate the code thats building the payload, this method is not async, I don't see any 'loading' type indicators and we aren't handling potential errors

2022-05-05 04:58 UTC, kibo-sushant commented on react-query/queryClient.ts
> +import React from 'react'
resolved

2022-05-05 05:03 UTC, kibo-sushant commented on hooks/useUpdatePersonalInfo/useUpdatePersonalInfo.spec.tsx
> +        const response = await updatePersonalInfoMutation.mutateAsync(personalInfo)
mocked using __mocks__ => msw => handlers, but to test whether mock is working as expected or not, need to call real graphQL query/mutation from custom hooks (react-query)

2022-05-05 05:03 UTC, kibo-sushant commented on pages/_app.tsx
Resolved

2022-05-05 05:05 UTC, kibo-sushant commented on __mocks__/msw/server.js
> +export const server = setupServer(...handlers)
We can customize response using Handlers (__mocks__ => msw => handlers)

2022-05-05 05:19 UTC, kibo-sushant commented on __test__/e2e/integration/checkout/Checkout/checkout.spec.tsx
> +    expect(passwordInput).toHaveValue(password)
Ideally, When a user clicks on the Next button (ex. 'Go to Shipping'), we should test/assert whether the next step(ex. shipping) is enabled or not (checking whether the shipping page is in the dom or not). 

Current Flow is
0) User clicks on the next button (ex. 'Go to Shipping')
1) Child component(ex. details) validates itself (form)
2) If form is valid then child component(ex. details) calls save mutation (ex. onPersonalDetailsSave())
3) If a mutation is successful then only the parent activates the next step

Currently, we are using react-hooks-form to validate fields, which return isValid
But every time we call validateForm() from Jest, we are getting isValid as false
And due to that, I am unable to test whether next Step is activated or not ( steps 2 and 3 )

2022-05-05 05:21 UTC, kibo-sushant commented on components/page-templates/Checkout/Checkout.tsx
> +  const handlePerosnalDetails = (userEnteredPersonalDetails: PersonalDetails) => {
As //TODO: is generating code smells, marked the code with // Refactor:

2022-05-05 06:35 UTC, kibo-sushant commented on public/locales/en/checkout.json
> +  "at-least-eight-characters-long": "at least 8 characters long",
Resolved

2022-05-05 09:47 UTC, kibo-sushant commented on __test__/e2e/integration/checkout/Checkout/checkout.spec.tsx
> +  useLoadCheckout: (_checkoutId: string) => ({
Resolved

2022-05-11 21:32 UTC, kibo-kevinwatts requested changes

2022-05-11 21:32 UTC, kibo-kevinwatts commented on components/checkout/DetailsStep/DetailsStep.tsx
> +      ? (passwordValidationRef.current?.validatePassword() as boolean)
Using a ref here on the child component feels like an anti-pattern

2022-05-11 21:32 UTC, kibo-kevinwatts commented on components/page-templates/Checkout/Checkout.tsx
> +import { OrderInput } from '@/lib/gql/types'
`import type`

2022-05-11 21:32 UTC, kibo-kevinwatts commented on components/page-templates/Checkout/Checkout.tsx
> +  const { data: _cartInfo, isLoading: _isLoadFromCartLoading } = useLoadFromCart(cartId)
we don't need both hooks here

2022-05-11 21:32 UTC, kibo-kevinwatts commented on components/page-templates/Checkout/Checkout.tsx
> +      detailsRef.current && detailsRef.current.validateForm()
lets revisit alternatives to using "ref" for this

2022-05-11 21:32 UTC, kibo-kevinwatts commented on components/page-templates/Checkout/Checkout.tsx
> +              Back
use translation

2022-05-11 21:32 UTC, kibo-kevinwatts commented on components/common/PasswordValidation/PasswordValidation.tsx
> +const PasswordValidation = forwardRef<PasswordValidationHandle, PasswordValidationProps>(
move the validation functions into lib, then they can better tested and re-used in other components and avoid calling this component to validate passwords

2022-05-12 06:04 UTC, kibo-sushant commented on components/page-templates/Checkout/Checkout.tsx
> +              Back
Used translation, actually, this code is going to change after Kripas PR merge

2022-05-12 06:04 UTC, kibo-sushant commented on hooks/useLoadCheckout/useLoadCheckout.ts
> +}
Resolved

2022-05-12 06:04 UTC, kibo-sushant commented on hooks/useLoadCheckout/useLoadCheckout.ts
> +    console.log(`${checkoutId ? 'checkoutId' : 'cartId'} response: ${JSON.stringify(response)}`)
Resolved

2022-05-12 06:06 UTC, kibo-sushant commented on hooks/useUpdatePersonalInfo/useUpdatePersonalInfo.ts
> +      queryClient.invalidateQueries([querykeys.LOAD_CHECKOUT])
As we are invalidating cache here it will trigger a hard reload, we can avoid it by updating cache manually

2022-05-12 07:17 UTC, kibo-sushant commented on components/page-templates/Checkout/Checkout.tsx
> +import { OrderInput } from '@/lib/gql/types'
Resolved

2022-05-16 21:59 UTC, kibo-kevinwatts approved these changes
Think i'm good with this

2022-05-16 22:00 UTC, kibo-kevinwatts approved these changes

2022-05-17 03:28 UTC, merged