feat(search): feature/icky-558 search suggestion component
KiboSoftware/nextjs-storefront pull request #37
Opened 2022-04-26 18:05 UTC by TriptiVermaXP

2022-04-27 11:12 UTC, kibo-sushant commented on __test__/e2e/integration/layout/SearchSuggestions/SearchSuggestions.spec.tsx
> +})
instead of defining suggestionSearch  here, we can reuse it from stories

As a part of 'should render component'
should only test whether searchBar is visible or not
Search suggestion dialog should not be visible by default

**Missing Testcases**
'should display user-entered text when a user enters a search term in SearchBar'
'should display search suggestion when a user enters a search term in SearchBar'
'should close search suggestion when user clicks outside search suggestion dialog'
'should clear search when user clicks on SearchBar clear icon'

2022-04-27 11:12 UTC, kibo-sushant commented on components/layout/SearchSuggestions/SearchSuggestions.spec.tsx
> +})
instead of defining suggestionSearch  here we can reuse it from stories

2022-04-27 18:31 UTC, TriptiVermaXP commented on components/layout/SearchSuggestions/SearchSuggestions.spec.tsx
> +})
Done

2022-04-27 18:31 UTC, TriptiVermaXP commented on __test__/e2e/integration/layout/SearchSuggestions/SearchSuggestions.spec.tsx
> +})
Done

2022-04-27 18:31 UTC, TriptiVermaXP commented on components/layout/SearchSuggestions/SearchSuggestions.tsx
> +export default SearchSuggestions
Done

2022-05-03 22:30 UTC, kibo-kevinwatts requested changes

2022-05-03 22:30 UTC, kibo-kevinwatts commented on components/common/SearchBar/SearchBar.tsx
> +  InputProps?: any
should this be `camelCase` instead?

2022-05-03 22:30 UTC, kibo-kevinwatts commented on components/layout/SearchSuggestions/SearchSuggestions.tsx
> +      // ToBe: api call
if the search results are props, should the handler api call also be a prop and called here?

2022-05-05 10:18 UTC, TriptiVermaXP commented on components/common/SearchBar/SearchBar.tsx
> +  InputProps?: any
Done

2022-05-05 10:19 UTC, TriptiVermaXP commented on components/layout/SearchSuggestions/SearchSuggestions.tsx
> +      // ToBe: api call
Will handle during API integration as I have created custom hook to call the mutation.

2022-05-05 11:28 UTC, kibo-sushant commented on components/layout/SearchSuggestions/SearchSuggestions.tsx
> +export default SearchSuggestions
As SearchSuggestions, is the top-level component that will call custom hooks (for fetching search results),
no need for searchSuggestionResult prop

2022-05-05 11:28 UTC, kibo-sushant commented on components/layout/SearchSuggestions/SearchSuggestions.spec.tsx
> +})
**The following test cases are missing**

describe('[components] ListItemTitle',()=>{
 it('should render component', ()=>{})
})

describe('[components] ListItemContent',()=>{
 it('should render component', ()=>{})
 it('should route to another page when user clicks on item', ()=>{})
})

In SearchSuggestions Unit Test Cases
Mock searchBarMock => <input type="textbox" value={searchTerm} onChange={handleSearch}  />
Mock ListItemTitle
Mock ListItemContent

describe('[components] SearchSuggestions',()=>{
 it('should display search suggestion when user enteres the text on search bar', ()=>{})
 it('should display backdrop when search suggustion is opens', ()=>{})
 
 it('should close search suggestion when user clears the search', ()=>{})
 it('should close search suggestion when user clicks on backdrop', ()=>{})
}

2022-05-05 11:28 UTC, kibo-sushant commented on __test__/e2e/integration/layout/SearchSuggestions/SearchSuggestions.spec.tsx
> +})
**Missing TestCases**
 it('should close search suggestion when user clears the search', ()=>{})
 it('should close search suggestion when user clicks on backdrop', ()=>{})

2022-05-09 05:55 UTC, TriptiVermaXP commented on components/product/ProductOptionTextbox/ProductOptionTextBox.spec.js
> +import { productOptionTextBoxMock } from '../../../__mocks__/stories/productOptionTextBoxMock'
Done

2022-05-11 14:37 UTC, TriptiVermaXP commented on public/locales/en/common.json
> +  "categories": "Categories"
Done

2022-05-11 14:37 UTC, TriptiVermaXP commented on hooks/useDebounce/useDebounce.spec.ts
> +})
Done

2022-05-11 14:37 UTC, TriptiVermaXP commented on components/product/ProductOptionTextbox/ProductOptionTextBox.stories.tsx
> +import { productOptionTextBoxMock } from '../../../__mocks__/stories/productOptionTextBoxMock'
Done

2022-05-11 14:38 UTC, TriptiVermaXP commented on components/layout/SearchSuggestions/SearchSuggestions.tsx
> +export default SearchSuggestions
Done. 
Few thing we can handle once react query gets implemented, I have left comments on code for the same.

2022-05-12 08:38 UTC, TriptiVermaXP commented on components/layout/SearchSuggestions/SearchSuggestions.tsx
> +      // ToBe: api call
Handled by custom hook passing the mocked value instead of props.

2022-05-12 08:38 UTC, TriptiVermaXP commented on components/layout/SearchSuggestions/SearchSuggestions.spec.tsx
> +})
Done

2022-05-16 21:38 UTC, kibo-kevinwatts approved these changes

2022-05-16 21:38 UTC, kibo-kevinwatts commented on hooks/useSearchSuggestions/useSearchSuggestions.ts
> +export interface PaymentTypeData {
delete PaymentTypeData

2022-05-18 03:14 UTC, kibo-sushant approved these changes

2022-05-19 11:58 UTC, merged