feat(plp): Implement Category Page using Material UI components and plp skeleton loading.
KiboSoftware/nextjs-storefront pull request #42
Opened 2022-05-09 09:03 UTC by kibo-geetanshuchhabra

2022-05-10 23:33 UTC, kibo-kevinwatts requested changes
Need to add integration tests, especially for different Sort by, view more, facet interactions

2022-05-10 23:33 UTC, kibo-kevinwatts commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +  onChange: (value: string) => void
use more descriptive name for 'onChange'

2022-05-10 23:33 UTC, kibo-kevinwatts commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +    borderTop: '1px solid #c7c7c7',
Add c7c7c7 to theme

2022-05-10 23:33 UTC, kibo-kevinwatts commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +  const [isFilterBy, setFilterBy] = useState<boolean>(false)
Use more descriptive name for "isFilterBy"

2022-05-10 23:33 UTC, kibo-kevinwatts commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                title="Filter By"
use translation

2022-05-10 23:33 UTC, kibo-kevinwatts commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                      <Grid key={product?.link || index} item lg={3} md={4} sm={4} xs={6}>
don't use index as key

2022-05-10 23:33 UTC, kibo-kevinwatts commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                          title={product?.title}
missing `salePrice` and `rating`

2022-05-10 23:33 UTC, kibo-kevinwatts commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                      Showing {initialProductsToShow} out of {products.length} items
use translation string

2022-05-16 09:33 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFilterByMobile/CategoryFilterByMobile.stories.tsx
> +}
Resolved

2022-05-16 09:33 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFilterByMobile/CategoryFilterByMobile.tsx
> +export default CategoryFilterByMobile
Resolved

2022-05-16 09:33 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFilterBy/CategoryFilterBy.spec.tsx
> +})
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFilterBy/CategoryFilterBy.tsx
> +export default CategoryFilterBy
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFacet/CategoryFacet.tsx
> +    borderBottom: '1px solid #c7c7c7',
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                      Showing {initialProductsToShow} out of {products.length} items
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                          title={product?.title}
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                      <Grid key={product?.link || index} item lg={3} md={4} sm={4} xs={6}>
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                title="Filter By"
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +  const [isFilterBy, setFilterBy] = useState<boolean>(false)
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +    borderTop: '1px solid #c7c7c7',
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +  onChange: (value: string) => void
Resolved

2022-05-16 09:39 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFilterBy/CategoryFilterBy.tsx
> +  const { facetList, title, onFilterByClick } = props
Resolved

2022-05-16 09:40 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFilterBy/CategoryFilterBy.tsx
> +export default CategoryFilterBy
Resolved(CategoryFilterBy component has been removed. But we need CategoryFilterByMobile Component to display total product count, clear all and view results button).

2022-05-16 09:40 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                    sx={{ marginRight: '1rem', typography: 'body1', color: 'grey.900' }}
Resolved

2022-05-16 09:40 UTC, kibo-geetanshuchhabra commented on components/filter-by/Facet/Facet.tsx
> +      backgroundColor: '#c7c7c7',
Resolved

2022-05-16 09:40 UTC, kibo-geetanshuchhabra commented on components/category/CategoryFilterBy/CategoryFilterBy.tsx
> +      <Box sx={{ borderBottom: '1px solid #c7c7c7' }}>
Resolved

2022-05-17 19:50 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/ProductListingTemplate/ProductListingTemplate.spec.tsx
> +describe('[component] - Category', () => {
instead of "Category" replace with name of component

2022-05-17 19:52 UTC, kibo-kevinwatts approved these changes
Looks good.
I suggest renaming the parent folder of "Facet", "FacetItem" etc. They are not "Category" specific. Rename to "product-listing"

2022-05-18 03:12 UTC, kibo-sushant approved these changes

2022-05-18 10:47 UTC, merged