feat(promocode): feature/icky 515 and 516 implemented promocode and promocode badge component
KiboSoftware/nextjs-storefront pull request #43
Opened 2022-05-09 19:39 UTC by kibo-Kripa

Implemented promocode component and promocode badge component

2022-05-10 21:09 UTC, kibo-kevinwatts requested changes
@kibo-Kripa Please check this pr, it looks incomplete. There is a large amount of duplication, the promo code component does not use the promo badge and the promo badge has no test coverage.

2022-05-11 11:52 UTC, kibo-sushant commented on components/common/PromoCode/PromoCode.tsx
> +export default PromoCode
**Duplicate Component**
Why we have exactly same compoent with differnt name(PromoCode  PromoCodeBadge)?

**Regarding State**
const promotext = useRef()
const [promo, setPromo] = useState('')
const [promoActive, setPromoActive] = useState(false)
const [promocode, setPromocode] = useState('')

I did not see any reason of using ref(promotext) here. If not needed we can remove it.
No need of promoActive state, we can derive it based on promoCode state

**Unnecessary Prop**
I think no need of promoEnable prop, we can enable/disable the 'Apply' button based on input value/state.

**Using meaningfull naming conventions**
promoEnable 	         => use either isDisabled or isEnabled (no need of this prop)
promotext 		 => use promoRef
handleOnclick 	 => use handleOnClick
handleOnchange      => use handleOnChange
promocode		 => use promoCode
setPromocode	         => use setPromoCode

**Using TypeScript**
For ref and State, instead of inferring the type provide it explicitly
Replace any type with the proper types

**Use Translation**
Instead of hardcoding 'Enter Promo code', 'Apply' use translation

**Using Colors and Fonts**
Instead of hard coding colors #DCDCDC, use the colors from the theme

**Avoid inline large SX code**
Instead of defining large SX code inline define it at top and use it

**Unnecessary Code**
const temp = promo
setPromocode(temp)

No need of temp variable, directly we can pass setPromocode(promo)

**Should use KiboTextBox component instead of MUI TextField, for consistent look and field**

**Flaws and limitations**
1) when promoEnable=true, 'Apply' button is getting disabled and vice versa
2) Currently unable to apply multiple Promo codes
3) Unable to fit component in Mobile View
4) Close Icon position should be at Top right corner

2022-05-11 11:52 UTC, kibo-sushant commented on components/common/PromoCode/PromoCode.spec.js
> +})
Should Mock KiboTextBox

**Missing test cases**
should enable Apply button when user enters text in input textbox
should disable Apply button when user clears input textbox
should able to add single badge
should able to add multiple badges
should remove specific badge when clicks on close icon

I

2022-05-11 14:23 UTC, kibo-Kripa commented on components/common/PromoCode/PromoCode.tsx
> +export default PromoCode
I am still working on this story

2022-05-23 17:48 UTC, closed without merging