feat(PaymentStep): card payment and billing address
KiboSoftware/nextjs-storefront pull request #45
Opened 2022-05-12 13:42 UTC by amolpawar-kibo

2022-05-13 06:36 UTC, kibo-chandradeeptalaha requested changes

2022-05-13 06:36 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +      <StyledHeadings>{t('payment-method')}</StyledHeadings>
Use Typography instead of h2.

2022-05-13 06:36 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +  onCardData: (cardData: CardDetailsProps) => void
Provide meaningful name

2022-05-13 06:36 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +        if (value != undefined) {
can value be null ?

2022-05-13 06:36 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.stories.tsx
> +  onSave: (data: Address) => console.log('called handleSave(data) : ', data),
remove console log

2022-05-13 06:36 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.stories.tsx
> +    console.log('called handleSaveCardPayment(data) : ', data),
remove console log

2022-05-13 06:36 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +const StyledHeadings = styled('h2')(() => ({
use Typography instead of h2

2022-05-13 06:36 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +      <Button variant="contained" onClick={handleSavePayment}>
add color="primary"

2022-05-13 06:36 UTC, kibo-chandradeeptalaha commented on hooks/usePaymentTypes/usePaymentTypes.ts
> +import { publicRuntimeConfig } from '../../next.config'
try to use getConfig to get the publicRuntimeConfig

2022-05-16 04:33 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +export default PaymentStep
As we are going to create smart components, no need of props.
Will get/save this information from/using custom hooks.

isUserLoggedIn: boolean
onSave: (data: Address) => void
onSaveCardPayment: (data: CardPaymentDetails) => void

2022-05-16 04:33 UTC, kibo-sushant commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.spec.tsx
> +})
**Missing Testcases**
should show the required error message when the user focus out the Card number input control
should show the required error message when the user focus out the Expiration Date input control
should show the required error message when the user focus out the cvv input control

should show an "Invalid credit card number" error message when the user enter an invalid credit card
should show a "Provide Expiration Date as MM/YYYY" error message when the user enters an invalid Expiration Date
should show an "Invalid CVV" error message when the user enters an invalid CVV

2022-05-16 04:33 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.spec.tsx
> +})
Should Mock AddressForm as well as CardDetailsForm

2022-05-16 04:33 UTC, kibo-sushant commented on __test__/e2e/integration/checkout/PaymentStep/PaymentStep.spec.tsx
> +})
No need to check isRequired Addressform message, as those are already covered in the Address form integration test

**We should have the following test cases**
should render component
should not display credit card information by default
should display credit card information when the user selects "Credit/Debit Card" as the payment method
should copy "Shipping Address" information when the user selects the "Billing address same as shipping" checkbox

2022-05-16 04:33 UTC, kibo-sushant commented on public/locales/en/common.json
>  }
We should put specific information under checkout.json

2022-05-17 12:39 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +      <StyledHeadings>{t('payment-method')}</StyledHeadings>
reused styled component in multiple places.

2022-05-17 12:46 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +        if (value != undefined) {
value always undefined or string

2022-05-17 12:50 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +      <Button variant="contained" onClick={handleSavePayment}>
This button will be replace with stepper step button

2022-05-17 12:51 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +  }, [isValid, errors, getValues, onCardData])
Resolved.

2022-05-18 05:10 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +      <StyledHeadings>{t('payment-method')}</StyledHeadings>
Resolved. Created Styled component using typography as it used multiple places

2022-05-18 05:10 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +  onCardData: (cardData: CardDetailsProps) => void
Resolved

2022-05-18 05:11 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.stories.tsx
> +  onSave: (data: Address) => console.log('called handleSave(data) : ', data),
Resolved

2022-05-18 05:11 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.stories.tsx
> +    console.log('called handleSaveCardPayment(data) : ', data),
Resolved.

2022-05-18 05:11 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +const StyledHeadings = styled('h2')(() => ({
Resolved. Created Styled component using typography as it used multiple places

2022-05-18 05:12 UTC, amolpawar-kibo commented on public/locales/en/common.json
>  }
Resolved.

2022-05-18 07:00 UTC, amolpawar-kibo commented on hooks/usePaymentTypes/usePaymentTypes.ts
> +import { publicRuntimeConfig } from '../../next.config'
Resolved.

2022-05-23 21:37 UTC, kibo-kevinwatts requested changes

2022-05-23 21:37 UTC, kibo-kevinwatts commented on components/checkout/DetailsStep/DetailsStep.tsx
> +    trigger()
doesn't `handleSubmit` trigger? why manually call it?

2022-05-23 21:37 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +      stepperStatus === 'VALIDATE' && isValid
I think this block can be simplified.
handleSubmit will perform validation and call the correct callback argument


`if(stepperStatus === 'VALIDATE'){
handleSubmit(onValid, onInvalidForm)()
}`

2022-05-23 21:37 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +      stepperStatus === 'VALIDATE' && isValid
I think this block can be simplified.
handleSubmit will perform validation and call the correct callback argument


`if(stepperStatus === 'VALIDATE'){
handleSubmit(onValid, onInvalidForm)()
}`

2022-05-23 21:37 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +import { usePaymentTypes } from '../../../../hooks/usePaymentTypes'
Use alias for instead of long relative paths, '@/hooks'

2022-05-23 21:37 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +import { usePaymentTypes } from '../../../../hooks/usePaymentTypes'
Use alias for instead of long relative paths, '@/hooks'

2022-05-24 07:07 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +import { usePaymentTypes } from '../../../../hooks/usePaymentTypes'
Resolved.

2022-05-24 07:07 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +import { usePaymentTypes } from '../../../../hooks/usePaymentTypes'
Resolved.

2022-05-24 07:07 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +      stepperStatus === 'VALIDATE' && isValid
Resolved.

2022-05-24 07:07 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +      stepperStatus === 'VALIDATE' && isValid
Resolved.

2022-05-26 04:33 UTC, kibo-sushant commented on components/checkout/PaymentStep/CardDetailsForm/CardDetailsForm.tsx
> +export default CardDetailsForm
CardDetailsFormProps -  should group props and callback functions
  Instead of a relative path use an absolute path
  Change CardDetailsProps name to CardData
  Do we need to export useCardSchema
  (formData: any) - remove any
  getCardData - here we are not getting or fetching data, we are forming data, so the name is misleading

2022-05-26 04:33 UTC, kibo-sushant commented on components/page-templates/Checkout/Checkout.tsx
> +          />
const paymentStepParams = {
    countries: ['US', 'AT', 'DE', 'NL'],
    isUserLoggedIn: true,
    saveAddressLabel: 'Save billing address',
  }
  
 Should not hard code countries and  saveAddressLabel
 I think we should not pass countries and saveAddressLabel to shippingStep
 As PaymentStep will be a smart component, we should not pass onSaveAddress and onSaveCardPayment as prop

2022-05-27 07:33 UTC, amolpawar-kibo commented on __test__/e2e/integration/checkout/PaymentStep/PaymentStep.spec.tsx
> +})
Resolved.

2022-05-27 07:35 UTC, amolpawar-kibo commented on public/locales/en/checkout.json
> +  "copy-shipping-address": "Billing address same as shipping"
Resolved

2022-05-27 07:35 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.spec.tsx
> +})
Resolved.

2022-05-27 07:36 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +export default PaymentStep
Resolved.

2022-05-27 07:37 UTC, amolpawar-kibo commented on lib/components/checkout/PaymentStep/CardDetailsForm/index.ts
> +}
Resolved

2022-05-27 07:37 UTC, amolpawar-kibo commented on components/page-templates/Checkout/Checkout.tsx
> +          />
Resolved.

2022-05-31 11:34 UTC, kibo-sushant approved these changes

2022-05-31 22:37 UTC, kibo-kevinwatts requested changes

2022-05-31 22:37 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +
"components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx" is long, can we move back to "components/checkout/PaymentStep/PaymentStep.tsx"? and move "CardDetailsForm" under "/checkout"

2022-06-01 04:32 UTC, amolpawar-kibo commented on components/checkout/DetailsStep/DetailsStep.tsx
> +    trigger()
I have already  resolved it.

2022-06-01 04:51 UTC, amolpawar-kibo commented on lib/components/checkout/PaymentStep/CardDetailsForm/index.ts
> +}
Resolved.

2022-06-01 05:37 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep/PaymentStep.tsx
> +
Resolved.

2022-06-03 09:01 UTC, amolpawar-kibo commented on components/common/AddressForm/AddressForm.tsx
> +    if (stepperStatus === StepStates.VALIDATE) {
Resolved.

2022-06-03 20:03 UTC, kibo-kevinwatts requested changes

2022-06-06 08:36 UTC, amolpawar-kibo commented on public/locales/en/common.json
> +  "invalid-cvv": "Invalid CVV",
Resolved.

2022-06-06 08:36 UTC, amolpawar-kibo commented on components/common/AddressForm/AddressForm.spec.tsx
> +  it('should stepperStatus validate call ', () => {
Resolved. It was written for old logic so removed it.

2022-06-06 08:36 UTC, amolpawar-kibo commented on components/common/AddressForm/AddressForm.spec.tsx
> +  it('should stepperStatus validate call ', () => {
Resolved.

2022-06-08 21:30 UTC, kibo-kevinwatts approved these changes

2022-06-08 21:30 UTC, kibo-kevinwatts approved these changes

2022-06-09 05:42 UTC, kibo-chandradeeptalaha approved these changes

2022-06-09 05:43 UTC, merged