feat(promocode): feature/icky 515 and 516 implemented promocode and promocode badge component
KiboSoftware/nextjs-storefront pull request #53
Opened 2022-05-23 18:06 UTC by kibo-Kripa

2022-05-23 20:52 UTC, kibo-kevinwatts requested changes

2022-05-23 20:52 UTC, kibo-kevinwatts commented on components/common/PromoCodeBadge/PromocodeBadge.spec.js
> +})
Add test cases for the `handleApplyCouponCode` and `onRemoveCouponCode` functionality

2022-05-23 20:52 UTC, kibo-kevinwatts commented on components/common/PromoCodeBadge/PromocodeBadge.spec.js
> +    expect(ApplyButton).not.toHaveClass('Mui-disabled')
Avoid assertions like this `expect(ApplyButton).not.toHaveClass('Mui-disabled')` if for some reason the disabled class name changed, it would give false negatives

instead, test the behavior
* the button click handler should not be called on click
* enter promo code
* click button and handler should be called

2022-05-23 20:52 UTC, kibo-kevinwatts commented on components/common/PromoCode/PromoCode.tsx
> +const PromoCode = ({ isEnabled }: any) => {
don't use "any" type for props, add type declaration to component file

2022-05-23 20:52 UTC, kibo-kevinwatts commented on components/common/PromoCode/PromoCode.tsx
> +export default PromoCode
This component is not being used by the related Promo component, do we need to keep it?

2022-05-23 20:52 UTC, kibo-kevinwatts commented on components/common/PromoCodeBadge/PromoBadge.tsx
> +const PromoBadge = ({ promoCode }: any) => {
Add type definition for props type, don't use "any"

2022-05-23 20:52 UTC, kibo-kevinwatts commented on components/common/PromoCodeBadge/PromoBadge.tsx
> +export default PromoBadge
This component is not being used by the other Promo code component and kind of duplicates the style, do we need it?

2022-05-24 09:51 UTC, kibo-sushant commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +}
**PromoCodeBadgeMain**

useState<any> => instad of any use proper type
list: any => change list to promo or something meaningfull
			 instad of any use proper type
			 
<> => As there is a single child, no need of a fragment
		 
**Unnecessary code**
As the child is not using  setCouponList, we should remove the prop

**Storybook**
 Able to add duplicate promo code,  is it correct behavior?
 ideally, after entering the promo code and hitting enter user should be able to add the promo code.
 
**Using  Absolute path over the relative**
Can we use absolute path instead of relative(../KiboTextBox)?

**Color**
Instead of hardcoding backgroundColor can we fetch it from Theme?

**TypeScript**
create interface PromoCodeBadgeProps and use it instead of using any 
Instead of any type use appropriate type everywhere
Instead of inferring types with useRef and useStatate, provide it explicitly

**Prop destructuring**
Instead of destructuring in between, we should do it at top

**Using Stack over Box with Flex**
Instead of using Box component, we can use Stack, which is more flexible
through which we can provide a gap between children, instead of passing mr to textbox

I think stack default direction is row only, no need to give it explicitly
<Stack direction="row"

**Style**
Actually parent should decide outer padding/margin, so we can remove marginTop: '1.5rem'

**Unnecessary Ref**
 Make KiboTextBox a controlled component and delete promoRef

**Unnecssary State**
 const [promoActive, setPromoActive] = useState(false)
 From couponList, as we can identify whether couponList is empty or not, no need of separate state
 Please delete it.

useEffect(() => {
    if (promo?.length > 0) {
      setIsEnabled(false)
    } else {
      setIsEnabled(true)
    }
  }, [promo])
From promo?.length, as we can enable/disable Apply button, no need to hold the state
Delete const [promoActive, setPromoActive] = useState(false)

**Proper naming conventions**
handleOnChange should be handleChange
For consistency purposes change (item: any) to (promo: string)

{couponList?.map((e: any)
Instead of e either use promo/coupon or something meaningfull

2022-05-24 09:51 UTC, kibo-sushant commented on components/common/PromoCodeBadge/PromoCodeBadge.stories.tsx
> +}
PromocodeBadgeComponent do not have isEnabled prop
PromocodeBadge do not have promoCode prop
Why we are passing it? and how it's working?

2022-05-24 09:51 UTC, kibo-sushant commented on components/common/PromoCodeBadge/PromocodeBadge.spec.js
> +    expect(ApplyButton).not.toHaveClass('Mui-disabled')
**Filename should be PromoCodeBadge.spec instead of PromocodeBadge.spec**

**I think we should have the following test cases**
 should render component
   Test whether the Promo Code text box is visible
   Test whether Apply button is visible 
   Test whether Apply button is disabled as the default
 
 should enable Apply button when a user enters Promo Code
 should disable Apply button when a user enters the promo code and apply it
 should display Promo Code when a user enters and apply it
 should display Promo Code when a user enters Promo Code and hits enter key
 should able to add multiple Promo Codes
 should not be able to add duplicate Promo Code
 should able to remove specific Promo Code
 
 Suggestion - Prefer to use userEvent over fireEvent

2022-05-24 09:51 UTC, kibo-sushant commented on components/common/PromoCodeBadge/PromoBadge.tsx
> +const PromoBadge = ({ promoCode }: any) => {
I think we should not club stories and test cases.
Please create separate files.

2022-06-01 22:06 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +export const PromoCodeBadge = (props: any) => {
Resolved

2022-06-01 22:07 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +  const promoRef = useRef<any>()
PromoRef is used to delete the applied promo code from the textbox

2022-06-01 22:07 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +  const [promoActive, setPromoActive] = useState(false)
Resolved

2022-06-01 22:08 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromocodeBadge.spec.js
> +    expect(ApplyButton).not.toHaveClass('Mui-disabled')
Almost added all these test cases

2022-06-01 22:08 UTC, kibo-Kripa commented on components/common/PromoCode/PromoCode.tsx
> +const PromoCode = ({ isEnabled }: any) => {
Resolved

2022-06-01 22:08 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromoBadge.tsx
> +export default PromoBadge
Resolved

2022-06-03 16:17 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromoBadge.tsx
> +export default PromoBadge
It is a separate component. We need that to display the badge only on a separate story

2022-06-08 22:20 UTC, kibo-kevinwatts requested changes

2022-06-08 22:20 UTC, kibo-kevinwatts commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +    const Coupon = (element: string) => element === promo
variable 'coupon' should be camelCase and more descriptive

2022-06-08 22:20 UTC, kibo-kevinwatts commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +    if (couponList?.some(Coupon)) {
still not sure if we need to check for this. 
since you're just console logging when its true, it may be simpler to write the logic like
```
if(!couponList?.some(comparePromo)){
    ...
    onApplyCouponCode(promo)
}
```

2022-06-08 22:20 UTC, kibo-kevinwatts commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +        promoRef.current.value = null
we should remove promoRef and make the input a controlled component

2022-06-14 20:24 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +    if (couponList?.some(Coupon)) {
Resolved

2022-06-14 20:24 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +    const Coupon = (element: string) => element === promo
Resolved

2022-06-14 22:17 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +        promoRef.current.value = null
Resolved

2022-06-21 21:34 UTC, kibo-kevinwatts commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +  promoList: any
add type for promo list instead of any, `string[]`

2022-06-24 17:54 UTC, kibo-Kripa commented on components/common/PromoCodeBadge/PromoCodeBadge.tsx
> +  promoList: any
Resolved

2022-06-27 17:29 UTC, merged