feat(register): UI Register Account Component
KiboSoftware/nextjs-storefront pull request #55
Opened 2022-05-24 09:46 UTC by kibo-geetanshuchhabra

2022-05-25 20:56 UTC, kibo-kevinwatts requested changes
Most of this looks good!

2022-05-25 20:56 UTC, kibo-kevinwatts commented on components/layout/RegisterAccount/Content/Content.spec.tsx
> +})
Don't mock the text box inputs for these tests

Add a test for the "create account" button

that should get the test coverage high enough to pass the Sonar Cloud

2022-05-25 20:56 UTC, kibo-kevinwatts commented on components/layout/RegisterAccount/Content/Content.tsx
> +  const createAccount = async (formData: RegisterAccountDetails) => {
I think this component should accept a prop that does the actual account creation, and should be passed in from the dialog component

2022-05-26 13:14 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/Content/Content.tsx
> +  const createAccount = async (formData: RegisterAccountDetails) => {
Resolved

2022-05-26 21:51 UTC, kibo-kevinwatts requested changes

2022-05-26 21:51 UTC, kibo-kevinwatts commented on components/layout/RegisterAccount/Content/Content.tsx
> +  const isCreateAccountButtonDisabled = () => {
Can we use the formState.isValid to determine if the button is disabled/enabled?
We shouldn't add a new function thats duplicating the validation logic

If a new function was added just for the "isPasswordValid" call, look at adding it to the yup validator https://github.com/jquense/yup#schematestoptions-object-schema

2022-05-30 08:44 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/Content/Content.spec.tsx
> +})
Resolved

2022-05-30 08:44 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/Content/Content.tsx
> +  const isCreateAccountButtonDisabled = () => {
Resolved

2022-05-30 12:43 UTC, kibo-sushant commented on components/layout/RegisterAccount/RegisterAccountDialog/RegisterAccountDialog.tsx
> +}
Pass params directly instead of creating const and using it ({...DialogArgs}).
<Content setAutoFocus={setAutoFocus} - delete setAutoFocus={setAutoFocus}
Instead of hardcoding width ( customMaxWidth: '32.375rem'), create const at top and use it


As below properties are default true one no need to send it
showContentTopDivider: true,
showContentBottomDivider: true,

2022-05-30 12:43 UTC, kibo-sushant commented on __test__/e2e/integration/layout/RegisterAccount/RegisterAccountDialog/RegisterAccountDialog.spec.tsx
> +})
missing test cases
 should display password validation component when user makes password field dirty

2022-05-31 04:28 UTC, kibo-geetanshuchhabra commented on public/locales/en/common.json
>  }
Resolved

2022-05-31 04:28 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/Title/Title.tsx
> +export default Title
Resolved

2022-05-31 10:51 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/RegisterAccountModal/RegisterAccountModal.tsx
> +export default RegisterAccountModal
Yes

2022-05-31 10:51 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/Content/Content.tsx
> +      {setAutoFocus}
Resolved

2022-05-31 10:51 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/Content/Content.tsx
> +  onRegisterToYourAccount: (formData: RegisterAccountInputData) => void
Resolved

2022-05-31 10:51 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/Content/Content.tsx
> +                setShowPassowordValidation(true)
Resolved

2022-05-31 10:51 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/RegisterAccountDialog/RegisterAccountDialog.tsx
> +}
Resolved

2022-05-31 10:51 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/RegisterAccountDialog/RegisterAccountDialog.tsx
> +}
Resolved

2022-05-31 10:57 UTC, kibo-geetanshuchhabra commented on components/layout/RegisterAccount/Content/Content.spec.tsx
> +})
Resolved

2022-05-31 11:35 UTC, kibo-sushant approved these changes

2022-05-31 23:14 UTC, kibo-kevinwatts approved these changes

2022-06-01 04:43 UTC, merged