integration login modal with API
KiboSoftware/nextjs-storefront pull request #61
Opened 2022-06-07 13:28 UTC by sss-bct

2022-06-08 06:16 UTC, kibo-sushant commented on components/layout/Login/LoginDialog/LoginDialog.tsx
> +
Unused Props
 customMaxWidth

Naming conventions
 KiboLoginFooter - no need of using kibo prefix
 
Remove console
 console.log('login params : ', params)

Use ? operator
    const userCredentials = {
      username: params.formData.email,
      password: params.formData.password,
    }

2022-06-08 06:16 UTC, kibo-sushant commented on pages/contexts/AuthContext.tsx
> +}
Meaningfull names
 isOpenLoginDialog should be isLoginDialogOpen

What approach are we going to follow?
 1) context will hold only State like user and isAuthenticated
 2) or context will have logic (will call custom hooks for login, logout, createUser) along with State also

I think instead of calling LoginDialog inside AuthContextProvider,  we should call it in _app.tsx
I think isOpenLoginDialog, toggleLoginDialog should not be part of context

2022-06-08 11:21 UTC, kibo-chandradeeptalaha reviewed
Context should not be under pages folder

2022-06-09 22:27 UTC, kibo-kevinwatts requested changes

2022-06-09 22:27 UTC, kibo-kevinwatts commented on components/layout/Login/LoginDialog/LoginDialog.tsx
> +  const { isLoginDialogOpen = false, toggleLoginDialog, setUser, authError = '' } = useAuthContext()
Create the context with initial state, instead of having to do 'isLoginDialogOpen = false' everywhere

2022-06-09 22:27 UTC, kibo-kevinwatts commented on components/layout/AppHeader/KiboHeader.tsx
> +  useUserQueries(onSuccess, onError)
Why are we passing callbacks to the custom hook instead of responding to the results?

2022-06-09 22:27 UTC, kibo-kevinwatts commented on components/layout/Login/LoginDialog/LoginDialog.tsx
> +  const login = async (params: LoginData) => {
rename to `handleLogin`

2022-06-09 22:27 UTC, kibo-kevinwatts commented on contexts/AuthContext.tsx
> +export const UserContext = createContext({} as AuthContextType)
create context with initial default state

2022-06-09 22:27 UTC, kibo-kevinwatts commented on components/layout/AppHeader/KiboHeader.tsx
> +  useUserQueries(onSuccess, onError)
Also, it might be better if we did this loading inside the Context itself

2022-06-10 12:36 UTC, sss-bct commented on package.json
>      "react-query": "^3.34.0",
We are not using this. removed all unnecessary entries. Not sure how it came here.

2022-06-10 12:37 UTC, sss-bct commented on lib/react-query/queryKeys.ts
> +  id: 'id' as string,
Now using array as it uses internally the same.

2022-06-10 12:38 UTC, sss-bct commented on lib/helpers/cookieHelper.ts
> +}
Made it configurable and fixed others.

2022-06-10 12:39 UTC, sss-bct commented on components/layout/Login/LoginDialog/LoginDialog.tsx
> +
Fixed.

2022-06-17 10:56 UTC, TriptiVermaXP requested changes

2022-06-17 10:56 UTC, TriptiVermaXP commented on components/layout/AppHeader/KiboHeader.tsx
> +                    subtitle={isAuthenticated ? 'Hi,' + user?.firstName : t('log-in')}
Take _Hi_, from localization

2022-06-17 10:56 UTC, TriptiVermaXP commented on components/layout/Login/LoginContent/LoginContent.tsx
>            label="Remember Me"
Labels should come from localization file.
aria-label="toggle password visibility" and label="Remember Me"

2022-06-17 10:56 UTC, TriptiVermaXP commented on components/layout/Login/LoginContent/LoginContent.tsx
> +          </Typography>
If possible, write the test case for error message.

2022-06-17 13:05 UTC, sss-bct commented on hooks/useUser/useUser.ts
> +}
Resolved

2022-06-17 13:05 UTC, sss-bct commented on pages/contexts/AuthContext.tsx
> +}
Done

2022-06-17 13:05 UTC, sss-bct commented on components/layout/AppHeader/KiboHeader.tsx
> +import { CustomerAccount } from '@/lib/gql/types'
Done

2022-06-17 13:06 UTC, sss-bct commented on components/layout/Login/LoginDialog/LoginDialog.tsx
> +  const { isLoginDialogOpen = false, toggleLoginDialog, setUser, authError = '' } = useAuthContext()
Done.

2022-06-17 13:06 UTC, sss-bct commented on components/layout/AppHeader/KiboHeader.tsx
> +  useUserQueries(onSuccess, onError)
Removed and fixed.

2022-06-17 13:06 UTC, sss-bct commented on components/layout/Login/LoginDialog/LoginDialog.tsx
> +  const login = async (params: LoginData) => {
Done.

2022-06-17 13:07 UTC, sss-bct commented on contexts/AuthContext.tsx
> +export const UserContext = createContext({} as AuthContextType)
Done.

2022-06-17 14:12 UTC, sss-bct commented on components/layout/AppHeader/KiboHeader.tsx
> +                    subtitle={isAuthenticated ? 'Hi,' + user?.firstName : t('log-in')}
Done

2022-06-17 14:12 UTC, sss-bct commented on components/layout/Login/LoginContent/LoginContent.tsx
>            label="Remember Me"
Done

2022-06-21 23:27 UTC, kibo-kevinwatts requested changes

2022-06-21 23:27 UTC, kibo-kevinwatts commented on contexts/AuthContext.spec.tsx
> +    <QueryClientProvider client={new QueryClient()}>
Reuse the `renderWithQueryClient` util under __test__/utils instead of importing duplicating code here

2022-06-21 23:27 UTC, kibo-kevinwatts commented on contexts/AuthContext.spec.tsx
> +          const { mutate } = useUserMutations()
you don't want to call the useUserMutation here directly.
you're login test should only call the exposed context hook method
Use MSW to mock both successful and error responses

```
    const { result } = renderHook(() => useAuthContext(), { wrapper })
    act(async () => {
      await result.current.login(params, mockSuccessCallback)
    })
    
    expect(result.current.user).toEqual(mockUser)
    expect(mockSuccessCallback).toBeCalled()
```

2022-06-21 23:27 UTC, kibo-kevinwatts commented on contexts/AuthContext.spec.tsx
> +  })
Add another use case for when login requests fails
```
    const { result } = renderHook(() => useAuthContext(), { wrapper })
    act(async () => {
      await result.current.login({email: 'mockFailedRequest'}, mockCallback)
    })

    expect(result.current.user).toEqual(null || whatever)
    expect(result.current.authError).toEqual('Something Wrong')
    expect(mockSuccessCallback).not.toBeCalled()
```

2022-06-21 23:27 UTC, kibo-kevinwatts commented on contexts/AuthContext.spec.tsx
> +import { storeClientCookie } from '@/lib/helpers/cookieHelper'
storeClientCookie should be mocked, and test that it was called on success

2022-06-21 23:27 UTC, kibo-kevinwatts commented on contexts/AuthContext.tsx
> +  setUser: any
is there a type we can use instead of any

2022-06-24 06:10 UTC, sss-bct commented on components/layout/Login/LoginContent/LoginContent.tsx
> +          </Typography>
Will be handled in different PR

2022-06-24 11:32 UTC, sss-bct commented on contexts/AuthContext.spec.tsx
> +    <QueryClientProvider client={new QueryClient()}>
Done.

2022-06-24 11:33 UTC, sss-bct commented on contexts/AuthContext.spec.tsx
> +          const { mutate } = useUserMutations()
Resolved using custom component instead renderHook.

2022-06-24 11:33 UTC, sss-bct commented on contexts/AuthContext.spec.tsx
> +import { storeClientCookie } from '@/lib/helpers/cookieHelper'
Done.

2022-06-24 11:33 UTC, sss-bct commented on contexts/AuthContext.tsx
> +  setUser: any
Removed. As it is handled in the context itself without exposing to all components.

2022-06-27 07:25 UTC, TriptiVermaXP approved these changes

2022-06-27 11:12 UTC, kibo-sushant approved these changes

2022-06-27 11:12 UTC, merged