feat: pdp product options integration
KiboSoftware/nextjs-storefront pull request #62
Opened 2022-06-08 11:16 UTC by kibo-chandradeeptalaha

2022-06-15 20:07 UTC, kibo-kevinwatts requested changes
This looks good! 
I have a couple of questions around the types, we can discuss after standup

2022-06-15 20:07 UTC, kibo-kevinwatts commented on hooks/custom/useProductDetailTemplate/useProductDetailTemplate.ts
> +      setUpdatedShopperEnteredValues(updatedOptions)
before we call `setUpdatedShopperEnteredValues` shouldn't we build the `updatedOptions` from the configureProductResponse?

2022-06-15 20:07 UTC, kibo-kevinwatts commented on hooks/mutations/useProductMutation/useProductMutation.spec.js
> +import { configuredProductDataMock } from '../../../__mocks__/stories/configuredProductDataMock'
prefer alias @ path instead of long relative paths

2022-06-15 20:07 UTC, kibo-kevinwatts commented on hooks/mutations/useProductMutation/useProductMutation.ts
> +import { ConfigureOption } from '@/lib/types'
import type {

2022-06-15 20:07 UTC, kibo-kevinwatts commented on hooks/mutations/useProductMutation/useProductMutation.ts
> +const configureProduct = async (configureProductDetails: ConfigureProductDetails) => {
is there a graphql type for this already?
and shouldn't there be a "quantity"?

2022-06-15 20:07 UTC, kibo-kevinwatts commented on hooks/custom/useProductDetailTemplate/useProductDetailTemplate.ts
> +  product: ProductCustom
do we need ProductCustom? instead of just "Product'?

2022-06-16 06:45 UTC, kibo-chandradeeptalaha commented on components/common/Price/Price.tsx
> +import { useTranslation } from 'next-i18next'
We are passing the whole priceRange object into the Price component. In order to do the translation on Parent, we need to then modify that object either in Getter or the Parent itself. Or we can handle that inside that Price component. @kibo-kevinwatts

2022-06-16 06:56 UTC, kibo-chandradeeptalaha commented on hooks/custom/useProductDetailTemplate/useProductDetailTemplate.ts
> +  product: ProductCustom
This is to get the fulfillment options inside Product Type as well.

ProductCustom = Product & ProductWithFullmentOptions

2022-06-16 11:28 UTC, kibo-chandradeeptalaha commented on components/common/Price/Price.tsx
> +import { ProductPriceRange } from '@/lib/gql/types'
Done

2022-06-16 11:38 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useProductMutation/useProductMutation.ts
> +import { ConfigureOption } from '@/lib/types'
Done

2022-06-16 11:40 UTC, kibo-chandradeeptalaha commented on hooks/mutations/useProductMutation/useProductMutation.spec.js
> +import { configuredProductDataMock } from '../../../__mocks__/stories/configuredProductDataMock'
Done

2022-06-16 11:40 UTC, kibo-chandradeeptalaha commented on hooks/custom/useProductDetailTemplate/useProductDetailTemplate.ts
> +      setUpdatedShopperEnteredValues(updatedOptions)
Done

2022-06-20 09:20 UTC, kibo-chandradeeptalaha commented on components/common/Price/Price.tsx
> +  const { children, color, sx, variant = 'body1', fontWeight = 'bold' } = priceProps
These have default values set. We should not remove as these can be used in different components.

2022-06-20 12:44 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.spec.js
> +    expect(onChangeMock).toHaveBeenCalledTimes(0)
Done

2022-06-20 12:44 UTC, kibo-chandradeeptalaha commented on components/product/ProductVariantSizeSelector/ProductVariantSizeSelector.tsx
> +  onChange: (attributeFQN: string, value: string) => void
Done

2022-06-20 12:44 UTC, kibo-chandradeeptalaha commented on components/product/ProductOptionTextBox/ProductOptionTextBox.tsx
> +  console.log('sfgsfdgf', option?.values?.[0]?.shopperEnteredValue)
Done

2022-06-20 12:44 UTC, kibo-chandradeeptalaha commented on components/product/ProductOptionSelect/ProductOptionSelect.tsx
> +  onChange: (attributeFQN: string, value: string) => void
Done

2022-06-20 12:44 UTC, kibo-chandradeeptalaha commented on components/product/ProductOptionCheckbox/ProductOptionCheckbox.tsx
> +  const { label = '', checked = false, attributeFQN, onChange } = props
Done

2022-06-20 12:44 UTC, kibo-chandradeeptalaha commented on components/product/ColorSelector/ColorSelector.tsx
> +  onChange: (attributeFQN: string, value: string) => void
Done

2022-06-20 12:45 UTC, kibo-chandradeeptalaha commented on components/common/Price/Price.tsx
> +          <SalePriceTypography price={price} salePrice={salePrice} {...rest} />
Done

2022-06-20 12:45 UTC, kibo-chandradeeptalaha commented on components/common/Price/Price.stories.tsx
> +    },
Removed

2022-06-20 12:45 UTC, kibo-chandradeeptalaha commented on __mocks__/stories/configuredProductDataMock.ts
> +}
Done

2022-06-22 06:22 UTC, kibo-chandradeeptalaha commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +  const productOptions = productGetters.getSegregatedOptions(currentProduct)
Done

2022-06-28 14:02 UTC, kibo-kevinwatts approved these changes

2022-06-29 11:36 UTC, kibo-sushant approved these changes

2022-06-29 11:36 UTC, merged