feat(plp): Integrate NextJS Category Page and Route
KiboSoftware/nextjs-storefront pull request #64
Opened 2022-06-09 11:41 UTC by kibo-geetanshuchhabra

2022-06-15 20:42 UTC, kibo-kevinwatts requested changes

2022-06-15 20:42 UTC, kibo-kevinwatts commented on components/product-listing/CategoryFacet/CategoryFacet.tsx
> +import { BreadCrumb as BreadCrumbType } from '@/lib/types'
import type {

2022-06-15 20:42 UTC, kibo-kevinwatts commented on components/product-listing/CategoryFacet/CategoryFacet.tsx
> +            href={`/category/${child?.value}`}
need to use a helper here to make category link

2022-06-15 20:42 UTC, kibo-kevinwatts commented on lib/api/operations/get-category-tree-by-code.ts
> +}
We don't have to change this for this pull request
but, for performance, we may want to query the api for categories by code, instead of using the full category tree
``` 
query {
  categories(filter:"categoryCode eq 1234") { 
}}
```

2022-06-15 20:42 UTC, kibo-kevinwatts commented on lib/api/operations/get-category-tree-by-code.ts
> +}
We don't have to change this for this pull request
but, for performance, we may want to query the api for categories by code, instead of using the full category tree
```query {
  categories(filter:"categoryCode eq 1234") { 
}}```

2022-06-15 20:42 UTC, kibo-kevinwatts commented on lib/api/operations/get-product-search.ts
> +import { QueryProductSearchArgs } from '@/lib/gql/types'
import type {

2022-06-15 20:42 UTC, kibo-kevinwatts commented on lib/api/operations/get-product-search.ts
> +import { QueryProductSearchArgs } from '@/lib/gql/types'
import type {

2022-06-15 20:42 UTC, kibo-kevinwatts commented on lib/getters/facetGetters.ts
> +    link: `/category/${b.link}`,
need to use helper for url building

2022-06-15 20:42 UTC, kibo-kevinwatts commented on lib/getters/facetGetters.ts
> +    link: `/category/${b.link}`,
need to use helper for url building

2022-06-16 06:47 UTC, kibo-sushant commented on lib/api/operations/get-category-tree-by-code.ts
> +}
consistency purpose use arrow function every were instead of normal one
import type {

2022-06-16 06:47 UTC, kibo-sushant commented on pages/category/[categoryCode].tsx
>  export async function getServerSideProps(context: GetServerSidePropsContext) {
Shall we cache response using 'Cache-Control' header? 
 res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )
  
  use : GetServerSideProps as type
  
  Remove any and use specific type
  const CategoryPage: NextPage = (props: any) => {

2022-06-16 06:47 UTC, kibo-sushant commented on __test__/unit/pages/categoryPage.spec.js
> +})
while mocking, create const and use it (instead of mocking inline)
In assertion, define const for an expected result and use it (instead of using big value)

2022-06-16 09:02 UTC, TriptiVermaXP commented on lib/api/operations/get-category-tree-by-code.ts
> +}
Use arrow function

2022-06-16 09:06 UTC, TriptiVermaXP commented on lib/api/operations/get-category-tree-by-code.ts
> +    return category?.childrenCategories?.find((childCategory: Maybe<PrCategory>) => {
return type of findCategoryById  is Boolean, they why are returning PrCategory here?

2022-06-16 09:08 UTC, TriptiVermaXP commented on lib/api/operations/get-category-tree-by-code.ts
> +export default async function search(searchParams: any) {
define type for searchParams

2022-06-16 09:16 UTC, TriptiVermaXP commented on pages/category/[categoryCode].tsx
>  const CategoryPage: NextPage = (props: any) => {
Please define type for page props

2022-06-16 09:20 UTC, TriptiVermaXP commented on __test__/unit/pages/categoryPage.spec.js
> +import { categoryTreeDataMock } from '../../../__mocks__/stories/categoryTreeDataMock'
import from @ path.
Also group the contents by adding blank line

2022-06-16 09:22 UTC, TriptiVermaXP commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
>      initialProductsToShow = 16,
Should we take it from config file?

2022-06-20 09:43 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.stories.tsx
>  import { categoryFacet } from '../../../__mocks__/stories/categoryFacetDataMock'
Resolved

2022-06-20 09:43 UTC, kibo-geetanshuchhabra commented on components/layout/MegaMenuItem/MegaMenuItem.spec.tsx
> +      expect(name).toHaveAttribute('href', '/category/' + cat?.categoryCode)
Resolved

2022-06-20 09:43 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
>      initialProductsToShow = 16,
will handle this part on pagination and sorting ticket, maybe we don't required this variable.

2022-06-20 09:44 UTC, kibo-geetanshuchhabra commented on __test__/unit/pages/categoryPage.spec.js
> +import { categoryTreeDataMock } from '../../../__mocks__/stories/categoryTreeDataMock'
Resolved

2022-06-20 09:45 UTC, kibo-geetanshuchhabra commented on lib/api/operations/get-product-search.ts
>  import type { NextApiRequest, NextApiResponse } from 'next'
Resolved

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on lib/api/operations/get-category-tree-by-code.ts
> +    return category?.childrenCategories?.find((childCategory: Maybe<PrCategory>) => {
Prcategory type is for selectCategoryFromTree function.

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on lib/api/operations/get-category-tree-by-code.ts
> +}
Resolved

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on __test__/unit/pages/categoryPage.spec.js
> +})
Resolved

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on pages/category/[categoryCode].tsx
>  export async function getServerSideProps(context: GetServerSidePropsContext) {
Resolved(partially)

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on lib/api/operations/get-category-tree-by-code.ts
> +}
Resolved

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on lib/getters/__tests__/productGetters.spec.js
> +        link: `/category/42`,
Resolved

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on lib/getters/facetGetters.ts
> +import { BreadCrumb } from '../types'
Resolved

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on lib/getters/productGetters.ts
> +  )?.values
Resolved

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on lib/getters/productSearchGetters.ts
> +import { FacetValue, ProductSearchResult } from '../gql/types'
Resolved

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on components/product-listing/CategoryFacet/CategoryFacet.spec.tsx
> -  it('should call onCategoryChildSelection when user selects specific category', () => {
we are checking the particular link path in our test cases.

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on components/product-listing/CategoryFacet/CategoryFacet.spec.tsx
> -  it('should call onBackButtonClick when user clicks on Back button', () => {
we have removed the function, we are using the href for redirection and test cases is written for checking whether the link have attribute or not.

2022-06-20 09:46 UTC, kibo-geetanshuchhabra commented on __mocks__/stories/productSearchDataMock.ts
> +export const productSearchDataMock = {
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/product-listing/CategoryFilterByMobile/CategoryFilterByMobile.stories.tsx
> +import { productSearchDataMock } from '../../../__mocks__/stories/productSearchDataMock'
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/product-listing/FacetList/FacetList.stories.tsx
> +import { productSearchDataMock } from '../../../__mocks__/stories/productSearchDataMock'
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/product-listing/CategoryFilterByMobile/CategoryFilterByMobile.tsx
>    onFilterByClose: () => void
In search page we don't require header

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/product-listing/FacetList/FacetList.tsx
> +            />
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on lib/getters/facetGetters.ts
> +    link: `/category/${b.link}`,
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on lib/getters/facetGetters.ts
> +    link: `/category/${b.link}`,
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on lib/api/operations/get-product-search.ts
> +import { QueryProductSearchArgs } from '@/lib/gql/types'
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on lib/api/operations/get-product-search.ts
> +import { QueryProductSearchArgs } from '@/lib/gql/types'
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/product-listing/CategoryFacet/CategoryFacet.tsx
> +            href={`/category/${child?.value}`}
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                          link={`/product/${product.productCode}`}
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                          link={`/product/${product.productCode}`}
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
>        setProductsToShow([...sliced])
Will handle this part on sorting and pagination ticket.

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
>        setProductsToShow([...sliced])
Will handle this part on sorting and pagination ticket.

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/product-listing/CategoryFacet/CategoryFacet.tsx
> +import { BreadCrumb as BreadCrumbType } from '@/lib/types'
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/product-listing/CategoryFacet/CategoryFacet.spec.tsx
> +import { CategoryFacetProps } from './CategoryFacet'
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on components/product-listing/CategoryFacet/CategoryFacet.spec.tsx
> +import { CategoryFacetProps } from './CategoryFacet'
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on lib/getters/productGetters.ts
> +    link: `/category/${b.link}`,
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on pages/category/[categoryCode].tsx
> +  const sortingValues = [
Resolved

2022-06-20 09:47 UTC, kibo-geetanshuchhabra commented on pages/category/[categoryCode].tsx
> +  const sortingValues = [
Resolved

2022-06-21 23:33 UTC, kibo-kevinwatts approved these changes
lgtm!

2022-06-22 11:06 UTC, kibo-sushant approved these changes

2022-06-22 11:45 UTC, kibo-geetanshuchhabra commented on pages/category/[categoryCode].tsx
>  export async function getServerSideProps(context: GetServerSidePropsContext) {
Will handle cache-control on icky-633

2022-06-22 11:47 UTC, kibo-geetanshuchhabra commented on lib/api/operations/get-category-tree-by-code.ts
> +}
Okay

2022-06-22 11:50 UTC, TriptiVermaXP approved these changes

2022-06-22 11:51 UTC, merged