feat(ReviewStep): initial commit with test cases
KiboSoftware/nextjs-storefront pull request #67
Opened 2022-06-14 09:30 UTC by amolpawar-kibo

2022-06-16 07:04 UTC, kibo-chandradeeptalaha commented on components/checkout/ReviewStep/ReviewStep.tsx
> +    backgroundColor: '#C0E3DF',
Don't we have something for this in theme ?

2022-06-16 07:07 UTC, kibo-chandradeeptalaha commented on components/common/ProductItem/ProductItem.tsx
> +  itemPurchaseLocation?: string | null
These props should be coming from a gql type

2022-06-16 07:37 UTC, kibo-chandradeeptalaha requested changes
Please take a look

2022-06-16 07:37 UTC, kibo-chandradeeptalaha commented on components/checkout/ReviewStep/ReviewStep.tsx
> +        <StyledGoBackButton variant="contained" onClick={goBack}>
use Global buttons

2022-06-16 07:37 UTC, kibo-chandradeeptalaha commented on components/checkout/ReviewStep/ReviewStep.tsx
> +        <StyledConfirmAndPayButton
Use Global Buttons

2022-06-16 07:37 UTC, kibo-chandradeeptalaha commented on lib/getters/checkoutGetters.ts
> +    price: '$' + (item?.product?.price?.price || 0).toString(),
We should not format the currency here

2022-06-16 07:37 UTC, kibo-chandradeeptalaha commented on lib/getters/checkoutGetters.ts
> +import DefaultImage from '@/public/product_placeholder.svg'
Try to define return types for these functions

2022-06-16 07:37 UTC, kibo-chandradeeptalaha commented on lib/getters/checkoutGetters.ts
> +    ?.filter((item) => item?.fulfillmentMethod === 'Ship')
I think we should get the "Ship"/"Pickup" values from next.config for consistency purpose

2022-06-16 07:37 UTC, kibo-chandradeeptalaha commented on components/checkout/OrderReview/OrderReview.tsx
> +  marginTop: '4.313rem',
Why are we using this here ?

2022-06-16 10:07 UTC, kibo-sushant commented on components/page-templates/Checkout/Checkout.tsx
> +  const reviesStepIndex = steps.findIndex((step) => step === t('review'))
correct the typo

2022-06-16 10:14 UTC, kibo-sushant commented on components/common/AddressForm/AddressForm.spec.tsx
> +import { render, screen, fireEvent, waitFor } from '@testing-library/react'
prefer userEvent over fireEvent

2022-06-16 10:16 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +  it('should default unchecked saved payment if logged in', async () => {
use should...when
test case is not meaningfull

2022-06-17 10:46 UTC, TriptiVermaXP requested changes

2022-06-17 10:46 UTC, TriptiVermaXP commented on components/checkout/OrderReview/OrderReview.spec.tsx
> +  })
Missing tests for userName and userPhoneHome value checks.
Missing tests for AddressDetailsView component mock/check the functionality.
Missing tests for paymentMethods and their values.
Missing tests for Edit click event.

2022-06-17 10:46 UTC, TriptiVermaXP commented on components/checkout/ReviewStep/ReviewStep.tsx
> +    setAggreeWithTermsAndConditions(event.target.checked)
Correct the typo of Agree - isAggreeWithTermsAndConditions

2022-06-21 09:48 UTC, kibo-chandradeeptalaha requested changes
Please take a look

2022-06-23 22:01 UTC, kibo-kevinwatts requested changes

2022-06-23 22:43 UTC, kibo-kevinwatts commented on components/common/OrderPrice/OrderPrice.spec.tsx
> +    expect(screen.getByText(/\$219\.99/i)).toBeVisible()
instead of searching by values like, `$219\.99/`, try using them from `Common.args` if possible

2022-06-24 13:12 UTC, amolpawar-kibo commented on components/checkout/ReviewStep/ReviewStep.tsx
> +    backgroundColor: '#C0E3DF',
Done.

2022-06-24 13:12 UTC, amolpawar-kibo commented on components/common/ProductItem/ProductItem.tsx
> +  itemPurchaseLocation?: string | null
Done.

2022-06-24 13:12 UTC, amolpawar-kibo commented on components/checkout/ReviewStep/ReviewStep.tsx
> +        <StyledConfirmAndPayButton
Done.

2022-06-24 13:13 UTC, amolpawar-kibo commented on components/checkout/OrderReview/OrderReview.tsx
> +  marginTop: '4.313rem',
Done.

2022-06-24 13:13 UTC, amolpawar-kibo commented on components/checkout/ReviewStep/ReviewStep.tsx
> +  goBack: () => void
Done.

2022-06-24 13:16 UTC, amolpawar-kibo commented on components/checkout/ReviewStep/ReviewStep.tsx
> +      onCompleteCallback({ type: FormStates.COMPLETE })
Done.

2022-06-24 13:18 UTC, amolpawar-kibo commented on components/checkout/OrderReview/OrderReview.tsx
> +  const paymentMethods = checkoutGetters.getPaymentMethods(checkout)
Done.

2022-06-24 13:18 UTC, amolpawar-kibo commented on components/checkout/OrderReview/OrderReview.stories.tsx
> +} as ComponentMeta<typeof OrderReview>
Done.

2022-06-24 13:18 UTC, amolpawar-kibo commented on components/checkout/ReviewStep/ReviewStep.stories.tsx
>  } as ComponentMeta<typeof ReviewStep>
Done.

2022-06-24 13:18 UTC, amolpawar-kibo commented on components/page-templates/Checkout/Checkout.tsx
> +  const reviesStepIndex = steps.findIndex((step) => step === t('review'))
Done.

2022-06-24 13:18 UTC, amolpawar-kibo commented on components/common/AddressForm/AddressForm.spec.tsx
> +import { render, screen, fireEvent, waitFor } from '@testing-library/react'
Done.

2022-06-24 13:18 UTC, amolpawar-kibo commented on components/checkout/PaymentStep/PaymentStep.spec.tsx
> +  it('should default unchecked saved payment if logged in', async () => {
Done.

2022-06-24 13:19 UTC, amolpawar-kibo commented on components/add-to-cart-dialog/Content/Content.tsx
> +export const StyledPriceSection = styled(Box)(() => ({
Done. Created OrderPrice component

2022-06-24 13:19 UTC, amolpawar-kibo commented on components/checkout/OrderReview/OrderReview.tsx
> +export const StyledOrderReview = styled(Box)(({ theme }: StyledThemeProps) => ({
Done.

2022-06-24 13:19 UTC, amolpawar-kibo commented on components/checkout/ReviewStep/ReviewStep.tsx
> +    setAggreeWithTermsAndConditions(event.target.checked)
Done.

2022-06-24 13:20 UTC, amolpawar-kibo commented on components/checkout/ReviewStep/ReviewStep.tsx
> +        <StyledPriceRow>
Done.

2022-06-24 13:20 UTC, amolpawar-kibo commented on components/page-templates/Checkout/Checkout.tsx
> +          <OrderSummary {...orderSummeryArgs}>
Done.

2022-06-24 13:20 UTC, amolpawar-kibo commented on components/checkout/ReviewStep/ReviewStep.tsx
> +      </StyledPriceTotalRow> */}
Done.

2022-06-24 13:20 UTC, amolpawar-kibo commented on components/checkout/ReviewStep/ReviewStep.tsx
> +    fullfillmentMethodLable: t('shipping'),
Done.

2022-06-24 13:20 UTC, amolpawar-kibo commented on components/common/OrderPrice/OrderPrice.tsx
> +  fullfillmentMethodLable: string
Done.

2022-06-24 13:22 UTC, amolpawar-kibo commented on lib/getters/checkoutGetters.ts
> +const getShippingTotal = (checkout: Order): string => checkout?.shippingTotal?.toString() || ''
Done. In mockup its showing 'free' so i was used string but now converted to number. 
Mockup Link. https://marvelapp.com/prototype/hh42h21/screen/87340957/handoff
Will discuss in detail

2022-06-24 13:23 UTC, amolpawar-kibo commented on components/common/OrderPrice/OrderPrice.spec.tsx
> +    expect(screen.getByText(/\$219\.99/i)).toBeVisible()
Done.

2022-06-24 13:35 UTC, amolpawar-kibo commented on components/common/OrderPrice/OrderPrice.spec.tsx
> +    expect(screen.getByText(/\$219\.99/i)).toBeVisible()
Done

2022-06-27 14:31 UTC, amolpawar-kibo commented on components/common/OrderPrice/OrderPrice.tsx
> +}))
Done.

2022-06-28 21:55 UTC, kibo-kevinwatts commented
@amolpawar-kibo Update the test cases per @TriptiVermaXP's comments and revert the msw test changes and i think we can merge this then

2022-06-29 05:21 UTC, amolpawar-kibo commented on components/checkout/OrderReview/OrderReview.stories.tsx
> +} as ComponentMeta<typeof OrderReview>
Resolve

2022-06-30 04:57 UTC, amolpawar-kibo commented on components/checkout/OrderReview/OrderReview.spec.tsx
> +  })
Done

2022-06-30 07:10 UTC, TriptiVermaXP approved these changes
Looks good.

2022-06-30 07:11 UTC, kibo-sushant approved these changes

2022-06-30 17:03 UTC, kibo-kevinwatts approved these changes

2022-06-30 17:12 UTC, kibo-chandradeeptalaha approved these changes

2022-07-01 04:24 UTC, merged