feat: fulfillment options radio component
KiboSoftware/nextjs-storefront pull request #68
Opened 2022-06-15 07:20 UTC by kibo-chandradeeptalaha

2022-06-16 08:13 UTC, kibo-sushant commented on components/cart/CartItem/CartItem.tsx
> +              <FulfillmentOptions fulfillmentOptions={fulfillmentOptionsMock} />
should not use mock data inside component, if required create prop and pass it from story

2022-06-16 08:13 UTC, kibo-sushant commented on __mocks__/stories/fulfillmentOptionsMock.ts
> +]
use return type
as best practice(to avoid code duplication) filename should be return type + 'Mock'

2022-06-16 22:22 UTC, kibo-kevinwatts commented on components/cart/CartItem/CartItem.tsx
> +              <FulfillmentOptions fulfillmentOptions={fulfillmentOptionsMock} />
^ what sushant said

2022-06-16 22:28 UTC, kibo-kevinwatts requested changes

2022-06-16 22:28 UTC, kibo-kevinwatts commented on components/common/FulfillmentOptions/FulfillmentOptions.tsx
> +            cta: option.details ? t('change store') : t('select store'),
missing hyphen in key, should be ` t('change-store')` and `t('select store')`

2022-06-16 22:28 UTC, kibo-kevinwatts commented on components/common/FulfillmentOptions/FulfillmentOptions.tsx
> +import { FulfillmentOption } from '@/lib/types'
import type {

2022-06-16 22:28 UTC, kibo-kevinwatts commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +import { fulfillmentOptionsMock } from '@/__mocks__/stories/fulfillmentOptionsMock'
don't use mock in components

2022-07-07 11:46 UTC, kibo-sushant approved these changes

2022-07-07 15:06 UTC, kibo-kevinwatts approved these changes

2022-07-07 18:06 UTC, merged