feat: Order History
KiboSoftware/nextjs-storefront pull request #71
Opened 2022-06-24 04:13 UTC by kibo-sushant

2022-06-24 05:58 UTC, kibo-chandradeeptalaha requested changes
Please take a look

2022-06-24 05:58 UTC, kibo-chandradeeptalaha commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos'
use named import for icons

2022-06-24 05:58 UTC, kibo-chandradeeptalaha commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +        <Typography variant="body1" sx={{ fontWeight: 'bold' }}>
Use Price Component

2022-06-24 05:58 UTC, kibo-chandradeeptalaha commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +        <Typography variant="body2" sx={{ color: 'grey.600' }}>
Order status should be color primary

2022-06-24 05:58 UTC, kibo-chandradeeptalaha commented on components/my-account/OrderHistoryItem/OrderHistoryItem.stories.tsx
> +  order: (orderCollection &&
use ? instead of chaining. pass a default [] if not found.

2022-06-24 05:58 UTC, kibo-chandradeeptalaha commented on components/my-account/OrderHistoryItem/OrderHistoryItem.spec.tsx
> +    const order = (Common && Common.args && Common.args.order) as Order
No need for chaining. If order is not provided, the UT should fail.

2022-06-24 05:58 UTC, kibo-chandradeeptalaha commented on components/my-account/OrderHistory/OrderHistory.tsx
> +          <OrderHistoryItem key={index} order={item as Order} />
We should use some sort routing here to navigate to the individual order details.

2022-06-24 05:58 UTC, kibo-chandradeeptalaha commented on components/my-account/OrderHistory/OrderHistory.tsx
> +import ArrowBackIosIcon from '@mui/icons-material/ArrowBackIos'
use named import

2022-06-24 05:58 UTC, kibo-chandradeeptalaha commented on components/my-account/OrderHistory/OrderHistory.tsx
> +        <Typography variant="h1">Order History</Typography>
use translation

2022-06-24 05:58 UTC, kibo-chandradeeptalaha commented on components/my-account/OrderHistory/OrderHistory.spec.tsx
> +    // const { orders, accountTitle } = Common?.args
Remove commented code

2022-06-24 07:55 UTC, kibo-sushant commented on components/my-account/OrderHistory/OrderHistory.spec.tsx
> +    // const { orders, accountTitle } = Common?.args
Resolved

2022-06-24 07:55 UTC, kibo-sushant commented on components/my-account/OrderHistory/OrderHistory.tsx
> +        <Typography variant="h1">Order History</Typography>
Resolved

2022-06-24 08:02 UTC, kibo-sushant commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos'
Resolved

2022-06-24 08:17 UTC, kibo-sushant commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +        <Typography variant="body1" sx={{ fontWeight: 'bold' }}>
Resolved

2022-06-24 08:17 UTC, kibo-sushant commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +        <Typography variant="body2" sx={{ color: 'grey.600' }}>
Resolved

2022-06-24 08:21 UTC, kibo-sushant commented on components/my-account/OrderHistoryItem/OrderHistoryItem.stories.tsx
> +  order: (orderCollection &&
Its required to satisfy TypeScript

2022-06-24 08:21 UTC, kibo-sushant commented on components/my-account/OrderHistory/OrderHistory.tsx
> +import ArrowBackIosIcon from '@mui/icons-material/ArrowBackIos'
Resolved

2022-06-24 15:32 UTC, kibo-kevinwatts reviewed
This all looks good! check my one comment on orderhistoryitem props

2022-06-24 15:32 UTC, kibo-kevinwatts commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +  const { order, onHistoryItemClick } = props
for dumb components like this, we have been explicit in passing the props instead of just passing the entire object. Can we do that instead?

2022-06-27 05:38 UTC, kibo-sushant commented on components/my-account/OrderHistory/OrderHistory.tsx
> +            key={index}
resolved

2022-06-27 05:38 UTC, kibo-sushant commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +  const { order, onHistoryItemClick } = props
resolved

2022-06-27 07:48 UTC, TriptiVermaXP requested changes
Please take a look.

2022-06-27 07:48 UTC, TriptiVermaXP commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +        <Typography variant="body1" sx={{ color: 'text.secondary' }}>
Typography directly accept _fontWeight="bold" color={'text.secondary'}_ instead of sx

2022-06-27 07:48 UTC, TriptiVermaXP commented on components/my-account/OrderHistory/OrderHistory.tsx
> +      <Stack sx={{ pt: '1.2rem', pb: '1.2rem' }}>
instead of pt: '1.2rem', pb: '1.2rem', we can directly use py: '1.2rem'.
px for left-right padding
py for top-bottom padding

2022-06-27 07:48 UTC, TriptiVermaXP commented on components/my-account/OrderHistory/OrderHistory.tsx
> +      >
As we have styles object defined, can we move inline all css on the top?

2022-06-27 07:48 UTC, TriptiVermaXP commented on components/common/FilterTiles/FilterTiles.tsx
> +      label="Last 6 months"
should be localized

2022-06-27 07:48 UTC, TriptiVermaXP commented on components/common/FilterOrders/FilterOrders.tsx
> +    color: '#2b2b2b',
Can't we take color from theme?

2022-06-27 07:48 UTC, TriptiVermaXP commented on components/my-account/OrderHistory/OrderHistory.spec.tsx
> +const OrderHistoryItemMock = () => <div data-testid="order-history-mock" />
Do we need integration testing to test these dependent components?

2022-06-28 06:09 UTC, kibo-sushant commented on components/my-account/OrderHistory/OrderHistory.spec.tsx
> +const OrderHistoryItemMock = () => <div data-testid="order-history-mock" />
As the component is read-only integration test is not required (maybe it will require after implementing FilterOrders and FilterTiles)

2022-06-28 06:10 UTC, kibo-sushant commented on components/common/FilterOrders/FilterOrders.tsx
> +    color: '#2b2b2b',
As mentioned in the component comment, it's a dummy component. It will get replaced by actual component.

2022-06-28 06:11 UTC, kibo-sushant commented on components/common/FilterTiles/FilterTiles.tsx
> +      label="Last 6 months"
As mentioned in the component comment, it's a dummy component. It will get replaced by an actual component.

2022-06-28 06:11 UTC, kibo-sushant commented on components/my-account/OrderHistory/OrderHistory.tsx
> +      >
I think one-liner sx is always fine

2022-06-28 06:12 UTC, kibo-sushant commented on components/my-account/OrderHistory/OrderHistory.tsx
> +      <Stack sx={{ pt: '1.2rem', pb: '1.2rem' }}>
resolved

2022-06-28 06:14 UTC, kibo-sushant commented on components/my-account/OrderHistoryItem/OrderHistoryItem.tsx
> +        <Typography variant="body1" sx={{ color: 'text.secondary' }}>
resolved

2022-06-28 21:18 UTC, kibo-kevinwatts approved these changes
Looks good. the sonar cloud duplication is only from mocked data so we can ignore that.

2022-06-29 05:28 UTC, TriptiVermaXP approved these changes
Approved.
Few code smells are there.
ViewOrderDetails is merged, we can integrate with order history.

2022-06-29 07:53 UTC, kibo-chandradeeptalaha approved these changes

2022-06-29 09:52 UTC, merged