feat(plp): category page facet
KiboSoftware/nextjs-storefront pull request #72
Opened 2022-06-24 12:45 UTC by kibo-geetanshuchhabra

2022-06-24 16:28 UTC, kibo-kevinwatts requested changes
Very good!

2022-06-24 16:28 UTC, kibo-kevinwatts commented on components/common/FilterTiles/FilterTiles.tsx
> +    updateRoute(tile as string)
since we plan on re-using these filter tiles, instead of calling ` updateRoute(` from within component it should be a prop we can provide

2022-06-27 10:32 UTC, kibo-sushant commented on lib/api/handlers/search.ts
> +    const response = await productSearch(req.query as unknown as CategorySearchParams)
Do we need both? as unknown as CategorySearchParams ?

2022-06-27 10:32 UTC, kibo-sushant commented on lib/getters/__tests__/facetGetters.spec.js
> +  it('should call getSelectedFacets function', () => {
name should be something like 'should return selected facets'

2022-06-27 10:32 UTC, kibo-sushant commented on lib/helpers/buildProductSearchInput.ts
> +}
Test case is missing

2022-06-27 10:32 UTC, kibo-sushant commented on hooks/queries/useProductSearch/useProductSearch.ts
> +}
Why are we hard coding instead of defining inside queryKeys? 
should we call  buildProductSearchInput from hook or component/page?
['productSearch', searchParams]
test cases are missing

2022-06-27 10:32 UTC, kibo-sushant commented on hooks/custom/useUpdateRoutes/useUpdateRoutes.ts
> +  }
As we are calling changeFilters from updateRoute, do we need to expose/return updateRoute ?

2022-06-27 11:11 UTC, kibo-sushant commented on pages/product/[productCode].tsx
> +  } as CategorySearchParams)
If fallback option is true, then we should display fallback page/loading bar or we can use fallback is blocking

2022-06-28 04:39 UTC, kibo-geetanshuchhabra commented on pages/product/[productCode].tsx
> +import { CategorySearchParams } from '@/lib/types'
Resolved

2022-06-28 04:39 UTC, kibo-geetanshuchhabra commented on hooks/queries/useProductSearch/useProductSearch.ts
> +import { CategorySearchParams } from '@/lib/types'
Resolved

2022-06-28 04:39 UTC, kibo-geetanshuchhabra commented on components/common/FilterTiles/FilterTiles.tsx
> +    updateRoute(tile as string)
Resolved

2022-06-28 04:40 UTC, kibo-geetanshuchhabra commented on components/FullWidthDivider.tsx
> +  // sx= {{width: '100vw',position: 'relative', marginLeft: {md: '-51vw', xs: '-50vw'},left: '50%'}}
Resolved

2022-06-28 04:40 UTC, kibo-geetanshuchhabra commented on __mocks__/stories/appliedFiltersMock.ts
> +]
Resolved

2022-06-29 07:17 UTC, kibo-geetanshuchhabra commented on components/FullWidthDivider.tsx
> +export default FullWidthDivider
Resolved

2022-06-29 07:17 UTC, kibo-geetanshuchhabra commented on components/common/FilterTiles/FilterTiles.tsx
> +export default FilterTiles
Resolved

2022-06-29 07:18 UTC, kibo-geetanshuchhabra commented on components/common/FilterTiles/FilterTiles.spec.tsx
> +})
Resolved

2022-06-29 07:18 UTC, kibo-geetanshuchhabra commented on components/layout/MegaMenu/MegaMenu.tsx
> +        </Link>
Resolved

2022-06-29 07:18 UTC, kibo-geetanshuchhabra commented on components/product-listing/Facet/Facet.tsx
> +import SearchBar from '@/components/common/SearchBar/SearchBar'
Resolved

2022-06-29 07:19 UTC, kibo-geetanshuchhabra commented on components/product-listing/FacetItem/FacetItem.tsx
> +        control={<Checkbox size="small" checked={isApplied} onChange={handleChange} />}
Resolved

2022-06-29 07:19 UTC, kibo-geetanshuchhabra commented on components/product-listing/FacetList/FacetList.tsx
> +import FilterTiles from '@/components/common/FilterTiles/FilterTiles'
Resolved

2022-06-29 07:19 UTC, kibo-geetanshuchhabra commented on components/product-listing/CategoryFacet/CategoryFacet.tsx
> +import { Box, Button, FormLabel, Link, Typography, SxProps, Divider } from '@mui/material'
As discussed we can use mui link.

2022-06-29 07:19 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +                        >
Resolved(Already written).

2022-06-29 07:19 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.tsx
> +              )}
Resolved

2022-06-29 07:19 UTC, kibo-geetanshuchhabra commented on components/page-templates/ProductListingTemplate/ProductListingTemplate.stories.tsx
> +  appliedFilters: appliedFiltersMock,
Resolved

2022-06-29 07:20 UTC, kibo-geetanshuchhabra commented on lib/api/handlers/search.ts
> +    const response = await productSearch(req.query as unknown as CategorySearchParams)
yes

2022-06-29 07:20 UTC, kibo-geetanshuchhabra commented on lib/getters/__tests__/facetGetters.spec.js
> +  it('should call getSelectedFacets function', () => {
Resolved

2022-06-29 07:20 UTC, kibo-geetanshuchhabra commented on lib/helpers/buildProductSearchInput.ts
> +}
Resolved

2022-06-29 07:20 UTC, kibo-geetanshuchhabra commented on hooks/queries/useProductSearch/useProductSearch.ts
> +}
Resolved

2022-06-29 07:20 UTC, kibo-geetanshuchhabra commented on hooks/custom/useUpdateRoutes/useUpdateRoutes.ts
> +  }
Resolved

2022-06-29 07:20 UTC, kibo-geetanshuchhabra commented on pages/category/[categoryCode].tsx
>      </>
Resolved

2022-06-29 07:20 UTC, kibo-geetanshuchhabra commented on pages/product/[productCode].tsx
> +  } as CategorySearchParams)
As discussed we required ticket in future for creating fallback page.

2022-06-30 02:54 UTC, kibo-kevinwatts approved these changes

2022-06-30 05:05 UTC, merged