order history component
KiboSoftware/nextjs-storefront pull request #76
Opened 2022-07-04 06:48 UTC by kibo-sushant

2022-07-05 16:14 UTC, kibo-kevinwatts requested changes
few small tweaks, but this looks good!

2022-07-05 16:14 UTC, kibo-kevinwatts commented on __test__/e2e/integration/order-status/ViewOrderStatus/ViewOrderStatus.spec.tsx
> +  it('should display "Billing Email must be a valid email" message when user enters invalid Billing Email', async () => {
I would recommend making these more generic instead of including the actual message content. for example
`should display invalid message when user enters invalid Billing Email` 
`should display required message when user does not enters Billing Email'`

2022-07-05 16:14 UTC, kibo-kevinwatts commented on components/order-status/ViewOrderStatus/ViewOrderStatus.tsx
> +  onOrderStatusSubmit: (data: { [x: string]: string }) => void
lets define/use a type for the data instead of [x: string]: string

2022-07-06 07:14 UTC, kibo-sushant commented on public/locales/en/orderhistory.json
> +  "simply-enter-your-order-number-and-billing-email-to-track-your-order": "Simply enter your order number and billing email to track your order.",
resolved

2022-07-06 07:14 UTC, kibo-sushant commented on components/order-status/ViewOrderStatus/ViewOrderStatus.tsx
> +    console.log(`formData: ${JSON.stringify(formData)}`)
resolved

2022-07-06 07:15 UTC, kibo-sushant commented on components/order-status/ViewOrderStatus/ViewOrderStatus.tsx
> +  const onValid = async (formData: { [x: string]: string }) => {
resolved

2022-07-06 07:15 UTC, kibo-sushant commented on __test__/e2e/integration/order-status/ViewOrderStatus/ViewOrderStatus.spec.tsx
> +  it('should display "Billing Email must be a valid email" message when user enters invalid Billing Email', async () => {
resolved

2022-07-06 07:15 UTC, kibo-sushant commented on components/order-status/ViewOrderStatus/ViewOrderStatus.tsx
> +  onOrderStatusSubmit: (data: { [x: string]: string }) => void
resolved

2022-07-06 07:37 UTC, TriptiVermaXP approved these changes

2022-07-06 20:03 UTC, kibo-kevinwatts approved these changes

2022-07-07 03:08 UTC, merged