feat(carousel): Feature/ICKY 649 carousel component
KiboSoftware/nextjs-storefront pull request #83
Opened 2022-07-13 02:46 UTC by kibo-Kripa

Home page Kibo hero Carousel component

2022-07-13 05:40 UTC, kibo-chandradeeptalaha commented on components/home/Carousel/KiboHeroCarousel.tsx
> +import CardContent from '@mui/material/CardContent'
import { Card , CardContent, Typography, Button, useMediaQuery } from '@mui/material'

2022-07-13 05:41 UTC, kibo-chandradeeptalaha commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    margin: '20px',
is this responsive ?

2022-07-13 05:41 UTC, kibo-chandradeeptalaha commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    color: '#494949',
use colors from theme only

2022-07-13 05:41 UTC, kibo-chandradeeptalaha commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    height: '600px',
is this responsive ?

2022-07-13 05:41 UTC, kibo-chandradeeptalaha commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    backgroundColor: 'white',
use common.white and common.black

2022-07-13 05:42 UTC, kibo-chandradeeptalaha commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    backgroundColor: 'white',
use common.white and common.black

2022-07-13 05:42 UTC, kibo-chandradeeptalaha commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    backgroundColor: '#A12E87',
use from theme

2022-07-13 05:44 UTC, kibo-chandradeeptalaha commented on components/home/Carousel/KiboHeroCarousel.tsx
> +  const mobileView = useMediaQuery('(min-width:600px)')
max-width: 900px is mobile view.

2022-07-13 05:45 UTC, kibo-chandradeeptalaha commented on components/home/Carousel/KiboHeroCarousel.tsx
> +          <a href="#home" style={{ color: 'white' }}>
link should be outside of text

2022-07-13 20:43 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +import CardContent from '@mui/material/CardContent'
done

2022-07-13 20:43 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    margin: '20px',
yes, it's responsive

2022-07-13 20:43 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    color: '#494949',
done

2022-07-13 20:43 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    backgroundColor: 'white',
done

2022-07-13 20:43 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    backgroundColor: 'white',
done

2022-07-13 20:44 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +  const mobileView = useMediaQuery('(min-width:600px)')
Changed

2022-07-13 20:44 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +          <a href="#home" style={{ color: 'white' }}>
done

2022-07-15 00:07 UTC, kibo-kevinwatts requested changes

2022-07-15 00:07 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +  })
Don't think we need this many "render" unit tests, one focused on render and three on functionality

it('should render component', () => { })
it('should move to next slide', () => { })
it('should move to previous slide', () => { })
it('should redirect on button click', () => { })

2022-07-15 00:07 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +      expect(screen.getByRole('button', { name: 'Shop Holiday Items on Sale' })).toBeInTheDocument()
don't hardcode text here

2022-07-15 00:07 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +      const link = screen.getAllByText(/Shop Sale/i)
don't hardcode text, you can configure the props for the story and then reuse for tests

2022-07-15 00:07 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.tsx
> +/** @format */
remove this, may need to configure your prettier extension to not insert this

2022-07-19 18:15 UTC, kibo-Kripa commented on styles/theme.ts
> +  30: '#494949',
Done

2022-07-19 18:16 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +function Project({ item }: any) {
Done

2022-07-19 18:16 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +      <CardContent sx={styles.topStyle}>
done

2022-07-19 18:16 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +          <Button variant="contained" sx={{ fontSize: mobileView ? '0.5rem' : '1rem' }}>
Done

2022-07-19 18:16 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +            {item.name}
Done

2022-07-19 18:16 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +            <a href="#home" style={{ color: 'white' }}>
Done

2022-07-19 18:17 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    <Card sx={styles.contentStyle} style={{ backgroundImage: `url(${item.href})` }}>
Done

2022-07-19 18:17 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    <div style={styles.mainStyle}>
Done

2022-07-19 18:17 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +const KiboHeroCarousel = () => {
Done

2022-07-19 18:17 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +    mobileImageUrl: 'https://i.pinimg.com/736x/04/96/05/04960532dffffe5e551b3fab6015a874.jpg',
Done

2022-07-19 18:17 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +  })
Done

2022-07-25 23:55 UTC, kibo-kevinwatts requested changes

2022-07-25 23:55 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.tsx
> +const KiboHeroCarousel = ({ carouselItem, topProps, withcard }: HeroItemProps) => {
This is the equivalent of using `const KiboHeroCarousel = (props:any)` and not how you want to define props for components.

We don't need the topProps / withCard prop. That is not part of the hero carousel component
The props should just be a list of carousel items (type you defined as ItemProps)

```
export interface HeroCarouselProps { 
     carouselItems: ItemProps[]
}
const KiboHeroCarousel = ({ carouselItems }: HeroCarouselProps) => {

}
```

2022-07-25 23:55 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.tsx
> +  component?: string
component?: string
  topProps: TopProps
  withcard: WithCardProps
  
are un needed

2022-07-25 23:55 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.tsx
> +              component={component}
this isn't quite what we discussed about using the next/link component.

Can we just add an "onClick" handler instead and do "onClick={ () => { router.push(buttonLink) } }"?

2022-07-25 23:55 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.tsx
> +function HeroItem({ props, topProps, withcard }: HeroItemProps) {
As defined, `HeroItemProps` is the equivalent to "any"
Avoid "any" when defining component props

Avoid naming a property of props, props. Thats the equivalent of doing `Component = (props) => { props.props }`
If "topProps, withcard" were required, they should be with the other "props"

Component signature should look like:
`function HeroItem(props: ItemProps) {`

I do not think we need topProps and withCard at all

2022-07-28 14:08 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +    it('should  redirect on button click', async () => {
Resolved

2022-07-28 14:09 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +const KiboHeroCarousel = ({ carouselItem, topProps, withcard }: HeroItemProps) => {
Done

2022-07-28 14:09 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.tsx
> +              component={component}
Done

2022-08-01 21:21 UTC, kibo-kevinwatts requested changes
left some comments on the unit test, rest looks good to me

2022-08-01 21:21 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +describe('checkout Component', () => {
test name should match component name

2022-08-01 21:21 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +  describe('checkout', () => {
this describe is unnecessary

2022-08-01 21:21 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +    it('mobile', async () => {
"mobile" is not detailed enough for test case name
   
   ` it("should [expected behaviour] when [scenario/context]", () => {});`

2022-08-01 21:21 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +    it('Desktop', async () => {
'Desktop' is not detailed enough for name.

use this for a template 
`    it("should [expected behaviour] when [scenario/context]", () => {}); `

2022-08-01 21:21 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +      expect(description[0]).toHaveStyle('font-size: 0.75rem')
we don't care much about the font size for responsive tests, its not related to the functionality of this component.

Since we are passing in mobile and desktop images as a prop, we care about that functionality for mobile vs desktop

2022-08-03 01:59 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +describe('checkout Component', () => {
Done

2022-08-03 01:59 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +  describe('checkout', () => {
done

2022-08-03 01:59 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +    it('mobile', async () => {
done

2022-08-03 01:59 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +    it('Desktop', async () => {
done

2022-08-03 01:59 UTC, kibo-Kripa commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +      expect(description[0]).toHaveStyle('font-size: 0.75rem')
done

2022-08-04 20:26 UTC, kibo-kevinwatts requested changes

2022-08-04 20:26 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +  })
nice!

2022-08-04 20:26 UTC, kibo-kevinwatts commented on components/home/Carousel/KiboHeroCarousel.spec.tsx
> +describe('checkout Component', () => {
I think you forgot to include this change in your commit, please update test case name

2022-08-09 21:27 UTC, kibo-kevinwatts approved these changes

2022-08-09 21:28 UTC, merged