feat(search): integrate nextjs search page and route
KiboSoftware/nextjs-storefront pull request #84
Opened 2022-07-15 08:23 UTC by kibo-geetanshuchhabra

2022-07-15 21:55 UTC, kibo-kevinwatts requested changes

2022-07-15 21:55 UTC, kibo-kevinwatts commented on pages/search.tsx
> +  category: { categories: PrCategory[] }
we shouldnt need the category for this page

2022-07-15 21:55 UTC, kibo-kevinwatts commented on pages/search.tsx
> +  const category = await categoryTreeSearchByCode(context.query)
we shouldnt need the category for this page

2022-07-15 21:55 UTC, kibo-kevinwatts commented on components/common/SearchBar/SearchBar.tsx
> +  onKeyEnter: (searchText: string) => void
onKeyEnter should be optional

2022-07-15 21:55 UTC, kibo-kevinwatts commented on __test__/unit/pages/searchPage.spec.js
> +    nextRouter.useRouter.mockImplementation(() => ({ asPath: '/search?search=jacket' }))
Is this to mock the initial router location?
Look into a cleaner / more standard approach in the testing library
https://testing-library.com/docs/example-react-router/

2022-07-15 21:55 UTC, kibo-kevinwatts commented on pages/search.tsx
> +  const [searchParams, setSearchParams] = useState<string>(router.asPath.split('?')[1])
Is this the same approach we used for category product listing? using `router.asPath` instead of router.query?
We should keep them consistent and makes more sense to use .query instead

2022-07-15 21:55 UTC, kibo-kevinwatts commented on pages/search.tsx
> +  }, [router.asPath.split('?')[1]])
shouldn't we use router.query?

2022-07-15 21:55 UTC, kibo-kevinwatts commented on __test__/e2e/integration/layout/SearchSuggestions/SearchSuggestions.spec.tsx
> +const useRouter = jest.spyOn(require('next/router'), 'useRouter')
why spy on it and add new mockImplementation if we're not checking if the push is called?

2022-07-20 11:23 UTC, kibo-geetanshuchhabra commented on __test__/e2e/integration/layout/SearchSuggestions/SearchSuggestions.spec.tsx
> +const useRouter = jest.spyOn(require('next/router'), 'useRouter')
Resolved

2022-07-20 11:23 UTC, kibo-geetanshuchhabra commented on pages/search.tsx
> +  }, [router.asPath.split('?')[1]])
Resolved

2022-07-20 11:23 UTC, kibo-geetanshuchhabra commented on pages/search.tsx
> +  const [searchParams, setSearchParams] = useState<string>(router.asPath.split('?')[1])
Resolved

2022-07-20 11:24 UTC, kibo-geetanshuchhabra commented on components/common/SearchBar/SearchBar.tsx
> +  onKeyEnter: (searchText: string) => void
Resolved

2022-07-20 11:24 UTC, kibo-geetanshuchhabra commented on pages/search.tsx
> +  const category = await categoryTreeSearchByCode(context.query)
Resolved

2022-07-20 11:24 UTC, kibo-geetanshuchhabra commented on pages/search.tsx
> +  category: { categories: PrCategory[] }
Resolved

2022-07-20 11:24 UTC, kibo-geetanshuchhabra commented on components/product-listing/Facet/Facet.tsx
> +            onKeyEnter={() => null}
Resolved.(remove this unwanted code).

2022-07-21 23:23 UTC, kibo-kevinwatts approved these changes

2022-07-22 03:33 UTC, kibo-chandradeeptalaha approved these changes

2022-07-22 05:25 UTC, merged