feature(fulfillment): pdp fulfillment option implementation
KiboSoftware/nextjs-storefront pull request #85
Opened 2022-07-15 12:04 UTC by kibo-chandradeeptalaha

2022-07-15 22:21 UTC, kibo-kevinwatts requested changes

2022-07-15 22:21 UTC, kibo-kevinwatts commented on hooks/custom/useProductDetailTemplate/useProductDetailTemplate.ts
> +      location: {},
Do we need the full "location" object here? maybe the locationCode is enought

2022-07-15 22:21 UTC, kibo-kevinwatts commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +import { StoreLocatorDialog } from '@/components/dialogs/Store'
lets add 'StoreLocatorDialog' to the ' components/dialogs' export

2022-07-15 22:21 UTC, kibo-kevinwatts commented on components/layout/AppHeader/KiboHeader.tsx
> +            setOrDeleteCookie(selectedStore?.name as string)
not related to this PR, but we need to modify `setOrDeleteCookie`. 
Unclear on the parameters and whether it is "setting" or "deleting"

2022-07-15 22:21 UTC, kibo-kevinwatts commented on components/dialogs/Store/MyStoreDialog/MyStoreDialog.tsx
> +          setOrDeleteCookie(selectedStore?.name as string)
again, 'setOrDeleteCookie' is confusing. We should be storing the "locatin.code" if anything, not name

2022-07-15 22:21 UTC, kibo-kevinwatts commented on components/common/FulfillmentOptions/FulfillmentOptions.tsx
> +  const shipFulfillment = publicRuntimeConfig.fullfillmentOptions[0].shortName
what if config is updated and "ship" is not the first option in the array?

2022-07-15 22:21 UTC, kibo-kevinwatts commented on components/common/FulfillmentOptions/FulfillmentOptions.tsx
> +import getConfig from 'next/config'
Try to remove the dependency on 'next/config' since this is a lower level component.
you're already passing in the fulfillment options, can probably pass the rest of the data needed

2022-07-15 22:21 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/ProductDetailTemplate/ProductDetailTemplate.spec.tsx
> +  it('should handle fulfillment option and adding item to cart', async () => {
just a suggestion. `should add ship to home item to cart`

2022-07-18 17:16 UTC, kibo-chandradeeptalaha commented on hooks/custom/useProductDetailTemplate/useProductDetailTemplate.ts
> +      location: {},
As discussed, keeping as object.

2022-07-18 17:30 UTC, kibo-chandradeeptalaha commented on components/common/FulfillmentOptions/FulfillmentOptions.tsx
> +import getConfig from 'next/config'
Done

2022-07-18 17:30 UTC, kibo-chandradeeptalaha commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +import { StoreLocatorDialog } from '@/components/dialogs/Store'
Done

2022-07-18 18:30 UTC, kibo-kevinwatts reviewed
One last change
@kibo-chandradeeptalaha  create a constant for 'Pickup' and 'Ship' so we don't have a headache later. should already have constant file under lib

```const FULFILLMENT_METHOD = {
    SHIP: "Ship",
    PICKUP: "Pickup"
}```

2022-07-19 14:06 UTC, kibo-kevinwatts approved these changes

2022-07-20 10:44 UTC, kibo-sushant commented on hooks/queries/useStoreLocations/useStoreLocations.ts
> +    () => (Boolean(searchParams.filter) ? getStoreLocations(searchParams) : {})
I think instead of using condition here we should use enabled prop

2022-07-20 10:44 UTC, kibo-sushant commented on hooks/queries/usePurchaseLocation/usePurchaseLocation.ts
> +    () => (param ? getPurchaseLocation(param) : {})
I think instead of using condition here we should use enabled prop

2022-07-20 10:44 UTC, kibo-sushant commented on lib/constants/index.ts
> +  PICKUP = 'Pickup',
It should not be part of FormStates, create separate object ex. shippingTypes or shippingOptions

2022-07-20 10:44 UTC, kibo-sushant commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +      location: value === 'Pickup' ? storeLocationGetters.getLocation(purchaseLocation) : undefined,
Wouldn't it be nice if will declare Const in lib and use it here instead of hard coding values?

2022-07-20 11:32 UTC, kibo-chandradeeptalaha commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +      location: value === 'Pickup' ? storeLocationGetters.getLocation(purchaseLocation) : undefined,
Resolved in Tripti's PR

2022-07-20 11:32 UTC, kibo-chandradeeptalaha commented on lib/constants/index.ts
> +  PICKUP = 'Pickup',
Resolved in Tripti's PR

2022-07-20 11:33 UTC, kibo-chandradeeptalaha commented on hooks/queries/useStoreLocations/useStoreLocations.ts
> +    () => (Boolean(searchParams.filter) ? getStoreLocations(searchParams) : {})
I think enabled is used for refetch and we don't have that requirement here. We tried this approach as well in different scenario. didn't work.

2022-07-20 11:33 UTC, kibo-chandradeeptalaha commented on hooks/queries/usePurchaseLocation/usePurchaseLocation.ts
> +    () => (param ? getPurchaseLocation(param) : {})
I think enabled is used for refetch and we don't have that requirement here. We tried this approach as well in different scenario. didn't work.

2022-07-21 09:25 UTC, kibo-sushant commented on hooks/queries/useStoreLocations/useStoreLocations.ts
> +    () => (Boolean(searchParams.filter) ? getStoreLocations(searchParams) : {})
Enabled is used for conditional fetching, I think this is the right example we can use it.

2022-07-21 09:25 UTC, kibo-sushant commented on hooks/queries/usePurchaseLocation/usePurchaseLocation.ts
> +    () => (param ? getPurchaseLocation(param) : {})
Enabled is used for conditional fetching, I think this is the right example we can use it.

2022-07-21 09:28 UTC, kibo-sushant approved these changes

2022-07-21 09:34 UTC, merged