feat: implement update cart quantity and delete cart item
KiboSoftware/nextjs-storefront pull request #86
Opened 2022-07-15 14:45 UTC by sss-bct

2022-07-15 16:33 UTC, sss-bct commented
Development is done, after review will add test cases.

2022-07-15 22:38 UTC, kibo-kevinwatts reviewed
good job @sss-bct!

2022-07-15 22:38 UTC, kibo-kevinwatts commented on hooks/mutations/useCheckoutMutation/useCheckoutMutation.tsx
> +export const useCheckoutMutation = () => {
this mutation doesn't really belong to "checkout" or "cart"
rename to "useCreateFromCartMutation"
like 
```
export const useCreateFromCartMutation = () => { 
  return {
    createFromCart: useMutation(getOrCreateCheckout)
  }
}
```

thoughts @kibo-sushant ?

2022-07-15 22:38 UTC, kibo-kevinwatts commented on components/common/QuantitySelector/QuantitySelector.tsx
> +const QuantityTextField = ({ quantity, handleCustomQuantity }: QuantityInputProps) => {
how does 'handleCustomQuantity' differ from 'setItemQuantity'?

2022-07-20 17:28 UTC, sss-bct commented on hooks/mutations/useCheckoutMutation/useCheckoutMutation.tsx
> +export const useCheckoutMutation = () => {
Ok. Resolved.

2022-07-20 17:34 UTC, sss-bct commented on components/common/QuantitySelector/QuantitySelector.tsx
> +const QuantityTextField = ({ quantity, handleCustomQuantity }: QuantityInputProps) => {
handleCustomQuantity is a callback through props to make API call happen from parent where as setItemQuantity is used to update an internal state of quantity to make QuantityTextField a controlled one.

2022-07-21 09:57 UTC, kibo-sushant commented on hooks/mutations/useCartMutation/useCartMutation.ts
> +}
We already have global error handler, do we need to use Try Catch block here?

2022-07-21 09:57 UTC, kibo-sushant commented on hooks/mutations/useCartMutation/useCartMutation.ts
> +    }),
I think we should follow the single responsibility principle here.
One custom hook should have one responsiblity, need to break hooks separate files

2022-07-21 13:44 UTC, sss-bct commented on components/common/QuantitySelector/QuantitySelector.tsx
> +  const [itemQuantity, setItemQuantity] = useState<number | string>(quantity)
value coming from event.target is a string, for that it's required.

2022-07-21 13:45 UTC, sss-bct commented on hooks/mutations/useCartMutation/useCartMutation.ts
> +}
Removed.

2022-07-21 13:48 UTC, sss-bct commented on hooks/mutations/useCartMutation/useCartMutation.ts
> +    }),
But it is working fine and each mutation is taking single responsibility here. As we decided I followed this approach, if you think it's mandatory I will update.

2022-07-21 16:01 UTC, kibo-sushant commented on hooks/mutations/useCartMutation/useCartMutation.ts
> +    }),
Small code is always easy to understand and more maintainable. One file should have only one hook and one hook should have only one responsibility.

2022-07-21 16:05 UTC, sss-bct commented on hooks/mutations/useCartMutation/useCartMutation.ts
> +    }),
I will break it up and all the remaining items will be coved as well.

2022-07-21 16:08 UTC, kibo-sushant approved these changes

2022-07-25 21:21 UTC, kibo-kevinwatts requested changes

2022-07-25 21:21 UTC, kibo-kevinwatts commented on components/common/QuantitySelector/QuantitySelector.tsx
> +  }, [quantity])
I don't think we need this, quantity is coming in as prop and assigned to state

2022-07-25 21:21 UTC, kibo-kevinwatts commented on components/common/QuantitySelector/QuantitySelector.tsx
> +  }, [quantity])
Agree with sushant, i don't think the validation for the quantity is correct here.

2022-07-25 21:21 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.js
> +  })
test case for decrease quantity?

2022-07-26 13:02 UTC, sss-bct commented on hooks/mutations/useCartMutation/useCartMutation.ts
> +import { CartItem, ProductOption } from '@/lib/gql/types'
Done

2022-07-26 13:04 UTC, sss-bct commented on components/common/QuantitySelector/QuantitySelector.tsx
> +  }, [quantity])
Actually it was not  rendering automatically after API response but found a solution with key. So Remove. Thank you.

2022-07-26 13:44 UTC, sss-bct commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.js
> +  })
Done.

2022-07-26 18:34 UTC, kibo-kevinwatts approved these changes

2022-07-27 03:03 UTC, merged