Feature/icky 656
KiboSoftware/nextjs-storefront pull request #88
Opened 2022-07-19 16:50 UTC by amolpawar-kibo

2022-07-19 22:39 UTC, kibo-kevinwatts commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +      if (isAuthenticated) {
Nitpick: this code can be simplified / improve readiblity by using less nested if/else

```
if (!isAuthenticated) {
  showModal({ Component: LoginDialog });
  return;
}
if (!isProductInWishlist) {
  await addToWishlist.mutateAsync({
    ...variables,
    customerAccountId: customerAccount?.id,
  });
} else {
  await removeWishlistItem.mutateAsync(variables);
}

showModal({
  Component: WishlistPopover,
  props: {
    isInWishlist: !isProductInWishlist,
    target: wislistButton,
  },
});```

2022-07-19 22:41 UTC, kibo-kevinwatts commented on components/dialogs/Wishlist/WishlistPopover/WishlistPopover.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(target)
what is anchorEl used for?

2022-07-19 22:43 UTC, kibo-kevinwatts commented on hooks/mutations/useWishlistMutation/useWishlistMutation.ts
> +    addToWishlist: useMutation(addToWishlist, {
@kibo-sushant Do we want to break this out into two separate hooks? "addToWishlist" and "removeWishlistItem"?

2022-07-20 05:10 UTC, amolpawar-kibo commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +      if (isAuthenticated) {
Done.

2022-07-20 07:28 UTC, amolpawar-kibo commented on hooks/mutations/useWishlistMutation/useWishlistMutation.ts
> +    addToWishlist: useMutation(addToWishlist, {
Done.

2022-07-20 07:28 UTC, amolpawar-kibo commented on components/dialogs/Wishlist/WishlistPopover/WishlistPopover.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(target)
Resolved. Removed anchorEl

2022-07-21 06:51 UTC, kibo-sushant commented on components/dialogs/Wishlist/WishlistPopover/WishlistPopover.stories.tsx
> +}
Need to fix 'View WishList' button alignment issues in Storybook 
.Spec file missng

2022-07-21 06:51 UTC, kibo-sushant commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +import WishlistPopover from '@/components/dialogs/Wishlist/WishlistPopover/WishlistPopover'
Not using index file?

2022-07-21 06:51 UTC, kibo-sushant commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +import FavoriteRoundedIcon from '@mui/icons-material/FavoriteRounded'
can we import both in single line?

2022-07-21 06:51 UTC, kibo-sushant commented on components/dialogs/Wishlist/WishlistPopover/WishlistPopover.tsx
> +import FavoriteRoundedIcon from '@mui/icons-material/FavoriteRounded'
can we import both icons in single line?

2022-07-21 06:51 UTC, kibo-sushant commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +
I think instead of building variable here we should use lib/helper function
Create smaller functions with single responsiblity something like below
Also we are catching error but not consoling it.

handleWishList = ()=>{  (isAuthinticated) ? updateWishList() : showLoginDialog() }

const updateWishList = ()=> {
        const variables = buildWishlistParams(product)
	if (!isProductInWishlist) {	...  } else {	...   }
}
const showLoginDialog =()=> {}

2022-07-21 06:51 UTC, kibo-sushant commented on context/AuthContext.tsx
> +    queryClient.invalidateQueries(wishlistKeys.all)
By default, queries are gets automatically invalidated on 0th second, do we need to invalidate it manually here?
Also non logged in user will not have a wishlist, after login successfully will it be there anything to invalidate?

2022-07-21 06:51 UTC, kibo-sushant commented on hooks/mutations/useWishlist/useAddToWishlistMutation/useAddToWishlistMutation.ts
> +}
Remove the Mutation suffix from the hook
Instead of invalidating the query, remove it from the cache
missing Spec

2022-07-21 06:51 UTC, kibo-sushant commented on hooks/mutations/useWishlist/useRemoveWishlistItemMutation/useRemoveWishlistItemMutation.ts
> +}
Remove the Mutation suffix from the hook
Instead of invalidating the query, remove it from the cache
missing Spec

2022-07-21 06:51 UTC, kibo-sushant commented on hooks/queries/useWishlist/useWishlistQueries.ts
> +}
missing Spec

2022-07-21 06:51 UTC, kibo-sushant commented on lib/getters/wishlistGetters.ts
> +}
Instead of if (currentWishlist) {}, 
use 
 if(!currentWishlist) return 
 return currentWishlist?.items?...

2022-07-21 06:51 UTC, kibo-sushant commented on next.config.js
> +    defaultWishlistName: 'default-wishlist',
Both storeLocationCookie and defaultWishlistName we should use same approach

2022-07-22 04:29 UTC, amolpawar-kibo commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +import FavoriteRoundedIcon from '@mui/icons-material/FavoriteRounded'
Both the icons has not exported member  of '"@mui/icons-material"'

2022-07-22 04:29 UTC, amolpawar-kibo commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +import WishlistPopover from '@/components/dialogs/Wishlist/WishlistPopover/WishlistPopover'
Done

2022-07-22 04:34 UTC, amolpawar-kibo commented on components/dialogs/Wishlist/WishlistPopover/WishlistPopover.tsx
> +import FavoriteRoundedIcon from '@mui/icons-material/FavoriteRounded'
Both the icons has not exported member of '"@mui/icons-material"'

2022-07-22 04:42 UTC, amolpawar-kibo commented on next.config.js
> +    defaultWishlistName: 'default-wishlist',
DONE

2022-07-26 06:55 UTC, amolpawar-kibo commented on components/dialogs/Wishlist/WishlistPopover/WishlistPopover.stories.tsx
> +}
Done.

2022-07-26 10:17 UTC, amolpawar-kibo commented on hooks/queries/useWishlist/useWishlistQueries.ts
> +}
Done.

2022-07-27 15:11 UTC, amolpawar-kibo commented on hooks/mutations/useWishlist/useRemoveWishlistItemMutation/useRemoveWishlistItemMutation.ts
> +}
All the hooks with mutation suffix should we are going to change all of them?

2022-07-27 15:13 UTC, amolpawar-kibo commented on hooks/mutations/useWishlist/useAddToWishlistMutation/useAddToWishlistMutation.ts
> +}
added spec. I think removing data from query is costly than invalidate

2022-07-27 15:15 UTC, amolpawar-kibo commented on components/dialogs/Wishlist/WishlistPopover/WishlistPopover.tsx
> +        )}{' '}
Done

2022-07-27 15:33 UTC, amolpawar-kibo commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +
Done. Moved variable creation into helpers

2022-07-28 17:44 UTC, kibo-kevinwatts requested changes

2022-07-28 17:44 UTC, kibo-kevinwatts commented on hooks/mutations/useWishlist/useAddToWishlistMutation/useAddToWishlistMutation.ts
> +}
I still see the "Mutation" suffix in the name of the hook

2022-07-28 17:44 UTC, kibo-kevinwatts commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +
I don't see the variable creation helpers being used.

2022-07-28 17:44 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/ProductDetailTemplate/ProductDetailTemplate.spec.tsx
> +  it('should use useAuthContext when login button clicked', async () => {
Test case name should be more specific to wishlist
This test case also seems to be doing too much with login and using the extra mock login form.
goal should be to test adding item to wishlist

Can we force/mock the authenticated?
@kibo-sushant what are we doing in other places to mock authenticated users?

2022-07-29 04:12 UTC, amolpawar-kibo commented on hooks/mutations/useWishlist/useAddToWishlistMutation/useAddToWishlistMutation.ts
> +}
All the hooks with mutation suffix should we are going to change all of the?

2022-07-29 04:46 UTC, amolpawar-kibo commented on components/page-templates/ProductDetail/ProductDetailTemplate.tsx
> +
Apologies for the mistake, I had assumption that I have created for this but I did for all wishlist mutation.

2022-07-29 05:17 UTC, amolpawar-kibo commented on __test__/e2e/integration/page-template/ProductDetailTemplate/ProductDetailTemplate.spec.tsx
> +  it('should use useAuthContext when login button clicked', async () => {
1. I still see the "Mutation" suffix in the name of the hook
- Existing hooks with mutation suffix. Should we are going to change all of them?
2. I don't see the variable creation helpers being used.
- Apologies for the mistake, I had assumption that I have created for this but I did for all wishlist mutations.

2022-08-01 22:54 UTC, kibo-kevinwatts approved these changes

2022-08-01 22:54 UTC, kibo-kevinwatts commented on hooks/mutations/useWishlist/useAddToWishlistMutation/useAddToWishlistMutation.spec.ts
> +  it('should use useAddToWishlistMutation', async () => {
it('should add item to wishlist')

2022-08-01 22:54 UTC, kibo-kevinwatts commented on hooks/mutations/useWishlist/useCreateWishlistMutation/useCreateWishlistMutation.spec.ts
> +  it('should use useCreateWishlistMutation', async () => {
it('should create wishlist')

2022-08-03 04:38 UTC, merged