feat(fulfillment): icky-574 fulfillment option implementation on cart
KiboSoftware/nextjs-storefront pull request #90
Opened 2022-07-21 11:17 UTC by TriptiVermaXP

2022-07-26 22:15 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    server.resetHandlers(
server.resetHandlers like this will remove all previously assigned handlers, is that intended?
`server.use( graphql.mutation('updateCurrentCartItem', (_req, res, ctx) => {}))` will override the request, which is what i think you want

2022-07-26 22:21 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    await user.click(pickupRadio[1])
I walked through debugging this, the onChange handler is not getting called. It is already set to pickup.
Don't grab the radio button by index, get radio button that is not selected instead

2022-07-26 22:22 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    expect(pickupRadio[1]).toBeChecked()
This test is also throwing an exception for "showModal" is not a function as well. 
Do we need to add the Modal Context for these test suites as well?

2022-07-28 21:57 UTC, kibo-kevinwatts requested changes

2022-07-28 21:57 UTC, kibo-kevinwatts commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +        .map((code) => `code eq ${code}`)
We may need this same logic on checkout, we should move to a getter 
Use the constant, don't hardcode 'Pickup'
 
This is just a nitpick comment, because the number of items will never be that big 
but this can be simplified/faster and done in one iteration 
```
const locationCodes = Array.from(cartItems.reduce((set, item) => {
    if(item.fulfillmentMethod === "Ship"){
        set.add(`code eq ${item.fulfillmentLocationCode}`)
    }
    return set
}, new Set()))
locationCodes.join(' or ')
```

2022-07-28 21:57 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    const deletedCartItem = screen.queryByText('Pink Backpack')
try to avoid hardcoding the number "2" `expect(cartItem).toHaveLength(2)` if the data is updated, this test breaks
could we check based on the mock data?
```    expect(cartItem).toHaveLength(mockCart.items.length)```

If possible, avoid hardcoding query based on mock data text `screen.queryByText('Pink Backpack')`  

try using the mock data length for comparison
```
    const itemCount = mockCart.items.length
    const cartItem = screen.getAllByRole('group')
    expect(cartItem).toHaveLength(itemCount)
    const deleteButton = screen.getAllByRole('button', { name: 'item-delete' })
    await user.click(deleteButton[0])
    expect(cartItems).toHaveLength(itemCount - 1)
```

2022-07-28 21:57 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    await new Promise((r) => setTimeout(r, 2000))
what is this timeout/promise for?

2022-07-28 21:57 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    expect(inputs[0]).toHaveValue('2')
instead of hardcoding the quantities, can we pull them from the mocked data?

2022-07-28 21:57 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +      expect(screen.getAllByText(/Available to Ship/i)[index]).toBeVisible()
Same question @kibo-sushant had, why are we hardcoding "Available to Ship" in these tests?

2022-07-29 09:17 UTC, kibo-sushant commented on lib/getters/cartGetters.ts
> +import { FulfillmentOption } from '../types'
use type while importing

2022-07-29 10:19 UTC, kibo-sushant commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +import { renderWithQueryClient } from '@/__test__/utils/renderWithQueryClient'
use index file for importing

2022-07-29 10:19 UTC, kibo-sushant commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +  })
without server.use or server.reset handler how delete is working?

2022-07-29 10:19 UTC, kibo-sushant commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +      name: /ship to home/i,
remove hard coding

2022-07-29 10:19 UTC, kibo-sushant commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +      name: /Pickup in store/i,
remove hard coding

2022-07-29 10:19 UTC, kibo-sushant commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    expect(inputs[0]).toHaveValue('3')
Avoid hardcoding, I wonder how initial value is 3 instead of 2

2022-07-29 12:16 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    const deletedCartItem = screen.queryByText('Pink Backpack')
@sss-bct could you please take look?

2022-07-29 12:16 UTC, TriptiVermaXP commented on components/page-templates/CartTemplate/CartTemplate.tsx
> +        .map((code) => `code eq ${code}`)
Done

2022-07-29 12:16 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    await new Promise((r) => setTimeout(r, 2000))
Removed and used timeout on test closure.

2022-07-29 12:16 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    expect(inputs[0]).toHaveValue('2')
Done

2022-07-29 12:16 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +      expect(screen.getAllByText(/Available to Ship/i)[index]).toBeVisible()
Done

2022-07-29 12:16 UTC, TriptiVermaXP commented on lib/getters/cartGetters.ts
> +import { FulfillmentOption } from '../types'
Done

2022-07-29 12:17 UTC, TriptiVermaXP commented on hooks/queries/usePurchaseLocation/usePurchaseLocation.ts
> +    }
Done

2022-07-29 12:17 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/ProductDetailTemplate/ProductDetailTemplate.spec.tsx
> +    })
Done

2022-07-29 12:17 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +import { renderWithQueryClient } from '@/__test__/utils/renderWithQueryClient'
Done

2022-07-29 12:17 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +  })
@sss-bct could you please take look?

2022-07-29 12:17 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +      name: /ship to home/i,
Done

2022-07-29 12:17 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +      name: /Pickup in store/i,
Done

2022-07-29 12:17 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    expect(inputs[0]).toHaveValue('3')
Done , @sss-bct could you please take look once?

2022-07-29 14:19 UTC, TriptiVermaXP commented on components/cart/CartItem/CartItem.tsx
> +                }
Fixed except 
_Title font is too big (on cartitem template)_
Theme font radio defined in theme (for h1) is not matching with mockup.
![image](https://user-images.githubusercontent.com/61453763/181757358-7d34cf20-dbfc-4d46-82ad-c6a7b7dd8706.png)
_The selected option text is not bold_ 
not changed to make it consistent with other pages.

2022-07-29 14:19 UTC, TriptiVermaXP commented on hooks/mutations/useCartMutation/useCartMutation.ts
> +    }),
Fixed

2022-08-01 07:07 UTC, TriptiVermaXP commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +    expect(inputs[0]).toHaveValue('3')
Done

2022-08-01 22:40 UTC, kibo-kevinwatts reviewed
This looks good now, thanks for the changes.
Just need some clarity on the integration tests

2022-08-01 22:40 UTC, kibo-kevinwatts commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +  })
@kibo-sushant maybe with the optimistic update changes? is that added in this pr?

2022-08-02 11:01 UTC, sss-bct commented on __test__/e2e/integration/page-template/cart/CartTemplate.spec.tsx
> +  })
I think so, it is due to optimistic update. it's there.

2022-08-03 07:02 UTC, kibo-sushant approved these changes

2022-08-03 14:09 UTC, kibo-kevinwatts approved these changes

2022-08-04 05:48 UTC, merged