feat(my-account):  my account page layout and navigation
KiboSoftware/nextjs-storefront pull request #94
Opened 2022-07-25 13:50 UTC by kibo-geetanshuchhabra

2022-07-25 20:53 UTC, kibo-kevinwatts requested changes

2022-07-25 20:53 UTC, kibo-kevinwatts commented on components/page-templates/MyAccountTemplate/MyAccountTemplate.tsx
> +import router from 'next/router'
use 'useRouter' hook
import { useRouter } from 'next/router'

2022-07-25 20:53 UTC, kibo-kevinwatts commented on pages/my-account/index.tsx
> +export const getServerSideProps: GetServerSideProps = async (
Need to secure this page, here in "getServerSideProps" like
https://nextjs.org/docs/authentication#authenticating-server-rendered-pages

or create nextJS middleware 
https://nextjs.org/docs/advanced-features/middleware

2022-07-29 13:32 UTC, kibo-geetanshuchhabra commented on components/page-templates/MyAccountTemplate/MyAccountTemplate.tsx
> +import router from 'next/router'
Resolved

2022-07-29 13:32 UTC, kibo-geetanshuchhabra commented on pages/my-account/index.tsx
> +export const getServerSideProps: GetServerSideProps = async (
Resolved

2022-08-01 22:19 UTC, kibo-kevinwatts reviewed
this looks good to me, just not sure if those mobile / desktop tests are needed

2022-08-01 22:19 UTC, kibo-kevinwatts commented on components/page-templates/MyAccountTemplate/MyAccountTemplate.spec.tsx
> +  it('Mobile', async () => {
what is being tested in these mobile/desktop tests?

if these tests are needed, update the names 'Desktop' or 'Mobile' is not enough detail

2022-08-01 22:19 UTC, kibo-kevinwatts commented on pages/_middleware.ts
> +}
nice, will this match other my-account paths? `/my-account/order-history` ?

2022-08-03 22:22 UTC, kibo-kevinwatts approved these changes

2022-08-04 04:48 UTC, merged