feat: view and select previously saved shipping address
KiboSoftware/nextjs-storefront pull request #96
Opened 2022-07-29 10:53 UTC by sss-bct

2022-08-01 21:47 UTC, kibo-kevinwatts requested changes

2022-08-01 21:47 UTC, kibo-kevinwatts commented on components/checkout/ShippingStep/ShippingStep.tsx
> +          radioGroupTitle={'Your default silling dddress'}
use translation string
also fix 'silling' typo

2022-08-01 21:47 UTC, kibo-kevinwatts commented on components/common/AddressList/AddressList.stories.tsx
> +  radioGroupTitle: 'Your default silling address',
fix typo

2022-08-01 21:47 UTC, kibo-kevinwatts commented on components/common/AddressList/AddressList.tsx
> +  const { addresses, withoutRadioTitle } = props
Why add the extra 'withoutRadioTitle' prop? 
Can we just leave "title" null?

2022-08-01 21:47 UTC, kibo-kevinwatts commented on hooks/queries/useUserAddresses/useUserAddressQueries.ts
> +  try {
why do the try catch here?
useQuery returns an error, just return that

`const {
      data = {},
      error,
      isLoading,
      isSuccess,
    } = useQuery`

2022-08-01 21:47 UTC, kibo-kevinwatts commented on components/checkout/ShippingStep/ShippingStep.tsx
> +    // do your stuff for the selected address
shouldn't this be implemented in this pull request ?

2022-08-02 13:54 UTC, sss-bct commented on components/checkout/ShippingStep/ShippingStep.tsx
> +          radioGroupTitle={'Your default silling dddress'}
Resolved.

2022-08-02 13:55 UTC, sss-bct commented on components/common/AddressList/AddressList.stories.tsx
> +  radioGroupTitle: 'Your default silling address',
Resolved.

2022-08-02 13:55 UTC, sss-bct commented on components/common/AddressList/AddressList.tsx
> +  const { addresses, withoutRadioTitle } = props
Correct. Not required here.

2022-08-04 21:54 UTC, kibo-kevinwatts requested changes

2022-08-04 21:54 UTC, kibo-kevinwatts commented on components/checkout/ShippingStep/ShippingStep.tsx
> +        firstName: selectedAddress.firstName || '',
in addition to sending `id: selectedAddress.id`
add `contactId: selectedAddress.id`

2022-08-04 21:54 UTC, kibo-kevinwatts commented on lib/gql/fragments/userContact.ts
> +    auditInfo {
remove auditInfo, faxNumber, label, companyOrOrganization

2022-08-05 12:06 UTC, sss-bct commented on lib/gql/fragments/userContact.ts
> +    auditInfo {
Removed.

2022-08-05 12:10 UTC, sss-bct commented on components/checkout/ShippingStep/ShippingStep.tsx
> +        firstName: selectedAddress.firstName || '',
Type support is not there for contactId, should I update type for this?

2022-08-09 08:17 UTC, kibo-sushant commented on components/page-templates/Checkout/Checkout.tsx
> +    accountId: user?.id as number, // geetanshu
remove commented code

2022-08-10 07:46 UTC, sss-bct commented on __mocks__/stories/userAddressMock.ts
> +export const userAddressResponse: CustomerContactCollection = {
it's there with another export here

2022-08-10 07:46 UTC, sss-bct commented on components/common/AddressList/AddressList.tsx
> +import KiboRadio from '@/components/common/KiboRadio/KiboRadio'
Resolved.

2022-08-10 07:46 UTC, sss-bct commented on components/common/AddressList/AddressList.tsx
> +  onAddressSelection: (addressId: string) => any
Done

2022-08-10 07:46 UTC, sss-bct commented on components/common/AddressList/AddressList.tsx
> +  onAddressSelect: (addressId: string) => any
Done.

2022-08-10 07:46 UTC, sss-bct commented on components/common/AddressList/AddressList.tsx
> +const buildAddressProps = (address: CrAddress | CuAddress | any) => {
Done.

2022-08-10 07:47 UTC, sss-bct commented on components/common/AddressList/AddressList.spec.js
> +})
Handled in integration test.

2022-08-10 07:47 UTC, sss-bct commented on components/page-templates/Checkout/Checkout.tsx
> +    accountId: user?.id as number, // geetanshu
Done.

2022-08-10 07:57 UTC, kibo-sushant approved these changes

2022-08-10 12:59 UTC, kibo-kevinwatts approved these changes

2022-08-11 12:54 UTC, merged