feat(tile): feature/icky 651 large and medium homepage content tiles
KiboSoftware/nextjs-storefront pull request #97
Opened 2022-07-29 19:16 UTC by kibo-Kripa

Large and medium responsive content tiles for the home page.

2022-08-02 23:14 UTC, kibo-kevinwatts requested changes

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.tsx
> +import { Box, Link, Typography, useTheme } from '@mui/material'
use Next/Link instead of material ui link

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.tsx
> +import useMediaQuery from '@mui/material/useMediaQuery'
combine Grid and useMediaQuery imports with other material ui imports

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.tsx
> +
Checking the Design in storybook.

Title text mobile is not centered
Subtitle text is not centered
Spacing(margin up / down) between links is too small
Font weight of links looks too heavy
Images on mobile look too tall / incorrect ratio
Spacing between tiles on mobile isn’t enough, images are almost touching

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.tsx
> +  const mobileView = useMediaQuery('(max-width:600px)')
should (max-width:600px) be hardcoded here? what about using theme breakpoints?

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.tsx
> +            href="#"
links are missing href mapped to prop

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.spec.tsx
> +    it('desktop', async () => {
no need for this test

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.spec.tsx
> +    it('mobile', async () => {
no need for this test

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.spec.tsx
> +describe('checkout Component', () => {
wrong component name / wrong format for name

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.spec.tsx
> +  describe('checkout', () => {
no need for this describe

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.spec.tsx
> +const createMatchMedia = (width: number) => (query: string) => ({
no need for this helper

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.tsx
> +  link1: string
links need to support text and url. either

```
export interface TileProps {
  imgSource: string
  title: string
  subtitle: string
  link1: { title: string; url: string }
    link2: { title: string; url: string }
      link3: { title: string; url: string }
 ```
 or
```
export interface TileProps {
  imgSource: string
  title: string
  subtitle: string
  links: Array<{ title: string; url: string }>
 ```

2022-08-02 23:14 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.tsx
> +  const styles = {
try to define styles outside of the actual component
for responsive rules, look at using `styled` components

2022-08-09 22:24 UTC, kibo-kevinwatts approved these changes
Looks better! the images on storybook look good too

2022-08-09 22:24 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.tsx
> +  const LinkStyle = styled('div')({
LinkStyle should be defined outside of this component

2022-08-09 22:24 UTC, kibo-kevinwatts commented on components/home/ContentTile/ContentTile.tsx
> +              <MuiLink underline="none" component="button" sx={styles.linkStyle}>
The MuiLink nested inside of a Link seems odd

2022-08-10 07:55 UTC, kibo-sushant commented on components/home/ContentTile/ContentTile.tsx
> +  const mobileView = useMediaQuery(kiboTheme.breakpoints.down('sm'))
break point should consider table also

2022-08-10 07:55 UTC, kibo-sushant commented on components/home/ContentTile/ContentTile.spec.tsx
> +})
For title and subtitle we should use getByTitle/getAllByTitle over getAllByText
Instead of verifying just 0th element, we should verify whether all the titles/subtitles/links are rendered or not using either map or RegEx. This way we can make sure that map is working as expected

2022-08-10 07:55 UTC, kibo-sushant commented on package.json
> +    "css-mediaquery": "^0.1.2",
Where are we using this? If not using anywhere then we should remove it.

2022-08-10 07:55 UTC, kibo-sushant commented on components/home/ContentTile/ContentTile.tsx
> +
In Desktop view, as per the mockup below text should be in single line
TOP DEALS
CLUB DEALS
FOOTWEAR DEALS

https://marvelapp.com/prototype/hh42h21/screen/85859469

2022-08-10 12:41 UTC, TriptiVermaXP requested changes
Please take a look review comments.

2022-08-10 12:41 UTC, TriptiVermaXP commented on components/home/ContentTile/ContentTile.tsx
> +function ContentTile({ largeTileProps, smallTileProps }: ContentTileProps) {
For consistency, please use arrow function instead normal function

2022-08-10 12:41 UTC, TriptiVermaXP commented on components/home/ContentTile/ContentTile.tsx
> +              <MuiLink underline="none" component="button" sx={styles.linkStyle}>
Font weight should be semi bold.

2022-08-10 12:41 UTC, TriptiVermaXP commented on components/home/ContentTile/ContentTile.tsx
> +      <Box sx={styles.boxStyle}>
Space between image and title mismatching with mockup.

2022-08-10 12:41 UTC, TriptiVermaXP commented on components/home/ContentTile/ContentTile.tsx
> +            }}
To apply fontSize on typography, we can use _variant="h2"_

2022-08-10 22:12 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +  const LinkStyle = styled('div')({
Done

2022-08-10 22:12 UTC, kibo-Kripa commented on package.json
> +    "css-mediaquery": "^0.1.2",
Done

2022-08-10 22:13 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +
In Figma, those are not in single line

https://www.figma.com/file/fQA8Bf38pHL74vWqvXxcRh/Headless-Homepage?node-id=2%3A4

2022-08-10 22:13 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +function ContentTile({ largeTileProps, smallTileProps }: ContentTileProps) {
Done

2022-08-10 22:13 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +      <Box sx={styles.boxStyle}>
Done

2022-08-10 22:14 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +            }}
Done

2022-08-12 16:08 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +import { Box, Link, Typography, useTheme } from '@mui/material'
Done

2022-08-12 16:08 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +import useMediaQuery from '@mui/material/useMediaQuery'
Done

2022-08-12 16:08 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +
Done

2022-08-12 16:08 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +  const mobileView = useMediaQuery('(max-width:600px)')
Done

2022-08-12 16:08 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +            href="#"
Done

2022-08-12 16:09 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.spec.tsx
> +    it('desktop', async () => {
Done

2022-08-12 16:09 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.spec.tsx
> +    it('mobile', async () => {
Done

2022-08-12 16:09 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.spec.tsx
> +describe('checkout Component', () => {
Done

2022-08-12 16:09 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.spec.tsx
> +  describe('checkout', () => {
Done

2022-08-12 16:09 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.spec.tsx
> +const createMatchMedia = (width: number) => (query: string) => ({
Done

2022-08-12 16:09 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +  link1: string
Done

2022-08-12 16:10 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +  const styles = {
Done

2022-08-12 16:10 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +  const mobileView = useMediaQuery(kiboTheme.breakpoints.down('sm'))
Done

2022-08-12 16:10 UTC, kibo-Kripa commented on components/home/ContentTile/ContentTile.tsx
> +  const mobileView = useMediaQuery(kiboTheme.breakpoints.down('sm'))
Done

2022-08-16 15:46 UTC, TriptiVermaXP approved these changes

2022-08-16 18:21 UTC, merged