feat: icky-592 (checkout payment)
KiboSoftware/nextjs-storefront pull request #98
Opened 2022-08-01 11:41 UTC by kibo-chandradeeptalaha

2022-08-01 23:39 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  CardTypeForCheckout,
should this type be moved to lib/types?

2022-08-01 23:39 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  const { checkout, isUserLoggedIn = false } = props
since we have useAuthContext now, don't think we need "isUserLoggedIn" as prop

2022-08-01 23:39 UTC, kibo-kevinwatts commented on lib/getters/accountDetailsGetters.ts
> +}
should we split these getters into multiple files? There is a mixture of customer account, billing address and card getters in this.

2022-08-01 23:39 UTC, kibo-kevinwatts commented on components/common/AddressForm/AddressForm.tsx
> +    reset(contact)
contact is the prop, why is the reset needed here?

2022-08-01 23:39 UTC, kibo-kevinwatts commented on components/order/view-order-details/ViewOrderDetails.tsx
> +              postalOrZipCode={
using some of the getters could clean this up

2022-08-02 09:38 UTC, kibo-chandradeeptalaha commented on components/common/AddressForm/AddressForm.tsx
> +    reset(contact)
it was not reflecting whenever the prop changed.

2022-08-02 09:50 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  const { checkout, isUserLoggedIn = false } = props
removed.

2022-08-02 09:50 UTC, kibo-chandradeeptalaha commented on lib/getters/accountDetailsGetters.ts
> +}
Done.

2022-08-02 09:50 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  CardTypeForCheckout,
Done.

2022-08-02 11:25 UTC, kibo-chandradeeptalaha commented on components/order/view-order-details/ViewOrderDetails.tsx
> +              postalOrZipCode={
Done

2022-08-04 11:22 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.tsx
> +    setShippingAddress(contact as Contact)
Why are saving shipping addresses here? Do we really need it?

2022-08-04 11:22 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  }, [isCustomerCardsSuccess, isCustomerContactsSuccess, checkout])
I think we should divide useEffect code in multiple small methods and call these methods in useEffect to increase code readability and maintainability

2022-08-04 11:22 UTC, kibo-sushant commented on components/checkout/PaymentStep/PaymentStep.tsx
> +        <FormControl sx={{ maxWidth: '26.313rem' }}>
shouldn't this size in pixel?

2022-08-04 12:17 UTC, kibo-chandradeeptalaha commented on components/common/AddressForm/AddressForm.tsx
> +    onSaveAddress({ contact: formData, isBillingAddressValid: true })
Done

2022-08-04 12:22 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentCardDetailsView/PaymentCardDetailsView.tsx
> +  onPaymentCardSelection?: (value: string) => void | null
when we are not passing radio prop, we dont need that prop.

2022-08-04 12:22 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentCardDetailsView/PaymentCardDetailsView.tsx
> +          onChange={(value) => (onPaymentCardSelection ? onPaymentCardSelection(value) : null)}
No

2022-08-04 12:24 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +    setShippingAddress(contact as Contact)
Yes.

2022-08-04 13:56 UTC, kibo-chandradeeptalaha commented on components/common/PaymentCard/PaymentCard.tsx
>    expireMonth?: number
Done

2022-08-04 13:57 UTC, kibo-chandradeeptalaha commented on components/common/KiboRadio/KiboRadio.tsx
> +  align?: string
Done

2022-08-04 13:57 UTC, kibo-chandradeeptalaha commented on components/checkout/DetailsStep/DetailsStep.tsx
> +        // ],
Done

2022-08-04 19:17 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  const [shippingAddress, setShippingAddress] = useState<Contact>({})
Why does this paymentstep need to setShippingAddress?

2022-08-04 20:16 UTC, kibo-kevinwatts requested changes

2022-08-04 20:16 UTC, kibo-kevinwatts commented on lib/gql/fragments/userContacts.ts
> +    auditInfo {
we don't need audit info, faxNumber, companyOrOrganization

2022-08-04 20:16 UTC, kibo-kevinwatts commented on lib/helpers/credit-card/index.ts
> +import { CardForm } from '@/lib/types'
import type {

2022-08-05 06:36 UTC, kibo-chandradeeptalaha commented on components/checkout/ShippingStep/ShippingStep.tsx
> +      setStepStatusIncomplete()
I think @kibo-sushant can comment on this.

2022-08-05 08:26 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  const [shippingAddress, setShippingAddress] = useState<Contact>({})
We are just storing that data to toggle the data on address form if we check the same as billing address option.

2022-08-05 08:27 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +          ...card,
Done

2022-08-05 08:27 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +          contactId: 0,
Removed

2022-08-05 08:27 UTC, kibo-chandradeeptalaha commented on components/checkout/SavedPaymentMethodView/SavedPaymentMethodView.tsx
> +        withoutRadioTitle={displayTitle ? t('payment-method') : ''}
Refactored.

2022-08-05 08:27 UTC, kibo-chandradeeptalaha commented on lib/getters/accountDetailsGetters.ts
> +const getcustomerAccountCards = (customerAccountCards: CardCollection): Card[] =>
Done

2022-08-05 08:28 UTC, kibo-chandradeeptalaha commented on lib/getters/accountDetailsGetters.ts
> +const getSavedPaymentAndBillingDetails = (
Done.

2022-08-05 08:28 UTC, kibo-chandradeeptalaha commented on lib/gql/fragments/userContacts.ts
> +    auditInfo {
Removed.

2022-08-05 08:28 UTC, kibo-chandradeeptalaha commented on lib/helpers/credit-card/index.ts
> +import { CardForm } from '@/lib/types'
Done

2022-08-05 14:01 UTC, kibo-chandradeeptalaha commented on lib/gql/fragments/userContacts.ts
> +    auditInfo {
Removed

2022-08-05 17:09 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  const [shippingAddress, setShippingAddress] = useState<Contact>({})
I don't see the state `shippingAddress` referenced anywhere in this component though

2022-08-05 17:10 UTC, kibo-kevinwatts commented on components/checkout/PaymentStep/PaymentStep.tsx
> +      ...billingFormAddress,
Why wouldn't this be something like

```
const contact = value? fulfillmentContact : initialBilling
setBillingFormAddress({
...contact
isSameBillingShippingAddress: value
})
```

2022-08-05 18:56 UTC, kibo-chandradeeptalaha commented on components/checkout/PaymentStep/PaymentStep.tsx
> +  const [shippingAddress, setShippingAddress] = useState<Contact>({})
Sorry about that. I was testing and forgot to change the reference. Should be fixed now.

2022-08-10 12:58 UTC, kibo-kevinwatts approved these changes

2022-08-10 14:29 UTC, merged